:userdoc.
:prolog.
:docprof hyphen=yes justify=yes layout=1 tipage=right.
:docprof toc='*5' style=packet.
:title stitle='Packet Tutorial'.
:library.
Amateur Packet Radio
:topic.
A Complete Tutorial
:release.Evie Cooper
:etitle.
:docnum.9963-0413-56
:partnum.0413-56
:filenum.PACKET
:date.January 15, 2026
:author.Evie Cooper
.nameeps cmstype=eps pdsfull='wec.doc.eps'
:artdef id=prcover name=prcover.
:eprolog.
:frontm.
:cover artid=prcover.
:tipage.
:notices.
This document originated from the HSnet Document Management System.

When placing this book in a binder, place the cover page with artwork
on it in the slip cover at the front and discard the second cover page
if you wish.
:enotices.
:vnotice.
:vnhd.First Edition, January 27, 2026
:note.This is the initial version of this document, so it is likely to
have all manner of errors.
:coprnote.&copr. Evie Cooper 2026
:coprext.Not for use where life or limb may be at risk.
:evnotice.
:preface.Preface
:p.I have tried to compose this to be as turnkey as possible, but I
will have inevitably made mistakes somewhere. If you find any, please
email me at :hp3.wec@bam.moe:ehp3.!
:p.AI statement: no generative AI was used in the composition of this
work.
:p.This document was formatted on an IBM System/390 Multiprise 3000
mainframe running z/VM 4.4 with BookMaster 1.4.
:toc.
:figlist.
:tlist.
:body.
:h1.An Introduction to Packet Radio
:p.Packet radio is a very advanced world, and I assure you that this
guide only barely does the protocol family justice. Amateur packet
radio has a rich history of protocol development and asserting an
influence on later network protocol stacks, and played a pivotal
development in the popularization of the Internet Protocol with
hobbyists.
:h3.Original Packet Radio
:p.In the past, computer networks were not nearly as commonplace,
accessible, or affordable-to-construct as they are today. Before the
modern era, the ARPAnet was inaccessible to anyone that wasn't a
government employee, contractor, or university student in the US; while
that did exist, the world was dotted by numerable :hp1.corporate
networks:ehp1. that used strange protocols, unusual hardware, and were
of no interest to the casual hobbyist. Where the ARPAnet required the
blessing of the US government and enterprise networks required strange
mainframes, communications controllers the size of refrigerators, and
things like that, the amateur radio operators of the late 1970s and
early 1980s looked on to things their peers had developed :hp1.but
seemed so out-of-touch.:ehp1.
:p.An important milestone in the development of computing networking
was Professor Norman Abramson at the University of Hawaii's project:
:hp2.ALOHAnet.:ehp2. The Hawaiian Islands were separated by oceans, and
it was not affordable for a group of universities to lay cables into
the ocean to connect their sites; as such, Dr. Abramson sought a
wireless approach. He figured that since a single radio station could
cover a sizable portion of the Islands, couldn't the same approach work
for a wireless computer network?
:p.The development of ALOHAnet resulted in a 9600 baud UHF packet radio
system that had reasonably been perfected by 1975, and the Aloha
medium-multiple-access protocol had inspired many descendent
technologies.
:fn.An interesting offshoot of the Aloha protocol was, of all things,
:hp1.Ethernet:ehp1.; the designers called it :q.Aloha in a wire:eq. and
were not far-off -- both systems used the same CSMA medium access
control technique.
:efn.
:p.In the San Francisco Bay, DARPA worked with SRI International to
construct a network called PRNET; this was the aptly-named :hp2.Packet
Radio NETwork.:ehp2. These researchers worked from 1973 to 1976 to run
the ARPAnet NCP protocol (which preceded the current Internet Protocol,
but is :hp1.radically:ehp1. different) wirelessly. Rather than using a
more primitive FSK modem design like the ALOHAnet project did, PRNET
used direct-sequence-spread-spectrum modems that included a forward
error correction algorithm -- this resulted in 100 kbps and 400 kbps
radio channels filling the air. Most pivotally, the PRNET project
demonstrated the first :hp1.internetworking:ehp1. wherein the ARPAnet,
PRNET, and SATNET (a satellite communications network) were interlinked.
:fn.The site of the first internetworking was a GMC Value-Van that Don
Cone had filled with radio equipment and computer equipment (which was
a DEC PDP-11/03 LSI-11 minicomputer); on November 22, 1977, the
Internet was born.
:efn.
:h3.Ham Packet Radio
:p.Amateur packet radio started in Montreal, Quebec in May 1978: VE2PY
(Robert Rouleau), VE2BQS (Norm Pearl), and VE2EHP (Jacques Orsali)
acquired special authorization from the Canadian government (an
:q.Amateur Radio Digital Operator's Certificate:eq.) to transmit
ASCII-encoded data on the 1.25-meter amateur band with custom
equipment. On the other side of the continent, VE7APU (Doug Lockhart)
and his group, the Vancouver Area Digital Communications Group) began
to produce proper modems that were much more capable than the earlier
Montreal Amateur Radio Club work. These devices became known as
:hp3.Terminal Node Controllers.:ehp3.
:p.South of Canada in the United States, the FCC permitted ASCII
transmissions in 1980; shortly after that in December 1980, KA6M (Hank
Magnuski) had erected the first packet repeater on 2 meters. Since the
old NCP protocol had yet to be replaced, Hank scored a very valuable
victory: the :hp1.entirety:ehp1. of the :pk.44.0.0.0/8:epk. network was
allocated for amateur radio, and became known as AMPRnet.
:fn.In keeping with the ARPANET theme.
:efn.
:p.Two years later (in January 1983), NCP was replaced with TCP, and
RFC 790 listed it amongst several other networks.
:fn.Interestingly enough, the now-ubiquitous :pk.10.0.0.0/8:epk.
network was a direct mapping of the ARPANET address space -- the
Internet has had several major addressing scheme overhauls throughout
its history!
:efn.
:p.1982 was a pivotal year for packet radio. The Pacific Packet Radio
Society (California), the Tuscon Amateur Packet Radio Corporation
(TAPR, Arizona), and the Amateur Radio Research and Development
Corporation (AMRAD, Washington, D.C.) were hot on the trails of
developing consumer hardware for this new craze.
:p.All of these incompatible TNCs meant that, though everyone used Bell
202 modems, nobody could interlink with each other. Everyone claimed to
use a modified :q.Vancouver Protocol:eq. (based on the work of VADCG),
but nobody really was. In 1982, several meetings were held, consisting
of many of the big names in packet radio of the day. They realized they
needed a standard, and they eventually came up with the :q.Amateur
Radio Protocol.:eq.
:p.This protocol was based on the extremely popular X.25 protocol, and
was named AX.25 (more information on it will be presented after this
chapter). It was WB4JFI (Terry Fox), who was the head of the ARRL's
:hp1.Ad-Hoc Committee on Amateur Radio Digital Communication:ehp1. who
signed off on the standard after it had been decided; this occurred on
October 26, 1984.
:p.AX.25 was a massive improvement over the existing VADCG protocols.
For one, it could handle 128 connections at the same time -- on the eve
of AX.25's standardization, it was estimated that were no more than 200
hams using packet radio in the entirety of the US and Canada combined!
One of the early TNCs that was responsible for settling this issue was
produced by a company called :q.Bill Ashby and Sons:eq.; that company
built a simple board based off of the Vancouver protocol hardware and
software, and made it available. Richcraft Engineering, ran by W4UCH,
came up with an ingenious idea: use the CP/M microcomputer OS to
implement a software-based packet radio stack. This greatly simplified
part complexity, and removed the need to use actual modem parts (often
called :q.HDLC controllers:eq. because they were lifted straight from
wireline X.25 modem hardware). After that, GLB Electronics came onto
the scene with something that would become extremely familiar to anyone
that finds old TNCs at hamfests: they designed a simple and cheap
Z80-based microcomputer that drove the audio interface much in the same
way that the Richcraft board did; this was the PK-1, and it was the
first popular software-only TNC.
:p.The TAPR was a strange bunch, and consisted of not more than 20
amateurs. On a weekend, they all met in the University of Arizona's
Computer Science building, and pitched an interesting project idea:
:q.could we develop a cheap packet radio system that was capable of
transmitting microcomputer software via the airwaves?:eq.
:p.Interestingly, many of the TAPR engineers worked for Motorola, who
was just down the street; the efforts of that club were shown to the
world in 1982 at the First American Radio Relay League Computer
Networking Conference. Drawing on the successes of the past, they
launched a very good and high-quality TNC kit in July 1983; whereas the
earlier attempts were somewhat shoddy in their design and just as bad
in their manufacturing, the TAPR kits felt :hp1.almost
professional:ehp1. -- the quality of their kits readily rivalled
commercial radio vendors (as in, companies that made radio hardware for
the non-amateur :q.real world:eq. market). The first run of this TNC
was at 9:12 PM PST on June 25, 1982; blazing away on 146.55 MHz, KD2S
(Den Connors) and Lyle Johnson (WA7GXD) held the first contact using
Heath H-89 serial terminals.
:p.In 1984, the TAPR TNC-1 board took the world by storm. It wasn't for
lack of trying, though; the production of the boards was very troubled.
In December 1982, just as they were getting ready to launch the
aforementioned board, the TAPR guys were having nonstop solder problems
on their circuit board assembly line. This resulted in a mad dash to
fix the productions, but the group was successful -- the board took the
world by storm.
:p.As soon as these became commonplace, all manner of bulletin board
systems (BBSes) began to pop up. One of the first BBSes put up on the
East Coast was by AI2Q (Alex Mendelsohn), and was powered by a Xerox
820 desktop computer running CP/M. Digipeaters quickly cropped up,
bringing the footprint of these BBSes to hundreds of mile in a matter
of weeks. Since the packet radio stack ran on that Xerox 820, NW2X
(Howie Goldstein) had a bright idea during his time as a student at the
Florida Institute of Technology: use the surplus and obsolete Xerox 820
motherboards to greatly evolve the function of those TAPR TNC-1 boards!
:p.The TNC-2 was announced at the 1985 Dayton Hamvention, to amazing
acclaim. This was based on the same idea as the early Z80 soft-TNC
pioneers, but greatly upgraded after many had experimented with the
TNC-1 and Xerox 820 combination system. The TNC-2 contained a Z80, some
RAM, a ROM chip, and a modem interface; this was quickly licensed out
to several companies, who began manufacturing them all over the world.
By the early 90s, TNC-2 devices were ubiquitous. Packet radio had hit
it big, arguably much bigger than it is today.
:p.Now, it is up to you to breathe life back into this amazing
forgotten world in an age of an uncertain Internet future.
:h3.Bringing it Together
:p.Before proceeding, I recommend you familiarize yourself with some
key terms heard in packet radio:
:ul.
:li.Packet Radio: a collection of hardware and software that performs
network communications via radio
:li.TNC (Terminal Node Controller): a box or program that connects a
computer or terminal to a radio and performs the
modulation/demodulation tasks required to generate a baseband signal
containing data
:li.Node: a host on a packet radio network, usually capable of
receiving inbound connections
:li.BBS (Bulletin Board System): a special kind of node that stores
messages (and sometimes forwards them off to other nodes)
:eul.
:p.For 99% of packet radio installations, the TNC will connect to a
VHF/UHF FM radio through its :hp3.audio interface;:ehp3. it also likely
has the ability to :hp3.key the radio:ehp3. -- since accurate
transmit/receive timings are paramount for packet radio, :hp2.you
cannot use your radio's VOX control for bidirectional packet:ehp2. (and
you should not use it for unidirectional packet either, honestly)!
:lblbox.Audio filtering and high-speed packet
:p.For most people using a Baofeng HT or mobile radio, the highest
speed you will be able to attain is 2400 baud (with 1200 baud being the
most common, for things like APRS). This is not because packet radio
has not evolved (in fact, there are megabaud packet radio systems), but
because the radio applies an audio filter on both the microphone input
and the audio output.
:p.The audio input is filtered to cut off any audio below 300 Hz (this
is to prevent bass tones from tripping a repeater's PL tone decoder,
which may stop you from being able to transmit into the repeater for
the duration of your transmission) and above 4 KHz (to conserve FM
bandwidth); likewise, the audio output is filtered to remove anything
above 4 KHz and below 300 Hz (to prevent screws backing out due to
constant PL tone bass vibrations on the speaker, or so I'm told).
:p.As such, in order to go faster (such as up to 9600 baud, the
most-desired speed), one must do away with these filters. This is done
by :hp2.tapping the discriminator:ehp2. and :hp2.directly driving the
modulator.:ehp2. This can be done by examining the schematic for your
radio, but many VHF/UHF mobiles made through the late 1990s to today
contain a port at the back that has a 9600 baud packet output; note
that it is paramount that you check the manual to determine what the
output level is (too low of an output level results in poor reception)
and ensure you do not overdrive the modulator input (doing so could put
your transmissions out-of-spec).
:elblbox.
:fig width=column place=inline frame=none.
:artwork name=prlpf align=center.
:figcap.VHF/UHF LMR audio frequency range
:efig.
:h1.Surveying the Landscape: Protocols and Stacks
:p.When discussing packet radio, it helps to have an understanding of
the numerable protocols found on the air:
:ul.
:li.AX.25
:li.KISS
:li.NET/ROM
:li.ROSE
:li.TCP/IP
:li.APRS
:eul.
:p.Before we get carried away, it is a good idea to familiarize oneself
with these protocols:
:h3.AX.25 (and KISS)
:p.The primary network protocol of amateur packet radio is
:hp3.AX.25.:ehp3., and it is a :hp3.link layer protocol.:ehp3. This is
a protocol derived from the earlier (but once extremely popular)
:hp1.X.25:ehp1. protocol family, a stack of protocols that provided:
:i1.AX.25 Protocol
:ul.
:li.A relatively simple protocol family that could be implemented
anywhere from large mainframe computers to small boxes that attached to
terminals
:li.Packet-switched networking, wherein :q.virtual circuits:eq. would
be propped up like TCP sockets are today on the TCP/IP protocol family
:fn.Keep that :hp3.virtual circuit:ehp3. term in mind as you read this,
as it is critical to understanding AX.25
:efn.
:li.Congestion control, retransmission, and other such features for
reliable communications on network links of uncertain reliability
:eul.
:p.:hp1.If you are passingly-familiar with :hp3.TCP:ehp3., you may
realize that these X.25 features share significant overlap with TCP
features -- TCP was intended to emulate the X.25 PLP (packet layer
protocol) over IP.:ehp1.
:h5.Addressing Scheme
:p.AX.25 provides a very simple service: a virtual circuit, between two
callsigns (which includes the SSID). This means that AX.25 addresses
use ham radio callsigns, so :pk.WA4XYZ-6:epk. and :pk.N4ABC:epk. are
valid.
:p.The suffix after the dash is called the :hp3.SSID:ehp3., i.e. the
Service Set Identifier. This allows you to have 16 different AX.25
addresses with one callsign; by convention, you would not
write:pk.N4ABC-0:epk., but would instead write :pk.N4ABC:epk. without
the suffix.
:i2.SSID
:p.The fundamental unit of AX.25 communication is the :hp3.frame.:ehp3.
This contains the destination callsign, source callsign, protocol
number, and a control byte; the control byte selects the frame type
(shown below), and the protocol number identifies the packet contents
(also listed below).
:h5.Operating Modes
:p.AX.25 has two operating modes: disconnected and connected. In the
disconnected mode, the following frame types may be sent:
:ul.
:li.:pk.SABM:epk. (Set Asynchronous Balanced Mode), used to initiate a
connection
:li.:pk.DISC:epk. (Disconnect), to disconnect any stale connections
:li.:pk.XID:epk. (Exchange Identification), sometimes used to exchange
station protocol capabilities
:li.:pk.UA:epk. (Unnumbered Acknowledge), to acknowledge an SABM or
DISC frame
:li.:pk.UI:epk. (Unnumbered Information), a frame that contains a bit
of information blasted verbatim without being contained within a
virtual circuit
:eul.
:p.When station 1 sends an SABM frame to station 2, station 2 will
hopefully reply with a UA frame -- if this does happen, the two
stations will now be :q.connected:eq.. In this state, the following
frames can be sent:
:ul.
:li.:pk.I:epk. (Information), a frame that contains the virtual circuit
:q.payload:eq.; this is transmitted alongside a send and receive
sequence number (which is used to ensure the packets are arriving)
:li.:pk.RR:epk. (Receiver Ready), to inform the recipient of the packet
that it got it and to inform the transmitting station to proceed
sending more
:li.:pk.REJ:epk. (Reject), if one side receives an I-frame with an
invalid :pk.N(S):epk. value (i.e. send sequence number)
:li.:pk.RNR:epk. (Receiver Not Ready), if the receiving station is
unable to process packets for whatever reason (perhaps it is out of
computational resources)
:eul.
:h5.Packet Format
:p.As you may imagine, UI frames are often used for beacons or to carry
additional network protocols. Now, examine the following diagram of an
AX.25 frame:
:i2.Packet format
:fig width=column place=inline frame=none.
:artwork name=prax25 align=center.
:figcap.AX.25 frame structure
:efig.
:p.Note that the image here is good for either a numbered or unnumbered
frame (that is, connected-mode or unconnected-mode). It is a good idea
to break down the packet structure for additional clarity:
:ul.
:li.Address: the address field here is variable-length (as shown, 14 to
28 bytes) since this can accommodate a plain source/destination pair or
:hp3.up to two digipeaters:ehp3.. :hp1.A digipeater is a packet
repeater system, usually simplex; you can only have two digipeaters
along a path!:ehp1.
:i2.Digipeater
:li.Control: this conveys the field type, seen in the above list; it
may span two bytes -- this is necessary to accommodate the sequence
numbers (which run :hp3.0 to 7:ehp3. so 4 bits; :pk.N(R):epk.
and:pk.N(S):epk. fit nicely in one byte together)
:li.PID (Protocol ID): this specifies the protocol contained within the
packet. The current registered values are as follows:
:i2.PID/protocol numbers
:ul.
:li.0x01: ISO 8208 (X.25 Packet Layer Protocol)
:fn.See the section on ROSE for more information on this.
:efn.
:li.0x06: VJ-compressed TCP/IP
:fn.This is the same compression algorithm used for :q.IP Header
Compression:eq. on PPP networks.
:efn.
:li.0x07: VJ-compressed TCP/IP (for an uncompressed frame)
:li.0x08: Segmentation fragment
:li.0xC3: TEXNET Datagram Protocol
:li.0xC4: Link Quality Protocol (LQP)
:li.0xCA: AppleTalk
:li.0xCB: AARP (AppleTalk)
:li.0xCC: IPv4
:li.0xCD: ARP (ARPA)
:li.0xCE: FlexNet
:li.0xCF: NET/ROM
:li.0xF0: no layer-3 protocol; the payload is raw text
:li.0xFF: escape character for a two-byte protocol field
:eul.
:eul.
:p.:hp1.The :q.no layer-3:eq. AX.25 operating mode is used for
connections from a packet terminal to a BBS or packet radio
command-line shell node.:ehp1.
:p.In an unconnected state, you can send and receive UI-frames by using
some specific command that the TNC or packet stack provides; there is
no acknowlegement. In a connected state, I-frames are sent instead and
both sides expect to exchange those RR frames. The :hp5.window
size:ehp5. controls how many packets each side can exchange before a RR
frame must be sent. Finding a good window size is crucial to reliable
network links! As mentioned above, the sequence numbers run :hp2.0 to
7:ehp2., and so does the range for possible window size values.
:lblbox.A Bigger Window?
:p.There is a mechanism to get more than 8 packets in a window, and it
is called :hp3.modulo-128:ehp3.; it lengthens the size of the control
field to three bytes (with byte 1 being the frame type, byte 2 being
the modulo-8 window size, and byte 2 and 3 together being the
modulo-128 window size). Most packet radio stacks support this, but no
real TNCs do as far as I am aware.
:elblbox.
:i2.Window Size
:h5.From Packet to Transmission
:p.The next step of transmission occurs if you are driving your packet
TNC from a PC running the AX.25 network stack code on a PC.
:fn.Most TNCs from the 1980s and 1990s have a ROM that provides a
simple command-line interface to AX.25 no-layer-3 connections (that is,
simple textual connections) without the aid of a PC.
:efn.
Before being sent to the TNC, the packet needs to be wrapped in a
:hp3.KISS:ehp3. frame. KISS, short for Keep It Simple Stupid, is a
protocol that is very reminiscent of the UNIX SLIP (Serial Line IP)
protocol. The AX.25 frame is wrapped in :pk.0xC0:epk. bytes, and any of
those bytes encountered in the packet are escaped with a double-byte
escape. Examine the following diagram of a KISS frame:
:i2.KISS
:fig width=column place=inline frame=none.
:artwork name=prkiss align=center.
:figcap.KISS + AX.25 frame structure
:efig.
:p.Now, just before transmission (this is done in the TNC), the AX.25
frames are stripped of their KISS framing and wrapped into an
:hp3.HDLC:ehp3. frame, just like X.25. HDLC (High-level Data Link
Control) is the equivalent of the Ethernet MAC protocol for X.25
networks -- it provides a very simple link layer protocol that X.25
rode on top of. AX.25 is similar, except it replaces most of the fields
of an HDLC frame; AX.25 encapsulated into HDLC only adds the frame mark
byte (which is always :pk.0x7E:epk.) and a frame check sequence (the
standard HDLC CRC algorithm computes this) at the end.
:i2.HDLC
:p.Examine the following diagram to see an HDLC-encapsulated AX.25
frame:
:fig width=column place=inline frame=none.
:artwork name=prhdlc align=center.
:figcap.HDLC + AX.25 frame structure
:efig.
:lblbox.Two link-layer protocols?
:p.This is a common question heard when discussing non-TCP/IP
protocols; a number of non-Ethernet-based protocols have what one might
would describe as more than one link-layer protocol! X.25 is a
network-layer protocol, and it used HDLC over :hp1.synchronous-serial
links:ehp1. (similar to KISS). Now, when the AX.25 frame is sent to the
TNC, it is wrapped in a KISS encapsulation; when that packet arrives at
the TNC from the host computer, the TNC's firmware will strip the KISS
encapsulation off, re-frame it into HDLC :hp1.instead:ehp1. instead of
KISS, then proceed with the packet encoding and modulation.
:elblbox.
:p.Once the packet has arrived at the TNC and has been re-framed in
HDLC framing, it will be encoded using some kind of serial data
encoding algorithm (like NRZ, NRZI, or Manchester coding), modulated,
and the audio stream will be sent to the radio for transmission.
:p.For the TNCs that use 6PACK framing, the TNC directly speaks an
HDLC-like protocol (and the attached computer is much more aware of the
status of the RF channel). The 6PACK protocol results in the TNC
telling the host computer whenever it is receiving data, and the host
computer can trigger (in much more detail) partial transmissions.
:lblbox.What's the point of 6PACK?
:p.6PACK is an alternate framing method (i.e. :q.line discipline:eq.)
to KISS that allows for multi-dropped TNCs (multiple TNCs on a serial
port daisy chain). TNCs that provide this function are rare in the
modern era, but it was once provided by swapping out the ROM chips in
the TNC.
:elblbox.
:h3.NET/ROM
:p.When AX.25's limit of two digipeater hops started to become an issue
in the late 80s (as packet networks were exploding in popularity by
this time), a solution needed to be found, and found fast! This
originally came in the form of a ROM chip (made by Software 2000) that
replaced the factory ROM in a TNC-2 compatible TNC (such as the
ubiquitous ones made by MFJ), and was called :q.the Net ROM:eq.. Soon
thereafter, the protocol it spoke became known as :hp2.NET/ROM.:ehp2.
:i1.NET/ROM
:p.NET/ROM alleviates the two-hop constraint by allowing nodes to set
up virtual circuits between themselves, then packets could pass through
many nodes simply by passing through those virtual circuit tunnels.
:hp5.Since AX.25 has a limitation of one virtual circuit tunnel per
callsign pair per protocol number, it is highly recommended that you
use a different SSID for your :q.basic AX.25 connections:eq. and your
NET/ROM node.:ehp5.
:fn.In an ideal world, you could use the same callsign for both base
AX.25 (i.e. no-L3 connections to a node or BBS) and NET/ROM, but due to
a practical limit in the old NET/ROM TNC firmware of the past (and
apparently in some modern packet radio stacks), you must use different
SSIDs -- this is because the node lumps all packets from one node to
another under the same umbrella, regardless of the protocol ID number.
:efn.
:p.Once the NET/ROM tunnels have been established, the same frame types
are used as AX.25 used; to start a connection, :pk.SABM:epk.
and:pk.UA:epk. frames are used, then I-frames and :pk.RR:epk. frames
throughout the duration of the session!
:h5.Addressing Scheme
:p.Rather than relying on callsigns explicitly, NET/ROM often uses
:hp1.node name aliases.:ehp1. For instance, your BBS could be
named:pk.NYBBS:epk., and your own node could be named :pk.WECNOD:epk..
In order to build up a collection of nodes and adjacency, NET/ROM nodes
emit :hp5.node broadcasts:ehp5. on a fixed timer (which is inevitably
changeable by the user); once adjacent nodes receive these packets, the
virtual circuit tunnels open and NET/ROM packets may pass.
:i2.Addressing
:p.Some packet radio stacks (namely XRouter) refer to a NET/ROM
connection as a :q.layer 4:eq. connection; by a contrast, a no-L3
connection would be a :q.layer 2:eq. connection.
:fn.Remember, a no-L2 connection is a plain AX.25 textual connection!
:efn.
:lblbox.So, what are all these layers?
:p.Network stacks are divvied up into :q.layers:eq., and this notation
is used to conceptualize network protocol families. To provide you with
a visual overview, please see the below image.
:elblbox.
:fig width=column place=inline frame=none.
:artwork name=prlayers align=center.
:figcap.Packet radio protocol layers
:efig.
:h5.Routing and Quality
:p.NET/ROM, as mentioned before, uses node names to build up its
routing table. As more and more NET/ROM nodes pop up on a network and
begin to exchange routing tables, there needs to be some kind of way of
preventing a long path from being taken when a shorter path is
possible. This is remedied by the :hp5.quality metric:ehp5. associated
with the port.
:i2.Routing (quality)
:p.NET/ROM routing broadcasts emitted from a port will contain a
quality, and any subsequent retransmissions of other routing tables
will have some quality shaved off with each routing table emission from
each node along a path.
:h5.NET/ROM Serial Protocol
:p.When the original NET/ROM-capable TNC ROMs became available in the
mid-80s, KISS mode was the :hp1.de facto:ehp1. standard for driving
TNCs; for efficiency reasons, several hams realized they could drop the
AX.25 encapsulation and :hp1.just:ehp1. carry NET/ROM packets to and
from the TNC. This became known as the :hp2.NRS:ehp2. protocol.
:i2.NRS (NET/ROM Serial Protocol)
:h3.ROSE
:p.The RATS Open Systems Environment is a direct port of the :hp1.X.25
PLP:ehp1. (Packet Layer Protocol) to run on top of AX.25. Like the
original X.25 PLP, ROSE uses the standard 10-digit X.25 addressing
scheme (frequently called :hp3.X.121:ehp3. addresses) and requires
manual mapping of callsigns to network numbers. Like NET/ROM, full
routing is permitted.
:i1.ROSE
:p.Unfortunately, ROSE was not very well-adopted; the Linux kernel's
AX.25 stack contains the most complete implementation of ROSE, but even
it is buggy and not worth running.
:h3.Internet Protocol
:p.Despite many efforts to establish some alternate protocol as the
dominant network protocol of the world, the :hp1.ARPA Internet
Protocol:ehp1. became the world standard; you probably used IP to get
this document!
:i1.IP (Internet Protocol)
:p.IP is very often seen alongside several other protocols riding on
top of it:
:ul.
:li.:pk.TCP:epk. (Transmission Control Protocol), used to set up
virtual circuits with reliable connections that handle dropouts,
unexpected disconnections, and other similar failures
:li.:pk.UDP:epk. (User Datagram Protocol), used to transmit
non-reliably-delivered datagrams between hosts
:li.:pk.ICMP:epk. (Internet Control Message Protocol), used to allow
network hosts to test communication (this is the :pk.ping:epk.
command), detect adjacent routers (ICMP redirects), and alert hosts
that UDP ports are not listening
:li.:pk.SCTP:epk. (Stream Control Transmission Protocol), an evolved
version of TCP that never caught on
:eul.
:p.The structure of an IP packet is as follows:
:fig width=column place=inline frame=none.
:artwork name=prippkt align=center.
:figcap.IPv4 and IPv6 Packets
:efig.
:p.The source and destination IP addresses can be seen, as well as the
:hp2.protocol:ehp2. number, which will be discussed further down. The
:hp2.TTL:ehp2. (Time-to-Live) field specifies the amount of routing
hops a packet can take before routers will stop routing it.
:h5.IPv4 and IPv6
:p.Furthermore, there are two distinct versions of IP: :hp3.IPv4:ehp3.
and :hp3.IPv6:ehp3.: IPv6 was created to rectify the
address-space-exhaustion issue IPv4 was facing in the late 90s. IPv4
addressing takes the form of four dotted-decimal :hp5.octets:ehp5.
(i.e. an eight-bit number; these run 0 to 255) -- for
example, :pk.44.192.15.221:epk.. IPv6 addresses, on the other hand, are
much more complex (as they consist of eight hexadecimal 16-bit words,
running :pv.0000:epv. to :pv.FFFF:epv.):
:xmp.
2062&colon.41FE&colon.653A&colon.9882&colon.511&colon.FFE9&colon.8392&colon.412D
:exmp.
Note that zeros are omitted from this IPv6 addressing scheme -- an
address that has entire words of zeros can be abbreviated.
Take the following example IPv6 address:
:xmp.
2062&colon.41FE&colon.653A&colon.0000&colon.0000&colon.0000&colon.8392&colon.412D
:exmp.
This can be shortened down to:
:xmp.
2062&colon.41FE&colon.653A&colon.&colon.8392&colon.412D
:exmp.
:h5.Subnetting
:p.Another important concept in IP networking are the important
definitions of the :hp1.host address, host address, broadcast address.,
and netmask.:ehp1. The host address is what you already saw before --
something like :pk.192.168.9.21:epk.. For our example, let us say that
the netmask is set to :pk.255.255.255.0:epk.. Now, if you convert both
the network address and netmask into binary, you can discover what the
netmask does, what our network address is, and also our broadcast
address. Examine this example to see that conversion:
:i2.Subnetting
:xmp.
192.168.9.21     11000000.10101000.00001001.00010101
255.255.255.0    11111111.11111111.11111111.00000000
:exmp.
:p.When you examine this example, you can see that the subnet mask is
completely overlaying all of the first three octets of that host
address. If we zero out all the bits on the portion of the host address
that aligns with the zeros in the netmask, you get the network address;
likewise, if we set all of those bits to one, you get the broadcast
address :hp1.for that network.:ehp1. These addresses look like this:
:xmp.
192.168.9.21     11000000.10101000.00001001.00010101
255.255.255.0    11111111.11111111.11111111.00000000
192.168.9.0      11000000.10101000.00001001.00010000
192.168.9.255    11000000.10101000.00001001.11111111
:exmp.
:p.Now, let's up the ant&ea.! How about if we use that same address,
but we change the address to :pk.255.255.255.128:epk.. We can now
recompute the addresses:
:xmp.
192.168.9.21     11000000.10101000.00001001.00010101
255.255.255.128  11111111.11111111.11111111.10000000
192.168.9.0      11000000.10101000.00001001.00010000
192.168.9.127    11000000.10101000.00001001.01111111
:exmp.
:p.Rather than writing out long netmasks, there is an abbreviation
(colloquially called CIDR, pronounced :q.cider:eq.) that allows you to
write the netmask by just noting the amount of bits in the netmask.
Since the bit consumption of the netmask always marches left-to-right,
with no zeros that have any ones to the right of the address (at least
until the end), one can write :q.192.168.1.15 with a netmask of
255.255.255.0:eq. as :q.192.168.1.15/24:eq.!
:i3.CIDR notation
:p.IPv6 addressing follows the same scheme, except the examples are
large enough to roll off the page!
:lblbox.About subnetting
:p.The practice described above, :hp2.subnetting:ehp2., is used to
divide networks into different segments. Otherwise, every host on the
Internet would be on the same logical network, and a single broadcast
packet would easily bring the worldwide network to it knees. The key
thing to know here is that :hp1.hosts who share different network
addresses are no longer on the same network, and you must use a
:hp3.router:ehp3. to allow those hosts to communicate:ehp1. A router
forwards packets between networks, facilitating the creation of the
Internet.
:elblbox.
:h5.Link-Layer Address Resolution
:p.A key part of both IPv4 and IPv6 is the concept of discovering what
Ethernet MAC address/AX.25 callsign/PPP peer maps to an IP address.
IPv4 does this with a protocol called :hp3.ARP:ehp3., the Address
Resolution Protocol. IPv6 does this with the :hp3.Neighbor
Discovery:ehp3. subset of :hp3.ICMPv6:ehp3..
:p.To understand ARP, examine this simple example of two hosts trying
to communicate:
:ul.
:li.PC 1 and PC 2 are on an Ethernet network. PC 1 has the IP address
192.168.1.5, and PC 2 has the IP address 192.168.1.10 -- both are on
the same subnet (as in, they fall within the same network addressing
range). PC 1 sends a :pk.ping:epk. packet to PC 2.
:li.PC 1 does not know PC 2's Ethernet MAC address, so it cannot send
IP packets encapsulated in Ethernet frames. To remedy this, the
following things occur:
:ol.
:li.PC 1 sends an ARP request for 192.168.1.10 to the Ethernet
broadcast address, :pk.FF.FF.FF.FF.FF.FF:epk.
:li.PC 2 responds to PC 1's request by directing an ARP reply directly
to PC 1's MAC address.
:li.Both PC 1 and PC 2 know each others' MAC addresses, so they are
free to exchange the ping packet.
:eol.
:eul.
:p.Substitute :q.Ethernet:eq. for :q.AX.25:eq. and the portion above
would still read true.
:h5.Address Classes
:p.There is an important consideration to be had here: it is possible
to have an :hp1.implicit netmask:ehp1. based on the range that the host
address falls into. This table shows the class, range, and implicit
netmask:
:table cols='* * *'.
:tcap.IPv4 Address Classes
:row.
:c.:hp2.Class:ehp2.
:c.:hp2.Range:ehp2.
:c.:hp2.Default Netmask:ehp2.
:row.
:c.A
:c.0.0.0.0 - 127.255.255.255
:c.255.0.0.0
:row.
:c.B
:c.128.0.0.0 - 191.255.255.255
:c.255.255.0.0
:row.
:c.C
:c.192.0.0.0 - 223.255.255.255
:c.255.255.255.0
:row.
:c.D
:c.224.0.0.0 - 239.255.255.255
:c.:hp1.none, used for multicast:ehp1.
:row.
:c.E
:c.240.0.0.0 - 255.255.255.255
:c.:hp1.none, experimental:ehp1.
:etable.
:p.Class D addresses are used for :hp2.multicast:ehp2., wherein one
host can send a packet to several other hosts. This requires the medium
to be able to handle broadcast packets (which Ethernet and Wi-Fi, the
two most common link layer protocols that carry IP, support; so does
AX.25) or a router capable of processing :pk.IGMP:epk. packets
(Internet Group Management Protocol, which sets up multicast groups).
Once a multicast group has been set up, any host can send packets
directed to the multicast group address, and every host within that
group will be able to receive those packets (so long as they are
listening on the :hp1.port:ehp1. desired).
:h5.TCP and UDP
:p.As mentioned before, :pk.TCP:epk. and :pk.UDP:epk. are the most
common protocols that run on top of IP (besides ICMP); these are the
protocols that applications actually use to transfer data between
hosts. Since it would not make sense to only allow one connection
between two hosts, TCP and UDP provide a :hp2.port multiplexing:ehp2.
method wherein program listen on various port numbers; the other side,
which wishes to connect to a host listening on some port, simply opens
a connection to that port! Some ports are reserved for specific
application protocols; here are some common ports:
:table cols='* * *'.
:tcap.Common TCP and UDP Ports
:row.
:c.:hp2.Protocol:ehp2.
:c.:hp2.Application:ehp2.
:c.:hp2.Port Number:ehp2.
:row.
:c.TCP
:c.FTP
:c.20, 21
:row.
:c.TCP
:c.SSH
:c.22
:row.
:c.TCP
:c.Telnet
:c.23
:row.
:c.TCP
:c.SMTP
:c.25
:row.
:c.TCP/UDP
:c.DNS
:c.53
:row.
:c.UDP
:c.DHCP/BOOTP
:c.67
:row.
:c.UDP
:c.TFTP
:c.69
:row.
:c.TCP
:c.HTTP
:c.80
:row.
:c.TCP
:c.POP3
:c.110
:row.
:c.UDP
:c.NTP
:c.123
:row.
:c.TCP
:c.IMAP4
:c.143
:row.
:c.UDP
:c.SNMP
:c.161
:row.
:c.TCP
:c.HTTPS
:c.443
:etable.
:p.TCP and UDP themselves are identified in the IP packet through the
:hp2.protocol number:ehp2. which follows the destination IP and source
IP; here are some common IP protocol numbers:
:table cols='* *'.
:tcap.Common IP Protocol Numbers
:row.
:c.:hp2.Protocol:ehp2.
:c.:hp2.Description:ehp2.
:row.
:c.1
:c.ICMP
:row.
:c.2
:c.IGMP
:row.
:c.4
:c.IP-in-IP
:row.
:c.6
:c.TCP
:row.
:c.17
:c.UDP
:row.
:c.50
:c.IPsec ESP
:row.
:c.51
:c.IPsec AH
:row.
:c.93
:c.AX.25-in-IP
:row.
:c.94
:c.KA9Q IP-in-IP
:etable.
:h5.Tunnels
:p.Since IPv4 is the dominant protocol on the internet, clever network
engineers have sought to run protocols that did not win the standards
race over the Internet -- this is accomplished in the form of a
:hp2.tunnel.:ehp2. For our purposes, we will be discussing :hp3.AXIP
tunnels:ehp3., since we wish to join otherwise-disconnected packet
radio networks over the internet -- examples for how to set this up on
the various packet radio stacks will be provided below (contingent on
support existing for them).
:h3.TexNet
:p.When you read the AX.25 Protocol Number list above, you probably saw
:hp1.TexNet:ehp1. on that list! This is a defunct protocol that is
similar to NET/ROM, and was used for the Texas/Oklahoma/Arkansas packet
network of the same name. Nearly all sites on TexNet were 9600 baud
stations, :hp1.in the mid-1980s!:ehp1. Needless to say, though it is
defunct, its position in the development of NET/ROM is important to at
least note.
:h1.The Linux Kernel AX.25 Stack
:h3.Compiling/Installing the Packages
:p.Before we get too carried away, you're going to want to be using a
Linux system that contains the following packages:
:i1.Linux AX.25
:i2.Compiling
:ul.
:li.:pk.libax25:epk., the base library for all Linux AX.25 programs
:li.:pk.ax25-apps:epk., a set of programs for making and receiving
AX.25 connections
:li.:pk.ax25-tools:epk., some programs used for configuring network
protocols and devices
:li.:pk.node:epk. or :pk.uronode:epk., to create and run a packet radio
node/shell
:fn.:q.node:eq. refers to the ax25-node package, not NodeJS! This
program is becoming increasingly hard to find, but can be found by
Googling :pk.node_0.3.2.tar.gz:epk..
:efn.
:li.:pk.aprsd:epk., for creating and running an APRS digipeater
:li.:pk.direwolf:epk., a software TNC, :hp1.install this if you do not
have a real TNC or do not want to use it:ehp1.
:li.:pk.inetutils:epk., which contains FTP/Telnet/ntalk servers and
clients
:li.:pk.socat:epk., used to create loopback TTY devices (fake serial
ports) -- this will be used for AX.25 tunnels
:eul.
:p.It is also recommended that you install these too for
troubleshooting and debugging:
:ul.
:li.:pk.net-tools:epk., which provides the
older :pk.ifconfig:epk., :pk.arp:epk. and :pk.route:epk. commands that
understand the various packet radio protocols
:li.:pk.tcpdump:epk., a terminal-based network traffic monitor tool
:li.:pk.wireshark:epk., a graphical network traffic monitor tool that
produces easy-to-follow lists of network traffic
:li.:pk.screen:epk. or :pk.tmux:epk., programs that allow you to run a
command-line program on a disconnectable virtual terminal
:eul.
:p.Some of this you'll probably need to compile yourself. Debian calls
the node program "ax25-node" to avoid interfering with the NodeJS
programming language runtime (see that footnote).
Do note that libax25 requires the Linux kernel headers; these can be
installed from most package repositories by installing a package called
linux-headers :hp1.(or something similar to that):ehp1.. Compiling
these is as easy as finding the source code, extracting the archive,
and compiling like so:
:xmp.
$ cd libax25
$ ./configure --prefix=/usr
$ make -j8
# make install          <--- note: requires root, prefix with sudo if necessary
$ cd ..
$ cd ax25-apps
$ ./configure --prefix=/usr
$ make -j8
# make install
$ cd ..
$ cd ax25-tools
$ ./configure --prefix=/usr
$ make -j8
# make install
$ cd ..
$ cd node               <--- note: UROnode compiles the same way
$ ./configure  --prefix=/usr
$ make -j8
# make install
$ cd ..
# ln -s /usr/etc/ax25 /etc/ax25
:exmp.
:p.:hp1.Note: these instructions are not entirely exact; if you are not
passingly familiar with UNIX software installation and maintenance, I
recommend you just use the packages available in your Linux
distribution's package repository!:ehp1.
:h3.Configuring the Base Stack
:p.Linux has two ways of identifying AX.25 ports:
:ih2.Configuring Ports
:ul.
:li.The :hp1.port name:ehp1., a textual name that the AX.25 commands use
:li.The :hp1.interface name:ehp1., the name that the Linux kernel knows
the network device by
:fn.These devices always start with :pk.ax:epk. so, :pk.ax0:epk..
:efn.
:eul.
:p.To define an AX.25 port, edit :pk./etc/ax25/axports:epk., and, use
tabs for everything, not spaces:
:i3.AX.25
:xmp.
# name callsign speed paclen window description
#----- -------- ----- ------ ------ -----------
radio  WA4XYZ-1 1200  256    7      Real TNC
:exmp.
:p.Each field is as follows:
:ul.
:li.:pk.name:epk.: a descriptive name of the port (the :q.port name:eq.
described above)
:li.:pk.callsign:epk.: the unique callsign and SSID used for the port
:fn.For a terminal callsign (as in, your own personal terminal), if you
wish to use it, simply replace the SSID with zero. For
example: :pk.WA4XYZ-0:epk..
:efn.
:li.:pk.speed:epk.: the baud rate used on the interface's serial link
:fn.This is the :hp3.serial port baud rate:ehp3., not the RF modem baud
rate -- configuring that on a real TNC is likely something you will
need to read further down to learn about.
:efn.
:li.:pk.paclen:epk.: the packet length, 256 is standard for VHF/UHF
links
:li.:pk.window:epk.: the window size for the port (see the above notes
in the AX.25 section)
:li.:pk.description:epk.: a bit of text for your convinence
:eul.
:p.For :hp3.NET/ROM:ehp3. ports, you want to
edit :pk./etc/ax25/nrports:epk. (again, use tabs instead of spaces):
:i3.NET/ROM
:xmp.
# name callsign alias  paclen description
#----- -------- ------ ------ -----------
netrom WA4XYZ-7 EVIE1  236    NET/ROM Switch Port
:exmp.
:p.Likewise, the fields are as follows:
:ul.
:li.:pk.name:epk.: the port name
:li.:pk.callsign:epk.: the unique NET/ROM callsign for this port
:fn.Remember the footnote earlier? It is highly recommended that you do
not, under any circumstances, reuse a callsign/SSID pair used anywhere
else! Doing so breaks AX.25-noL3 connections (and sometimes also
NET/ROM connections)!
:efn.
:li.:pk.alias:epk.: the NET/ROM node alias, with a maximum length of
:hp3.6:ehp3. letters
:li.:pk.paclen:epk.: the packet length of the NET/ROM frames emitted
from this interface. :hp1.It is important that it is :hp3.20 bytes
less:ehp3. than the paclen of the AX.25 interface that will do the most
NET/ROM networking!:ehp1.
:li.:pk.description:epk.: text
:eul.
:p.You also need to define the port to the NET/ROM daemon (used to send
and receive routing frames), so edit :pk./etc/ax25/nrbroadcast:epk.:
:xmp.
# ax25_name min_obs def_qual worst_qual verbose
#---------- ------- -------- ---------- -------
radio       5       192      100        0
:exmp.
:p.The fields are as follows:
:ul.
:li.:pk.ax25_name:epk.: the corresponding AX.25 port that you want to
send and receive NET/ROM node broadcasts on
:li.:pk.min_obs:epk.: the minimum obsolecence value for the port (the
time before nodes are removed from the table)
:li.:pk.def_qual:epk.: the default quality announced when the node
includes itself in a routing table frame broadcast; the 192 to 200
range is fine
:li.:pk.worst_qual:epk.: the lowest quality number this node will
accept for other nodes listed in routing table frames
:li.:pk.verbose:epk.: set this to :hp2.1:ehp2. to allow this node to
announce :hp1.other NET/ROM nodes that it has heard -- this allows it
to function as a NET/ROM router (which is probably what you
want).:ehp1.
:eul.
:p.For :hp3.ROSE:ehp3., edit :pk./etc/ax25/rsports:epk.:
:i3.ROSE
:xmp.
# name address     description
#----- ----------  -----------
rose   1000100002  ROSE Switch Port
:exmp.
:p.The fields are as follows:
:ul.
:li.:pk.name:epk.: the switch port name
:li.:pk.address:epk.: the 10-digit X.121 address for this node as it
applies to all TNC ports
:li.:pk.description:epk.: text
:eul.
:h5.Starting Ports and Daemons
:p.After you have defined all of those ports, you now need to start
them. In this day and age, most Linux distributions do not
automatically load the Linux kernel modules for packet radio, so load
them yourself:
:ih2.Port configuration/daemons
:i3.Modules
:fn.You don't need to do this if you compiled your own monolithic
kernel with the modules baked in.
:efn.
:xmp.
# modprobe ax25
# modprobe netrom
# modprobe rose
:exmp.
:p.Once that has been done, you must now associate your TNC serial port
with your interface name (note that you will not need to set the baud
rate ahead of time) with :pk.kissattach:epk.:
:i3.kissattach
:xmp.
# kissattach /dev/ttyS0 radio
:exmp.
:p.If you are using a 6PACK TNC in lieu of a KISS TNC, you can
use :pk.spattach:epk. or the :pk.-6:epk. option of :pk.kissattach:epk.:
:xmp.
# kissattach -6 /dev/ttyS0 radio
# spattach /dev/ttyS0 radio
:exmp.
:p.If your TNC requires CRC (Direwolf does, but that will be covered in
a future section), enable it with this command:
:i3.kissparms
:xmp.
# kissparms -c 1 -p radio
:exmp.
:p.You now need to initialize your NET/ROM and ROSE ports:
:i3.nrattach
:i3.rsattach
:xmp.
# nrattach netrom
# rsattach rose
:exmp.
:p.In order for NET/ROM to work, you must start its daemon:
:i3.netromd
:xmp.
# netromd -i -t 10
:exmp.
:p.This transmits a routing table frame as soon as the program starts,
and then every 10 minutes after that.
:p.In order to build up a list of heard AX.25 stations (which can be
accessed with the :pk.mheard:epk. command later), run this daemon:
:xmp.
# mheardd
:exmp.
:p.:hp1.IPv4 over AX.25 will be discussed later.:ehp1.
:h5.Making Connections
:p.By the time you have completed the above commands, you should have
several interfaces added to the output of the :pk.ifconfig:epk.
command; invoke it and see for yourself:
:i2.ifconfig output
:fn.It is highly recommended that you install the
older:pk.net-tools:epk. package to have the :pk.ifconfig:epk. command
(among others), as the newer :pk.iproute2:epk. package is not very good
with packet radio.
:efn.
:xmp.
ax0: flags=67<UP,BROADCAST,RUNNING>  mtu 256
        ax25 WA4XYZ-1  txqueuelen 10  (AMPR AX.25)
        RX packets 919130  bytes 52973823 (50.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1791658  bytes 235437942 (224.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

nr0: flags=193<UP,RUNNING,NOARP>  mtu 255
        netrom WA4XYZ-7  txqueuelen 1000  (AMPR NET/ROM)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 264196  dropped 0 overruns 0  carrier 0  collisions 0

rose0: flags=193<UP,RUNNING,NOARP>  mtu 128
        rose 1000100002  txqueuelen 1000  (AMPR ROSE)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 264196  bytes 8454272 (8.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
:exmp.
:p.The callsigns can be seen on the ports, which is correct.
:p.Now, to open a connection to another node, do so with
the :pk.call:epk. command:
:ih2.Connection commands
:i3.AX.25
:xmp.
$ call radio n4abc-10
:exmp.
:p.This will start a fullscreen program that allows you to have a basic
textual conversation with another user's terminal, packet node, packet
BBS, or some other such thing -- it depends on how they have their node
configured and what it is listening for. To escape from a session,
enter a tilde, followed by a period, then strike Enter.
:fn.This is the same break key sequence that :pk.cu:epk.
and:pk.ssh:epk. use.
:efn.
:p.To make a NET/ROM connection, use a similar command:
:i3.NET/ROM
:xmp.
$ call netrom NYBBS
:exmp.
:p.To make a ROSE connection, use this:
:i3.ROSE
:xmp.
$ call rose AA4XY 1019542251
:exmp.
:h5.Listening and Beaconing
:p.Inevitably, you will want to discover adjacent NET/ROM nodes, listen
for AX.25 packets on the air, and send out beacons. To discover
adjacent NET/ROM nodes, run these two commands:
:ih2.Adjacent node discovery
:i3.NET/ROM nodes files
:xmp.
$ cat /proc/net/nr_nodes
$ cat /proc/net/nr_neigh
:exmp.
:p.If you want to listen for AX.25 packets on all interfaces, run this:
:i3.AX.25 listen command
:xmp.
# listen -c -a
:exmp.
:p.If you wish to view a list of stations you have heard so far, invoke
this (note: if you are tuned to the APRS frequency, you may get
hundreds of lines of output in a busy city):
:i3.AX.25 mheard command
:xmp.
$ mheard
:exmp.
:p.To send out a beacon announcing your presence, you can do so by
transmitting AX.25 UI-frames on a fixed timer (this transmits it on the
AX.25 port named :pk.radio:epk.):
:i3.AX.25 beacon command
:xmp.
$ beacon -t 10 radio "WA4XYZ Packet Radio Node"
:exmp.
:p.While connected, you can use :pk.netstat:epk. to get information
about active connections:
:i3.Multiprotocol netstat command
:xmp.
$ netstat --ax25
$ netstat --netrom
$ netstat --rose
:exmp.
:h3.Running TCP/IP on AX.25
:p.IP is heavily used on packet radio networks in places where advanced
packet adoption is high, so it is best to familiarize oneself with it.
Please note that the :hp1.IP addresses used here are non-global, not
unique on the internet, and you should probably go get some IP
addresses that start with 44 (which you can discover how to do after
some brief internet searches).:ehp1. Alas, let us construct a sample
example with LAN addresses.
:i2.TCP/IP
:p.Before going further, you should assign an IP address to your AX.25
interface:
:xmp.
# ifconfig ax0 192.168.44.100
:exmp.
:p.Note that :pk.ax0:epk. corresponds to the AX.25 port
named :pk.radio:epk., and you can make this association by observing the
output from the :pk.kissattach:epk. command.
:p.Rather than having to retroactively assign the IP address using
the :pk.ifconfig:epk. command, you can actually specify it as the last
argument to the :pk.kissattach:epk. command:
:xmp.
# kissattach /dev/ttyS0 radio 192.168.44.100
:exmp.
:p.At this point, you should be able to ping other hosts. It is
recommend that you send one ping at a time, though, as to not overwhelm
the frequency with packets every second:
:xmp.
$ ping -c 1 192.168.44.125
:exmp.
:p.When this ping command starts, it will emit ARP packets (just like
described in the IP intro section before); when the other node replies,
IP commuication can start.
:h5.Telnet Daemon
:p.Note that :hp3.you should not use encrypted protocols:ehp3., like
SSH, over AX.25; instead, use Telnet. To start a Telnet server and
permit remote login into your node (which is a :hp2.security
risk:ehp2.), continue reading.
:i3.Telnet
:p.To run a Telnet server on a Linux system with :pk.systemd:epk.
installed (which is most of them), install :pk.inetutils:epk. and run
this command:
:xmp.
# systemctl start telnet@.socket
:exmp.
:p.To run a Telnet server without the aid of systemd and instead use
the :pk.inetd:epk. program included in inetutils,
edit :pk./etc/inetd.conf:epk. and add in the following line:
:xmp.
telnet  stream  tcp   nowait  root  /usr/libexec/telnetd telnetd
telnet  stream  tcp6  nowait  root  /usr/libexec/telnetd telnetd
:exmp.
:p.At this point, invoke :pk.inetd:epk.:
:xmp.
# /usr/libexec/inetd
:exmp.
:p.:hp3.Note for Arch Linux users:ehp3.: if you are using Arch Linux
and running inetd to run a telnet server (in lieu of having systemd
control the socket), you need to replace
the :pk./usr/libexec/telnetd:epk. command invocation
in :pk.inetd.conf:epk. with the following:
:fn.For some reason, Arch Linux has a misplaced :pk.login:epk. program,
which is normally at :pk./sbin/login:epk.; this is a workaround to
allow telnetd to find the program.
:efn.
:xmp.
telnetd --exec-login=/usr/bin/login
:exmp.
:p.Alternatively, if you wish to use :pk.xinetd:epk. in lieu of
traditional inetd, edit :pk./etc/xinetd.conf:epk. and make sure this is
in here:
:fn.Note that :pk.xinetd:epk. also likes to check
the :pk./etc/xinetd.d/*:epk. files; this behavior can be altered by
editing :pk./etc/xinetd.conf:epk..
:efn.
:xmp.
service telnet {
    flags          = REUSE
    socket_type    = STREAM
    wait           = no
    user           = root
    server         = /usr/libexec/telnetd
    server_args    = --exec-login=/usr/bin/login
    log_on_failure += USERID
    disable        = no
}
:exmp.
:p.You can start xinetd by simply typing :pk.xinetd:epk. on the command
line. :hp1.Note that the Arch Linux fix has already been applied
here:ehp1..
:p.To make a Telnet connection, simply type something like this:
:xmp.
$ telnet 192.168.44.95
:exmp.
:p.Note that when the connection opens, you will see the remote
system's login prompt; you do not directly specify the username on the
command line.
:h5.Routing - Basic
:p.If you have two networks, say :pk.192.168.1.0/24:epk.
and:pk.192.168.44.0/24:epk. (the packet radio :q.LAN:eq. used in the
above example). If we wish to route between these two networks, two
things need to happen:
:i3.Routing
:ol.
:li.The routing node (our packet radio box) needs to have :hp2.IP
forwarding:ehp2. (i.e. routing) enabled
:li.All nodes on both networks need to be made aware that they can
route to the other network, and told how to get there
:eol.
:p.Examine the following diagram of the setup:
:fig width=column place=inline frame=none.
:artwork name=prrtng align=center.
:figcap.IP Routing Example
:efig.
:p.For PC 1 to reach PC 2, it must pass the packets through the routing
node. First, you must engage :hp2.IP forwarding:ehp2. (routing) on the
packet node:
:xmp.
# echo 1 > /proc/sys/net/ipv4/conf/all/forwarding
:exmp.
:p.Now, we have to populate routing tables. For this to be done, you
should first check the output from :pk.ifconfig:epk. on the packet node:
:xmp.
eth0: flags=4675<UP,BROADCAST,RUNNING,ALLMULTI,MULTICAST>  mtu 1500
        inet 192.168.1.5  netmask 255.255.255.0  broadcast 192.168.1.25
        ether aa:00:04:00:07:04  txqueuelen 1000  (Ethernet)
        RX packets 310597188  bytes 69593025608 (64.8 GiB)
        RX errors 0  dropped 4673197  overruns 0  frame 0
        TX packets 28622761  bytes 3296809890 (3.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ax0: flags=67<UP,BROADCAST,RUNNING>  mtu 256
        inet 192.168.44.100 netmask 255.255.255.0  broadcast 192.168.100.25
        ax25 WA4XYZ-1  txqueuelen 10  (AMPR AX.25)
        RX packets 919130  bytes 52973823 (50.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1791658  bytes 235437942 (224.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
:exmp.
:p.First, you need to tell :hp1.PC 1:ehp1. how to reach the packet
radio subnet (which, naturally, includes PC 2):
:xmp.
# route add -net 192.168.44.0/24 gw 192.168.1.5
:exmp.
:p.Remember, :pk.192.168.1.5:epk. is the Ethernet port on the packet
node!
:p.Likewise, you need to provide PC 2 with a routing table entry. This
consists of:
:xmp.
# route add -net 192.168.1.0/24 gw 192.168.44.100
:exmp.
:p.Now, you can execute ping commands (or anything else that uses
TCP/IP) and route between the two networks!
:h5.Routing - NAT
:p.If you wish to access the Internet via packet radio, you will need
to employ :hp2.NAT:ehp2. (Network Address Translation) routing.
:fn.:q.NAT:eq. used here is a colloquial term for what Cisco IOS calls
:hp2.NAT Overload:ehp2., some network engineers call :hp2.PAT:ehp2.
(Port Address Translation), and Windows calls :q.Internet Connection
Sharing.:eq. There is some debate as to which term is the true one, but
most people just call it :q.NAT.:eq.
:efn.
:p.Examine the following image to visualize the setup:
:fig width=column place=inline frame=none.
:artwork name=prnat align=center.
:figcap.IP NAT Example
:efig.
:p.Note that the IP addresses on the Ethernet subnet are no longer
shown -- they are no longer significant. Instead, what matters most is
the packet radio subnet. Now, enter the following commands on the
packet node to engage NAT routing, then I will explain what is going on
and why.
:xmp.
# iptables -t nat -a POSTROUTING -o eth0 -j MASQUERADE
# iptables -A FORWARD -i eth0 -o ax0 -m state --state RELATED,ESTABLISHED -j ACCEPT
# iptables -A FORWARD -i ax0 -o eth0 -j ACCEPT
:exmp.
:p.So, what's going on here? Well, whenever a host on the packet radio
subnet sends packets directed at the Internet, they will be
transmitting them to the packet routing node. It will then modify the
packet's source and destination address such that the packets look like
they are coming from the packet routing node PC; at the same time, the
router attached to the internet connection and Ethernet LAN does the
same thing.
:fn.This is a :q.double-NAT:eq. setup, since it does not require
entering any routes on that edge router.
:efn.
:h3.BPQ Ethernet Interface
:p.If you wish to run packet radio protocols in the gigabits range, the
BPQ Ethernet driver is your friend. The :pk.BPQETHER:epk. allows you to
encapsulate AX.25 frames (and, by extension, NET/ROM, ROSE, FlexNet,
IP, and such) over Ethernet (and, with some modification, Wi-Fi). This
provides a high-speed backbone and testing environment over Ethernet
LANs; non-Ethernet connections (T1 lines, synchronous serial links,
dialup links) will want to use an :hp1.AXIP or AXUDP:ehp1. tunnel
(which will be documented later).
:p.Before this can work, you must first :hp1.ensure that the Ethernet
device name:ehp1. has not been :q.renamed:eq. by something; in other
words, the network interface is named :pk.eth0:epk.. To do this, you
will need to pass a kernel parameter to the kernel; this can be done by
editing the GRUB/ELILO/Limine configuration. How to do this is
out-of-scope for this document, but you will need to pass the following
parameter: :pk.net.ifnames=0:epk.
:p.Once that change has been made, you will need to enter another port
into :pk./etc/ax25/axports:epk. like so:
:xmp.
# name callsign speed paclen window description
#----- -------- ----- ------ ------ -----------
radio  WA4XYZ-1 1200  256    7      Real TNC
bpq    WA4XYZ-5 19200 1024   7      BPQETHER Port
:exmp.
:p.There is no :pk.kissattach:epk. command to run here, as we can
:hp1.directly:ehp1. use the port after assigning the address to
the :pk.bpq0:epk. device:
:xmp.
# ifconfig bpq0 hw ax25 WA4XYZ-5 up
:exmp.
:p.When this has been done, the :pk.call:epk. command will
read:pk./etc/ax25/axports:epk. to resolve the port name to its
associated callsign -- after this is done, the connection opens.
:p.It is also possible to enable that port for NET/ROM, simply by
editing :pk./etc/ax25/nrbroadcast:epk.:
:xmp.
# ax25_name min_obs def_qual worst_qual verbose
#---------- ------- -------- ---------- -------
radio       5       192      100        0
bpq         5       192      100        0
:exmp.
:p.It is not necessary to update the ROSE configuration.
:h3.AXIP and AXUDP Tunnels
:p.Sometimes, it is necessary to bridge a packet radio network over the
Internet (or some other network link that speaks TCP/IP natively, and
does not natively support AX.25). In order to do this, one can
construct an :hp2.AX/IP:ehp2. tunnel -- this encapsulates the AX.25
frames into IPv4 packets. Likewise, to encapsulate TCP/IP into UDP
packets, one can create an :hp2.AX/UDP:ehp2. tunnel.
:fn.While AX/IP packets are technically smaller than AX/UDP packets, it
is generally not possible to :q.port-forward:eq. an AX/IP tunnel. This
resulted in the creation of :hp1.AX/UDP:ehp1., which can be
port-forwarded through a NAT router and firewall.
:efn.
:p.Before creating an AX/IP or AX/UDP tunnel, it is necessary to
understand the differences between AX/IP and AX/UDP in detail:
:ul.
:li.:hp3.AX/IP:ehp3.: uses IP protocol number 93
:li.:hp3.AX/UDP:ehp3.: uses UDP port 10093 :hp1.(or whichever you'd
like):ehp1.
:eul.
:p.The program that controls this tunnel is :pk.ax25ipd:epk., and it
has two operating modes (IP and UDP, as mentioned before). The
configuration file is located at :pk./etc/ax25/ax25ipd.conf:epk. --
start with a sample like this for :hp3.AX/IP:ehp3. mode:
:xmp.
# Socket type:
socket ip

# Use mode "tnc" or "digi"
mode tnc

# Beaconing
beacon after 600
btext YOUR BEACON TEXT HERE

# Use the PTY device created with socat
device /dev/ttyS30

# Line speed
speed 115200

# Log level, 0 to 4 (4 being the highest)
loglevel 0

# Broadcast ourselves?
broadcast QST NODES

# AX/IP connections go here
route NH6AB-2 12.34.56.78
:exmp.
:p.Likewise, for an :hp3.AX/UDP:ehp3. tunnel, start with this:
:xmp.
# Socket type:
socket udp

# Use mode "tnc" or "digi"
mode tnc

# Beaconing
beacon after 600
btext YOUR BEACON TEXT HERE

# Use the PTY device created with socat
device /dev/ttyS30

# Line speed
speed 115200

# Log level, 0 to 4 (4 being the highest)
loglevel 0

# Broadcast ourselves?
broadcast QST NODES

# AX/IP connections go here
route NH6AB-1 12.34.56.78 udp 10093
:exmp.
:p.Now, one may wish to emit broadcasts on a tunnel, and/or also
provide a default route on that interface. This can be done with
the :pk.b:epk. and :pk.d:epk. letters appended to the end of
the :pk.route:epk. lines. For example, to set a link as both
broadcast-capable (in other words, for to make NET/ROM work) and a
default route:
:xmp.
route NH6AB-1 12.34.56.78 udp 10093 b d
:exmp.
:p.As you might imagine, you must also enter this
into :pk./etc/ax25/axports:epk., like so:
:xmp.
# name callsign speed paclen window description
#----- -------- ----- ------ ------ -----------
radio  WA4XYZ-1 1200  256    7      Real TNC
bpq    WA4XYZ-5 19200 1024   7      BPQETHER Port
axip   WA4XYZ-3 19200 1024   7      AX/IP Port
:exmp.
:p.Likewise, edit :pk./etc/ax25/nrbroadcast:epk. to make the port
elegible for NET/ROM communication:
:xmp.
# ax25_name min_obs def_qual worst_qual verbose
#---------- ------- -------- ---------- -------
radio       5       192      100        0
bpq         5       192      100        0
axip        5       192      100        0
:exmp.
:p.Once you have defined the :pk.axports:epk. entry, you can now create
the :hp1.fake serial port:ehp1. used to allow :pk.ax25ipd:epk. to
communicate with the Linux kernel; the :pk.socat:epk. program does this:
:xmp.# socat -d -d PTY,link=/dev/ttyS30 PTY,link=/dev/ttyS31
:exmp.
:p.Now that :pk.socat:epk. is running, you can now start the daemon:
:xmp.# ax25ipd
:exmp.
:h3.Accepting Inbound Connections
:p.Inevitably, in the construction of a packet radio network, you will
find it necessary to allow some packet nodes to communicate with your
node. This can be in the form of two different methods:
:ol.
:li.:hp2.Keyboard-to-keyboard chat:ehp2., with inbound connections
answered by a program like :pk.ttylinkd.:epk.
:li.:hp2.A node:ehp2., a packet radio :q.shell:eq. that provides
BBS-esque functions
:eol.
:p.This guide will cover the setup of both listed options.
:h5.Configuring ax25d
:p.Before you can accept any inbound connections, you will need to
configure a program called :pk.ax25d.:epk.
:fn.This is from the :pk.ax25-apps:epk. package.
:efn.
Configuration is relatively simple, and is done by editing
the :pk./etc/ax25/ax25d.conf:epk. configuration file. If you are
familiar with configuring :pk.inetd:epk., :pk.ax25d:epk. is intended to
be somewhat analogous to that. Examine the following sample
configuration file:
:xmp.
&lbrk.WA4XYZ-1 VIA radio&rbrk.
NOCALL   * * * * * *  L
default  * * * * * *  - root  /usr/local/bin/node   node
#
&lbrk.WA4XYZ-5 VIA bpq&rbrk.
NOCALL   * * * * * *  L
default  * * * * * *  - root  /usr/local/bin/node   node
#
&lbrk.WA4XYZ-3 VIA axip&rbrk.
NOCALL   * * * * * *  L
default  * * * * * *  - root  /usr/local/bin/node   node
#
<netrom>
NOCALL   * * * * * *  L
default  * * * * * *  - root  /usr/local/bin/node   node
#
{* via rose}
NOCALL  * * * * * *  L
default * * * * * *  -  root  /usr/local/bin/node   node
:exmp.
:p.In the above example, the :pk.node:epk. program is being invoked --
this is an example of :hp1.case 2:ehp1. on the above list. Substituting
some other program name will result in that program being invoked.
:p.Note also that this program can accept AX.25, NET/ROM, and ROSE
connections.
:h5.Configuring the Node Program
:p.:pk.Node:epk. is a basic packet radio shell program, allowing
inbound users to run commands of their choosing. The base program is
not very feature-rich, so adding custom commands is highly recommended.
:p.The configuration file is located at :pk./etc/ax25/node.conf:epk. --
consult the following example:
:xmp keep=5.
# Idle timeout (seconds).
IdleTimeout     900

# Timeout when gatewaying (seconds).
ConnTimeout     14400

# Visible hostname. Will be shown at telnet login.
HostName        my.host.name

# Node ID.
NodeId          WA4XYZ-1

# ReConnect flag.
ReConnect       on

# "Local" network.
LocalNet        192.168.1.0/24

# Hidden ports.
#HiddenPorts    2

# Netrom port name. This port is used for outgoing netrom connects.
NrPort          netrom

# Logging level
LogLevel        3

# The escape character (CTRL-T)
# Use this to return to the node if a telnet connection or comma
d fails or hangs.
EscapeChar      &hat.T

# Resolve IP numbers to DNS addresses?
ResolveAddrs    on

# Node prompt.
NodePrompt      "WA4XYZ-1>"
:exmp.
:p.Before starting :pk.node:epk., you must also configure some account
permissions. To do that, edit :pk./etc/ax25/node.perms:epk.:
:xmp.
# user  type    port    passwd  perms
# Default permissions per connection type.
# 63 means they can connect out to any host through telnet.
*       ax25    *       *       63
*       netrom  *       *       63
*       local   *       *       63
*       ampr    *       *       63
*       inet    *       *       63
*       host    *       *       63
:exmp.

:lblbox.A Word on Node Security
:p.Giving :pk.inet:epk. users (i.e. users that connected to the node
through Telnet) access to telnet out to any other host on the Internet
is a risky move. A clever attacker (though unlikely) could use this as
a way to frame you for all manner of denial-of-service attacks!
:elblbox.
:p.Now that user permissions have been set, you now should edit the
MOTD (Message of The Day) file to configure the banner users will see
when connecting to the node. Edit :pk./etc/ax25/node.motd:epk.:
:xmp.
This is John Smith's Super Duper Cool Packet Radio Node!

Type ? for a list of commands. help <commandname> gives a
description of the named command.
:exmp.
:p.Assuming that you have configured the node correctly this far, the
only thing that is required to start the program is actually to
start :pk.ax25d:epk.:
:xmp.# ax25d
:exmp.
:p.After testing the node, you will likely want to define some custom
commands to make the node do something useful. The command syntax
consists of the following elements:
:ol.
:li.:pk.ExtCmd:epk.
:li.:hp1.<command name>:ehp1.
:li.:hp1.<command flags:ehp1.
:ul.
:li.1: run command through pipe
:li.2: reconnect prompt
:li.3: change user and then run through pipe
:eul.
:li.:hp1.<username that the program runs at, likely root>:ehp1.
:li.:hp1.<full path to Linux program invoked when the command is ran>:ehp1.
:li.:hp1.<name of the program, without the full path>:ehp1.
:li.:hp1.<command arguments>:ehp1.
:eol.
:p.For some cooked examples, see the below lines:
:xmp.
ExtCmd PS 1 nobody /bin/ps ps ax
ExtCmd PMS 3 root /usr/sbin/pms pms
:exmp.
:p.You can also :hp2.allow TCP Node connections:ehp2. by allowing users
to connect via the Telnet protocol. This is done by adding a line
to :pk./etc/inetd.conf:epk. just like before for the standard Telnet
daemon:
:xmp.
node    stream  tcp   nowait  root  /usr/bin/node node
node    stream  tcp6  nowait  root  /usr/bin/node node
:exmp.
:p.However, before restarting :pk.inetd:epk., you must also
update :pk./etc/services:epk.:
:fn.:pk.inetd:epk. uses port names resolved from the lines
of :pk./etc/services:epk. by convention, but you can also replace
:q.node:eq. in the first word of the line with a port number to achieve
the same effect.
:efn.
:xmp.node    3694/tcp
:exmp.
:p.If you are using :pk.xinetd:epk. instead, the configuration is
similar :hp1.(but does still require the :pk./etc/services:epk. fix):ehp1.
:xmp.
service node {
    flags          = REUSE
    socket_type    = STREAM
    wait           = no
    user           = root
    server         = /usr/bin/node
    log_on_failure += USERID
    disable        = no
}
:exmp.
:p.If you are using :pk.systemd:epk., you will need to edit two files:
:ol.
:li.:pk./usr/lib/systemd/system/node.socket:epk.
:xmp.
&lbrk.Unit&rbrk.
Description=Packet Radio Node

&lbrk.Socket&rbrk.
ListenStream=3694
Accept=true

&lbrk.Install&rbrk.
WantedBy=sockets.target
:exmp.
:li.:pk./usr/lib/systemd/system/node@.service:epk.
:xmp.
&lbrk.Unit&rbrk.
Description=Node Server
After=local-fs.target

&lbrk.Service&rbrk.
ExecStart=-/usr/sbin/uronode
StandardInput=socket
:exmp.
:eol.
:p.To apply these changes, invoke the following two commands:
:xmp.# systemctl daemon-reload
# systemctl start node.socket
:exmp.
:h5.Using UROnode Instead of Node
:p.For the most part, it is highly recommended that you use
:hp3.UROnode:ehp3. in lieu of traditional Node; not only does UROnode
have more functionality, but it is more secure.
:p.Compilation and installation is relatively simple; at the time of
this document's composition, UROnode can be found on GitHub after a
quick Internet search -- if this information no longer applies in the
future, it should surely still be findable!
:p.However, there are some things that should be noted.
By default, the October 2021 version of UROnode deposits all files into
the :pk./usr/local:epk. prefix -- you can fix this by running the
following commands to compile UROnode:
:xmp.
$ export ETC_DIR=/etc
$ export SBIN_DIR=/usr/sbin
$ export BIN_DIR=/usr/bin
$ export LIB_DIR=/usr/lib
$ export DATA_DIR=/usr/share
$ export MAN_DIR=/usr/share/man
$ export VAR_DIR=/var/lib/ax25
$ ./configure
<say no to interactive mode>
$ make -j4
# make install
:exmp.
:p.Now that UROnode has been installed, it must now be configured.
Since UROnode is a fork of Classic Node,
editing :pk./etc/ax25/uronode.conf:epk. is :hp1.relatively:ehp1. simple!
Note that you must also edit these files; check them off as you go:
:ol prefix=checkoff.
:li.:pk./etc/ax25/uronode.announce:epk. - announcements and notices
:li.:pk./etc/ax25/uronode.info:epk. - information file for users that
run the :pk.info:epk. command
:li.:pk./etc/ax25/uronode.motd:epk. - Message of the Day
:li.:pk./etc/ax25/uronode.perms:epk. - user permissions, :hp1.it is
critical you understand the security ramnifications here!:ehp1. :
:li.:pk./etc/ax25/uronode.routes:epk. - static pinned routes such that
users do not have to specify a port name on outbound connections :
:li.:pk./etc/ax25/uronode.users:epk. - callsigns, usernames, and
passwords to allow sysop users to drop into a Linux shell
:eol.
:p.Note that you can also :hp1.edit inetd, xinetd, or systemd's
configuration:ehp1. to allow :hp3.TCP connections:ehp3. to UROnode;
simply replace :pk.node:epk. with :pk.uronode:epk. and it should work!
:h3.APRS Digipeater/I-Gate
:p.If you wish to build an APRS digipeater or I-Gate   with the Linux
AX.25 stack, you have several options:
:ol.
:li.:pk.aprx:epk., a dedicated APRS daemon
:fn.:pk.aprx:epk. was forked from the earlier :pk.aprsd:epk. project.
:efn.
:li.:hp2.NOSaprs:ehp2., see the JNOS section below
:li.:hp2.XRouter APRS:ehp2., see the XRouter section below
:li.:hp2.Dire Wolf:ehp2. integrated APRS support, see the Dire Wolf
section below
:eol.
:p.Since this manual portion is present amongst the Linux AX.25 setup,
let us examine :pk.aprx:epk.!
:h5.Compilation
:p.Compiling :pk.aprx:epk. is relatively simple:
:xmp.
sh configure
make -j4
sudo mkdir /usr/local/aprx
sudo cp aprx /usr/local/aprx
sudo cp aprx.8 /usr/local/aprx
:exmp.
:h5.Bidirectional I-Gate Configuration
:p.APRS I-Gates that can transmit are a :hp1.rather rare
commodity:ehp1. in the world of amateur radio. As such, you should
probaby try to build one! Start
editing :pk./usr/local/aprx/aprx.conf:epk.:
:xmp keep=5.
mycall N0CALL-10
myloc lat 3639.50N lon 08724.50W

<aprsis>
    passcode 12345
    server noam.aprs2.net
    filter "m/25"
</aprsis>

<logging>
    pidfile /usr/local/aprx/aprx.pid
    rflog /usr/local/aprx/aprx-rf.log
    aprxlog /usr/local/aprx/aprx.log
    #dprslog /usr/local/aprx/dprs.log
    #erlangfile /usr/local/aprx/aprx.state
</logging>

<interface>
   ax25-device        $mycall
   tx-ok              true
   telem-to-is        true
</interface>

<beacon>
    beaconmode both
    cycle-size 20m
    beacon object "N0CALL-10" symbol "I#" lat "1234.50N" lon "01234.50W"
         comment "N0CALL TXing I-Gate and Digi"
    beacon raw ")123456zThis is aprx 2.9.1"
</beacon>

<telemetry>
    transmitter       $mycall
    via               TRACE1-1
    source            $mycall
</telemetry>

<digipeater>
    transmitter       $mycall

    <source>
       source         $mycall
       relay-type     digipeated
       viscous-delay  0
       ratelimit      60 120
       filter         t/poimqstunw
    </source>

    <source>
       source         APRSIS
       relay-type     third-party
       viscous-delay  0
       ratelimit      60 120
       via-path       WIDE1-1
       msg-path       WIDE1-1
       filter         t/poimqstunw
    </source>
</digipeater>
:exmp.
:h3.Configuring Dire Wolf
:p.If you don't have a real TNC (or don't want to use it), Dire Wolf is
a software TNC that works marvels; WB2OSZ did a wonderful job writing
it!
:i1.Dire Wolf
:h5.Compiling and Installation
:p.To install this wonderful program, follow the compilation directions
on the GitHub page. I :hp2.highly:ehp2. recommend that you compile it
yourself, to ensure that you are getting the latest version!
:p.Of interest is the support for :hp1.CM108 USB sound card
keying:ehp1. through its GPIO pins -- the CM108 is a cheap USB sound
card famously known for the availability of some extra GPIO pins on its
controller, and these can be used to key the radio.
:h5.Configuration
:p.Here is a basic config file for your viewing pleasure, usually
located at :pk./usr/local/share/doc/direwolf/conf/direwolf.conf:epk.
(unless you did not install Dire Wolf from the source code). Ensure the
configuration file contains the following elements:
:xmp.
ADEVICE soundhw:4.0
CHANNEL 0
MYCALL WA4XYZ-1
MODEM 1200
ARATE 48000
DTMF
TXDELAY 5
TXTAIL 5
FULLDUP OFF
PTT /dev/ttyUSB0 RTS
AGWPORT 8000
KISSPORT 8001
:exmp.
:p.Breaking down the config file, the configuration statements are as
follows:
:ul.
:li.:pk.ADEVICE:epk. - select audio device
:fn.Use :pk.arecord -l:epk. to list audio devices.
:efn.
:li.:pk.CHANNEL:epk. - select channel 0 (Dire Wolf can emulate a
multi-port TNC)
:li.:pk.MYCALL:epk. - set default callsign, overwritten by the KISS
callsign
:li.:pk.MODEM:epk. - set modem RF baud rate
:li.:pk.ARATE:epk. - set sound card sample rate
:fn.48000 is good for 1200 and 2400; use 96000 for 9600 and 19200 baud
:efn.
:li.:pk.DTMF:epk. - do DTMF decoding
:li.:pk.TXDELAY:epk. - transmit keyup delay (time from PTT activation
to stable, modulated RF emission)
:li.:pk.TXTAIL:epk. - transmit tail
:li.:pk.FULLDUP:epk. - select full-duplex operating mode
:li.:pk.PTT:epk. - PTT device selection:
:ul.
:li.:pk.<serial port device name> <signal pin>:epk.: use the selected
TTY device and RTS/DTR for keying
:li.:pk.GPIO <pin number>:epk.: use Raspberry Pi GPIO pins for keying
(prefix the number with a - for an active-low signal
:li.:pk.CM108:epk.: use GPIO pin 3 of the CM108 or CM119 USB sound chip
:eul.
:li.:pk.AGWPORT:epk. - AGW Packet Engine socket
:li.:pk.KISSPORT:epk. - KISS socket
:eul.
:p.After configuring Dire Wolf, start it with this command:
:xmp.# direwolf -p
:exmp.
:p.This will cause Dire Wolf to start, and it will create a KISS TNC
PTY device at :pk./tmp/kisstnc:epk. You can then run :pk.kissattach:epk.
on that port, provided that you enter the port
into :pk./etc/ax25/axports:epk. as follows:
:xmp.
# name callsign speed paclen window description
#----- -------- ----- ------ ------ -----------
radio  WA4XYZ-1 1200  256    7      Real TNC
radio2 WA4XYZ-3 1200  256    7      Dire Wolf
:exmp.
:p.Don't forget to enter it into :pk./etc/ax25/nrports:epk. and start
the rest of the packet stack.
:p.:hp2.Important!:ehp2. You need to run :pk.kissparms -c 1 -p <Dire
Wolf port name>:epk. :hp1.before:ehp1. trying to make any connections
with any of the user programs!
:h3.List of Linux Packet Programs
:p.The following table provides a list of programs, their associated
package, and a brief description:
:table cols='* * *'.
:tcap.Linux Packet Programs
:row.
:c.:hp2.Command:ehp2.
:c.:hp2.Package:ehp2.
:c.:hp2.Description:ehp2.
:row.
:c.mheard
:c.ax25-tools
:c.List AX.25 callsigns recently heard over some given timeframe
:row.
:c.ax25d
:c.ax25-tools
:c.Listen for and accept AX.25, NET/ROM, and ROSE connections
:row.
:c.axctl
:c.ax25-tools
:c.Configure or kill active AX.25 connections
:row.
:c.axparms
:c.ax25-tools
:c.Manipulate the kernel UID/callsign mapping table
:row.
:c.axspawn
:c.ax25-tools
:c.Provide automatic AX.25 login and possibly create accounts
:row.
:c.beacon
:c.ax25-tools
:c.Periodically broadcast a beacon on a port
:row.
:c.bpqparms
:c.ax25-tools
:c.Change what MAC address the BPQETHER driver uses
:row.
:c.mheardd
:c.ax25-tools
:c.Listen for AX.25 stations and populate the mheard list
:row.
:c.rxecho
:c.ax25-tools
:c.:q.Dummy routing:eq./bridging between two AX.25 ports
:row.
:c.sethdlc
:c.ax25-tools
:c.Alter settings for an HDLC-based port
:row.
:c.smmixer
:c.ax25-tools
:c.Change volume levels for the in-kernel soundcard softmodem
:row.
:c.smdiag
:c.ax25-tools
:c.Display status and modulation diagram for soundcard modem driver
:row.
:c.kissattach
:c.ax25-tools
:c.Attach serial KISS or 6PACK interface
:row.
:c.kissnetd
:c.ax25-tools
:c.Allocate several PTYs and emulate a KISS network (or use multiple
serial ports)
:row.
:c.kissparms
:c.ax25-tools
:c.Alter KISS TNC settings (TX delay/tail, CRC, etc)
:row.
:c.net2kiss
:c.ax25-tools
:c.Directly output AX.25 packets from an interface on a serial port
:row.
:c.mkiss
:c.ax25-tools
:c.Operate a multi-port KISS TNC with one serial port
:row.
:c.nodesave
:c.ax25-tools
:c.Write NET/ROM routing table to a shell script for running later
:row.
:c.nrattach
:c.ax25-tools
:c.Attach NET/ROM port
:row.
:c.nrparms
:c.ax25-tools
:c.Configure NET/ROM nodes, aliases, and routes
:row.
:c.nrsdrv
:c.ax25-tools
:c.Use a NET/ROM Serial Protocol TNC with kissattach (via a PTY)
:row.
:c.netromd
:c.ax25-tools
:c.Send and receive NET/ROM routing table broadcasts
:row.
:c.rsattach
:c.ax25-tools
:c.Attach ROSE port
:row.
:c.rsuplnk
:c.ax25-tools
:c.Accept AX.25 connections and dump packets into a ROSE net
:row.
:c.rsdwnlnk
:c.ax25-tools
:c.Accept ROSE packets and dump into an AX.25 host
:row.
:c.rsparms
:c.ax25-tools
:c.Configure ROSE nodes and routes
:row.
:c.ttylinkd
:c.ax25-tools
:c.TTYLink daemon (AX.25, NET/ROM, ROSE, TCP)
:row.
:c.rip98d
:c.ax25-tools
:c.Send and receive RIP98 routing messages for IP networks
:row.
:c.ax25_call
:c.ax25-tools
:c.Make AX.25 conection
:row.
:c.netrom_call
:c.ax25-tools
:c.Make NET/ROM conection
:row.
:c.rose_call
:c.ax25-tools
:c.Make ROSE conection
:row.
:c.tcp_call
:c.ax25-tools
:c.Make TCP5 conection
:row.
:c.yamcfg
:c.ax25-tools
:c.Configure YAM interface
:row.
:c.dmascc_cfg
:c.ax25-tools
:c.Configure PI2, PackeTwin, and other DMASCC devices
:row.
:c.ax25ipd
:c.ax25-apps
:c.AX/IP and AX/UDP tunnel manager
:row.
:c.a25rtd
:c.ax25-apps
:c.AX.25 routing daemon
:row.
:c.ax25rtctl
:c.ax25-apps
:c.ax25rtd control program
:row.
:c.call
:c.ax25-apps
:c.Make AX.25, NET/ROM, or ROSE connections
:row.
:c.listen
:c.ax25-apps
:c.Monitor AX.25, NET/ROM, ROSE, and IP traffic on an AX.25 port
:row.
:c.soundmodem
:c.soundmodem
:c.Soundcard AX.25 modem driver program (SoundBlaster)
:row.
:c.soundmodemconfig
:c.soundmodem
:c.Configure soundcard modem driver
:row.
:c.baycom
:c.baycom
:c.Drive Baycom modem by manipulating the 8250 UART chip
:row.
:c.aprsd
:c.aprsd
:c.Original APRS daemon
:row.
:c.aprspass
:c.aprsd
:c.Compute APRS-IS access passcode
:row.
:c.aprsdigi
:c.aprsdigi
:c.Original APRS digipeater
:row.
:c.aprsmon
:c.aprsdigi
:c.aprsdigi monitor tool
:row.
:c.aprx
:c.aprx
:c.Improved APRS digipeater and i-gate
:row.
:c.aprx-mon
:c.aprx
:c.aprx monitor tool
:row.
:c.node
:c.ax25-apps
:c.AX.25, NET/ROM, ROSE, and TCP packet radio shell program
:row.
:c.uronode
:c.uronode
:c.Improved version of classic node
:row.
:c.linpac
:c.linpac
:c.Advanced packet radio shell program
:etable.
:h1.JNOS
:p.NOTE: before proceeding with this, install all of the :hp5.optional
programs:ehp5. listed at the beginning of the Linux AX.25 section!
:i1.JNOS
:h3.Introduction
:p.KA9Q NOS was a packet radio stack for MS-DOS PCs that saw tremendous
popularity in the late 80s and early 90s; its creator, Phil Karn,
included the :hp1.source code:ehp1. with every release. Since NOS was
open-source, many amateurs ported it and made it available on a number
of operating systems:
:ul.
:li.Windows 3.x
:li.Windows NT
:li.OS/2 (PM-NOS)
:li.UNIX (WAMPES)
:li.AmigaOS (AmigaNOS, AmigaTCP)
:fn.Not to be confused with :hp1.AmiTCP:ehp1., which later evolved into
:hp1.GENESiS:ehp1. -- this is unrelated to the later/more common
:hp1.Roadshow:ehp1. stack
:efn.
:li.:hp1.and many, many more:ehp1.
:eul.
:p.Alas, NET/NOS (as it became to be known) quickly found itself
obsolete and many forks emerged. One of those were :hp2.TNOS:ehp2., the
Tampa Network Operating System. Running up until about 2004 or so, TNOS
introduced many new features and was ported to run on the new and
popular :hp1.Linux:ehp1. system, something I am sure you are passingly
familiar with. In October 2004, VE4KLM (Maiko Langelaar) combined the
JNOS 1.11F release (itself an updated NET/NOS port that continued to
run on MS-DOS, maintained by N5KNX, James Dugal, until 1996) with the
portability improvements of TNOS 2.40. JNOS 2 was Linux-native, could
work on other OSes (including BSD), and even gained IPv6 support!
:p.Despite there being many NOSes, this guide will cover configuring
JNOS 2 first. Before beginning, it is helpful to familiarize oneself
with the features this stack has:
:ul.
:li.Link-layer protocols: AX.25, Ethernet (disused), PPP, SLIP
:li.Network-layer protocols: NET/ROM, IPv4, IPv6
:li.Tunnel protocols: AXIP, AXUDP, IPENCAP (protocol 94), IPIP
(protocol 4)
:li.Applications: SMTP, POP3, BBS, FTP, HTTP, DNS server/client, user
database manager
:eul.
:p.
:h3.Compilation
:p.To actually compile JNOS, you need to retrieve the source code from
VE4KLM's website:
:fn.This is true as of 2026/01/20, when this was written.
:efn.

:i2.rsync download
:xmp.$ rsync -a www.langelaar.net&colon.&colon.official jnos
:exmp.
:p.You now need to configure the program:
:xmp.$ cd jnos
$ ./configure
$ make -j8
# mkdir /jnos
# cp -rv jnos jnospwmgr usage /jnos
:exmp.
:p.With that last command being ran, JNOS has been installed. You may
now proceed to configuration.
:h5.Advanced Configuration
:p.If you wish to manually maniplate the configuration file for the
features baked into JNOS, you may edit :pk.config.h:epk. in the JNOS
source directory. To turn on a config option, ensure :pk.#define:epk.
is present on the line; :pk.#undef:epk. disables an option. For example:
:i2.config.h entries
:xmp.#define NETROMSESSION
:exmp.
:p.This option is :hp1.enabled.:ehp1.
:h3.Configuration
:p.JNOS is configured by editing the :pk.autoexec.nos:epk. file present
in the JNOS program working directory; in this example, it will be
present at :pk./jnos/autoexec.nos:epk.. This file contains a series of
commands that are ran at startup, so any JNOS command that you type in
during JNOS's execution may be ran at startup (provided that you key it
in).
:fn.This scheme is reminscent of :pk.autoexec.bat:epk. on MS-DOS systems
:efn.

:i2.autoexec.nos
:p.Rather than providing a long and linear :pk.autoexec.nos:epk. file
as a sample, I find it better to slowly start creating one (and, don't
worry, the entire example will be available at the end).
:p.First, we should enable logging and set the escape key to something
easy:
:i2.escape (break) key
:xmp.log on
escape !
:exmp.
:p.We can optimize our TCP settings for a radio link, since we will be
running TCP/IP over AX.25:
:i2.TCP tuning
:xmp.
tcp mss 216
tcp window 4096
tcp timert linear
tcp irtt 5000
tcp maxw 9000
tcp bl 2
tcp ret 12
tcp syn on
tcp maxwait 30000
tcp retries 5
:exmp.
:p.We likely want to respond to pings:
:i2.ICMP options
:xmp.
icmp echo on
icmp trace 2
:exmp.
:p.Set the IP TTL to something decent:
:xmp.
ip ttl 225
ip rt 4
:exmp.
:p.Set our default IP address, DNS hostname, and callsign:
:i2.IP address and hostname
:xmp.
ip address 203.0.113.25
hostname jnos2.wa4xyz.radio
ax25 mycall WA4XYZ-3
:exmp.
:p.Linux allows us to attach a :q.tunnel:eq. device, allowing JNOS to
talk directly to the Linux kernel's TCP/IP stack :hp1.without:ehp1. the
aid of a simulated KISS tunnel:
:fn.This :q.simulated tunnel:eq. is the same as a :pk.socat:epk. fake
PTY seen on the Linux :pk.ax25ipd:epk.example.
:efn.

:i2.Tunnel device
:xmp.
attach tun tun0 1500 0
ifconfig tun0 ipaddress 192.168.48.2
ifconfig tun0 netmask 0xffffff00
ifconfig tun0 mtu 1500
# Give it a chance to come up
pause 1
# This runs a command on the host to initialize the tunnel device:
shell ifconfig tun0 192.168.48.1 pointopoint 192.168.48.2 mtu 1500 u
:exmp.
:p.If you are using a KISS TNC on the first COM port, :pk.ttyS0:epk.:
:i2.KISS TNC device
:xmp.
attach asy ttyS0 - ax25 ax0 4096 256 9600
ifconfig ax0 description "KISS TNC"
ifconfig ax0 ax25 irtt 1000
ifconfig ax0 ax25 t2 100
ifconfig ax0 ax25 t3 60000
ifconfig ax0 ax25 t4 120
ifconfig ax0 ax25 paclen 256
ifconfig ax0 ax25 window 16384
ifconfig ax0 ax25 maxframe 4
ifconfig ax0 ax25 maxwait 10000
ifconfig ax0 mtu 256
ifconfig ax0 ipaddr 203.0.113.25
ifconfig ax0 netmask 0xffffff00
ifconfig ax0 broadcast 203.0.113.255
mode ax0 datagram
:exmp.
:p.If you wish to have a cross-connection to the Linux AX.25 stack,
enter these commands (note that the IP address on this subnet
is :pk.198.18.44.0/24:epk.):
:xmp.
attach asy ttyS32 - ax25 ax1 4096 256 9600
ifconfig ax1 description "KISS PTY emulation"
ifconfig ax1 ax25 irtt 1000
ifconfig ax1 ax25 t2 100
ifconfig ax1 ax25 t3 60000
ifconfig ax1 ax25 t4 120
ifconfig ax1 ax25 paclen 256
ifconfig ax1 ax25 window 16384
ifconfig ax1 ax25 maxframe 4
ifconfig ax1 ax25 maxwait 10000
ifconfig ax1 mtu 256
ifconfig ax1 ipaddr 198.18.44.5
ifconfig ax1 netmask 0xffffff00
ifconfig ax1 broadcast 198.18.44.255
mode ax1 datagram
:exmp.
:p.Since we are doing TCP/IP over AX.25, we need to add two routes: one
for our tunnel device and one for our TNC:
:fn.Note that the example shown here assumes that your edge router
knows that it can access the :pk.192.168.48.0/24:epk. network through
your Linux's machine; in reality, you may struggle to do this or have
to resort to setting up NAT. If this is the case, see the earlier NAT
example under the :hp1.Linux AX.25:ehp1. example.
:efn.

:i2.route command
:xmp.
route add 203.0.113.0/24 ax0 direct 5
route add 198.18.44.0/24 ax1 direct 5
# The following IP address is our router's IP:
route add default tun0 192.168.1.1
:exmp.
:p.Configure a DNS server:
:i2.DNS client
:xmp.
domain addserver 192.168.1.110
:exmp.
:p.Set up some AX.25 beacons:
:i2.AX.25 beaconing
:xmp.
ax25 bctext "JNOS/Linux"
ax25 bcinterval 600
ax25 bcport ax0
ax25 bcport ax1
:exmp.
:p.Turn on ARP polling, such that your machine can network with other
IP/AX.25 hosts:
:i2.ARP polling
:xmp.
# ARP functions:
arp eaves tun0 on
arp eaves ax0 onn
arp eaves ax1 onn
arp eaves encap on
# ARP polling:
arp poll tun0 on
arp poll ax0 onn
arp poll ax1 onn
arp poll encap on
arp maxq 10
:exmp.
:p.Set some AX.25 parameters to increase performance:
:i2.AX.25 tuning
:xmp.
ax25 maxf 2
ax25 timert linear
ax25 version 2
ax25 win 2048
ax25 pacl 128
ax25 bcinterval 600
ax25 ret 12
ax25 irtt 2500
ax25 maxw 7000
ax25 blimit 3
ax25 hsize 50
:exmp.
:p.Turn on the :q.heard list:eq. list to keep track of stations:
:i2.AX.25 heard list
:xmp.
ax25 heard ax0
ax25 hport ax0 on
ax25 heard ax1
ax25 hport ax1 on
:exmp.
:p.Start configuring NET/ROM, and make a provision for running TCP over
NET/ROM:
:i2.NET/ROM tuning
:xmp.
attach netrom
netrom alias JNOSXX
netrom call WA4XYZ-8
netrom interface ax0 192 143
netrom interface ax1 192 143
ifconfig netrom tcp blimit 3
ifconfig netrom tcp irtt 300000
ifconfig netrom tcp maxwait 900000
ifconfig netrom tcp mss 216
ifconfig netrom tcp retries 25
ifconfig netrom tcp timertype linear
ifconfig netrom tcp window 432
netrom nodefilter mode none
netrom acktime 100
netrom choketime 60000
netrom derate on
netrom hidden on                # show nodes that start with #
netrom irtt 8000
netrom minquality 143
netrom nodetimer 60             # broadcast interval
netrom obsotimer 1200           # how long nodes last for
netrom promiscuous on
netrom qlimit 2048
netrom retries 5
netrom timertype linear
netrom ttl 18
netrom g8bpq on                 # BPQ Packet Engine extensions
netrom bcpoll ax0               # this is our TNC
netrom bcnodes ax0
netrom bcpoll ax1               # this is our Linux pipe
netrom bcnodes ax1
ifconfig netrom ipaddress 203.0.113.26 netmask 0xfffffffc
route add 203.0.113.24/30       # 203.0.113.25-26 are for NET/ROM IP
:exmp.
:p.JNOS has an HTTP server:
:ih2.Servers
:i3.HTTP
:xmp.
start http 80 /wwwroot          # /jnos/wwwroot is the real path
http absinclude on
http maxcli 15
http multihomed on
http simult 15
http tdisc 180
:exmp.
:p.Configure the FTP server:
:i3.FTP
:xmp.
ftptdisc 300
ftype B
ftpclzw on
ftpslzw on
ftpmaxservers 15
:exmp.
:p.Configure the SMTP server to forward messages to and from the BBS
and the Internet:
:fn.I am only assuming that you are familiar with the inner workings of
SMTP; the :pk.smtp gateway:epk. command will allow you to direct
messages to an SMTP proxy that could rewrite the address -- see the
Appendix for that.
:efn.

:i3.SMTP
:xmp.
smtp quiet on
smtp maxclients 25
smtp maxservers 25
smtp batch on
smtp t4 300
smtp tdisc 920
smtp timer 920
smtp use on
# smtp gateway 192.168.1.145
:exmp.
:p.Start all of the server programs:
:xmp.
start ax25
start telnet
start smtp
start finger
start pop
start ttylink
start netrom
start ftp
start convers
start forward
:exmp.
:p.If you need an AX/IP tunnel:
:ih2.Tunnels
:i3.AX/IP
:xmp.
attach axip axi0 256 192.168.44.1
:exmp.
:p.If you need an AX/UDP tunnel (in this case, the local and remote
port are both 10093):
:i3.AX/UDP
:xmp.
attach axudp axu0 256 192.168.44.1 N4XYZ-3 10093 10093
:exmp.
:p.:hp3.Note:ehp3. that you :hp5.must:ehp5. have equivalent commands
for all of the interface-dependent commands above for AX/IP and AX/UDP
tunnels!
:h5.Managing Users
:p.Before you can run JNOS, you should create some users. Remember,
JNOS's primary job is to be a mailbox and BBS system, so you
:hp1.really should:ehp1. do this. Users are stored in
the :pk.ftpusers:epk. file, which is located at :pk./jnos/ftpusers:epk.
in our example. Here is a sample file:
:i2.ftpusers file
:xmp.
N4HAM pass123 /jnos/public 0x437F
univperm * /jnos/public 0x405F
:exmp.
:p.The :pk.univperm:epk. line is the fall-through for users who are not
registered and who connected to your node. The :q.permission value:eq.
(the hex value on the end of the line) is computed by ORing the
following values:
:fn.If you are unfamiliar with how to do this, the Calculator program
on most graphical OSes (as well as most graphing calculators) will
permit you to change it into :hp1.programmer mode:ehp1. (that's what
Windows Calculator calls it, OS X Calculator has the same mode
accessible via command-3) and perform arithmetic on hex values.
:efn.

:i2.univperm (in ftpusers)
:table cols='* * * *'.
:tcap.JNOS User Permission Bits
:row.
:c.:hp2.Name:ehp2.
:c.:hp2.Decimal Value:ehp2.
:c.:hp2.Hex Value:ehp2.
:c.:hp2.Comments:ehp2.
:row.
:c.FTP_READ
:c.1
:c.0x1
:c.Read file
:row.
:c.FTP_CREATE
:c.2
:c.0x2
:c.Create new files
:row.
:c.FTP_WRITE
:c.4
:c.0x4
:c.Overwrite or delete existing files
:row.
:c.AX25_CMD
:c.8
:c.0x8
:c.AX.25 gateway (outbound connect) allowed
:row.
:c.TELNET_CMD
:c.16
:c.0x10
:c.Telnet gateway allowed
:row.
:c.NETROM_CMD
:c.32
:c.0x20
:c.NET/ROM gatrway allowed
:row.
:c.SYSOP_CMD
:c.64
:c.0x40
:c.User can try to enter sysop mode
:row.
:c.EXCLUDED_CMD
:c.128
:c.0x80
:c.Ban user from BBS
:row.
:c.PPP_ACCESS_PRIV
:c.256
:c.0x100
:c.Allow user to connect via PPP
:row.
:c.PPP_PWD_LOOKUP
:c.512
:c.0x200
:c.PPP peer ID/password lookup
:row.
:c.NO_SENDCMD
:c.1024
:c.0x400
:c.Disallow :q.send:eq. command
:row.
:c.NO_READCMD
:c.2048
:c.0x800
:c.Disallow :q.read:eq. command
:row.
:c.NO_3PARTY
:c.4096
:c.0x1000
:c.Disallow third-party mail from other BBSes
:row.
:c.IS_BBS
:c.8192
:c.0x2000
:c.This callsign is a remote BBS
:row.
:c.IS_EXPERT
:c.16384
:c.0x4000
:c.Allow access to :q.expert:eq. shell
:row.
:c.NO_CONVERS
:c.32768
:c.0x8000
:c.Disallow access to the :q.convers:eq. chat server
:row.
:c.NO_ESCAPE
:c.65536
:c.0x10000
:c.Disable the escape character
:row.
:c.NO_LISTS
:c.131072
:c.0x20000
:c.No lists displayed from the mailbox
:row.
:c.NO_LINKEDTO
:c.262144
:c.0x40000
:c.Disable the :q.*** linked to:eq. text
:row.
:c.NO_LASTREAD
:c.524288
:c.0x80000
:c.Ignore the lastread file in the shared accounts directory
:row.
:c.NO_FBBCMP
:c.1048576
:c.0x100000
:c.No F4FBB BBS compression
:row.
:c.XG_ALLOWED
:c.20971572
:c.0x200000
:c.Allow the :q.xg:eq. (dynamic IP route) command
:etable.
:p.Provided that you tailored this file accordingly, you should now
have a working JNOS system. It is recommended that you run JNOS in
a:pk.screen:epk. session:
:xmp. a
# socat -d -d PTY,link=/dev/ttyS34 PTY,link=/dev/ttyS35 &
# screen -S jnos
# cd /jnos
# ./jnos
<press control-A then D>
:exmp.
:p.Now that JNOS is up, configure the Linux AX.25 stack (as seen
before) to have a port entry for the JNOS pipe. Start by adding it
to:pk./etc/ax25/axports:epk.:
:xmp.
# name callsign speed paclen window description
#----- -------- ----- ------ ------ -----------
radio  WA4XYZ-1 1200  256    7      Real TNC
jnos   WA4XYZ-5 19200 1024   7      JNOS/Linux
:exmp.
:p.Ensure it is also in :pk./etc/ax25/nrbroadcast:epk.:
:xmp.
# ax25_name min_obs def_qual worst_qual verbose
#---------- ------- -------- ---------- -------
radio       5       192      100        0
jnos        5       192      100        0
:exmp.
:p.Now, connect Linux's stack to the :hp1.other side:ehp1. of the fake
serial cable provided by :pk.socat:epk.:
:xmp.# kissattach /dev/ttyS35 jnos 198.18.44.10
:exmp.
:p.Now, everything is set. JNOS is running, and Linux can communicate
with it by using IP on the :pk.tun0:epk. interface, or by using AX.25
on the :pk.jnos:epk. port (which would be :pk.ax0:epk. if you have no
other :pk.kissattach:epk.'d TNCs active).
:p.In this canned example, JNOS can be reached in either of the
following examples from its Linux host:
:xmp.$ call jnos WA4XYZ-3 (AX.25-noL3)
$ call netrom JNOSXX (NET/ROM aka AX.25-L4)
$ telnet 192.168.48.2 (tun0 interface)
$ telnet 198.18.44.5 (TCP/IP over AX.25)
:exmp.
:h3.Using JNOS
:p.Before running any JNOS commands, invoke :pk.ifconfig:epk. to see
the interfaces. You should see at least four ports:
:ih2.JNOS commands
:i3.ifconfig
:xmp.
ax0      IP addr 203.0.113.25 MTU 256 Link encap AX25
         Link addr WA4XYZ-3  BBS WA4XYZ-3  Paclen 256   Irtt 5000
         BCText: JNOS/Linux
         flags 0xfb2 trace 0x0 netmask 0xffffff00 broadcast 203.0.113.255
         sent: ip 0 tot 1092405 idle 0:00:00:19
         recv: ip 1437715 tot 1751311 idle 0:00:00:07
ax1      IP addr 198.18.44.5 MTU 256 Link encap AX25
         Link addr WA4XYZ-3  BBS WA4XYZ-3  Paclen 256   Irtt 5000
         BCText: JNOS/Linux
         flags 0xfb2 trace 0x0 netmask 0xffffff00 broadcast 198.18.44.255
         sent: ip 0 tot 1092405 idle 0:00:00:19
         recv: ip 1437715 tot 1751311 idle 0:00:00:07
tun0     IP addr 192.168.48.2 MTU 1500 Link encap TUN
         flags 0x300 trace 0x0 netmask 0xffffff00 broadcast 0.0.0.0
         sent: ip 3023005 tot 3023005 idle 0:00:00:16
         recv: ip 3137736 tot 3137736 idle 0:00:00:13
encap    IP addr 0.0.0.0 MTU 65535 Link encap None
         flags 0x300 trace 0x0 netmask 0xffffffff broadcast 255.255.255.255
         sent: ip 0 tot 0 idle 243:23:38:35
         recv: ip 0 tot 0 idle 243:23:38:35
:exmp.
:p.To make an AX.25 connection, use the following command:
:i3.connect (AX.25)
:xmp.jnos> connect ax0 N4ABC-7
:exmp.
:p.List NET/ROM nodes with:
:i3.connect (NET/ROM)
:xmp.jnos> netrom route nodes
jnos> netrom neigh
:exmp.
:p.To make a NET/ROM connection:
:xmp.jnos> netrom connect MYNODE
:exmp.
:p.You can make a Telnet connection:
:xmp.jnos> telnet 192.168.1.1
:exmp.
:h5.Using the JNOS BBS
:p.One of the most standout features of the JNOS package (and, by
extension, its adjacents like those listed at the start of this
section) is its wonderful :hp2.BBS.:ehp2. Whereas Linux requires the
F6FBB BBS package, JNOS has one built in!
:i2.JNOS BBS
:p.Users can access the BBS in one of two ways:
:ol.
:li.Invoke the :pk.bbs:epk. command at the :pk.jnos>:epk. prompt
:li.Telnet, AX.25-connect, or NET/ROM-connect to the JNOS node
:eol.
:p.When you connect, via Telnet in this example, you will be greeted
with a logon prompt. By specifying any callsign, you can log in and
register:
:fn.To disallow anonymous/unregistered users access to the BBS (and
therefore node in general), you can specify that for
the:pk.univperm:epk. user by setting the :pk.EXCLUDED_CMD:epk.
permission bit.
:efn.
:xmp.
% telnet 192.168.48.2
Trying 192.168.48.2...
Connected to 192.168.48.2.
Escape character is '&hat.&rbrk.'.

JNOS (jnos2.wa4xyz.radio)

login: w4abc
Password:
&lbrk.JNOS-2.0p-B1FHIM$&rbrk.
You have 0 messages.

Please type 'REGISTER' at the > prompt.
Area: w4abc (#0) >
:exmp.
:p.At this point, you can register as an anonymous user:
:i3.User registration
:xmp.
Area: w4abc (#0) >
register
Your current settings are:
Name = Someone
AX.25 Homebbs Address  = Unknown
Internet Email Address = Unknown

First name.(CR=cancel)
Somebody
AX.25 homebbs.(CR=cancel all)
WA4XYZ-3
Internet Email.(CR=ignore)
w4abc@arrl.net
Area: w4abc (#0) >
:exmp.
:p.If you check the :pk.ftpusers:epk. file, you will note that the user
is :hp1.not:ehp1. there; instead, the user can be found at the bottom
of :pk./jnos/spool/users.dat:epk.:
:i3.users.dat file
:xmp.w4abc 1769026100 M20   A X     -nSomebody -hWA4XYZ-3 -ew4abc@arrl.net
:exmp.
:p.To give the user persistent, registered access, you must key them
into :pk.ftpusers.:epk.
:p.To :hp2.send a message:ehp2., use the :pk.S:epk. command:
:xmp.
Area: w4abc (#0) >
s w4abc
Subject:
test email
Enter message.  End with /EX or &hat.Z in first column (&hat.A aborts):
this is a test message to demonstrate JNOS's BBS.
/EX
Send(N=no)? y
Msg queued
Area: w4abc (#0) >
:exmp.
:p.To :hp2.read a message:ehp2., you only need to :hp1.press the Enter
key&colon.:ehp1.
:xmp.
Area: w4abc (#0) >

Message #1
Date: Wed, 21 Jan 2026 14:12:14 CST
From: w4abc@jnos2.wa4xyz.radio
To: w4abc
Subject: test email

this is a test message to demonstrate JNOS's BBS.

You have new mail. Please Kill when read!
Area: w4abc (#1) >
:exmp.
:p.Now, the BBS tells you need to :hp2.kill:ehp2. the message when you
receive it; this is the shorthand for :hp2.deleting a message&colon.:ehp2.
:xmp.
k
Msg 1 Killed.
Area: w4abc (#1) >
:exmp.
:p.Now, the :pk.#1:epk. in the parathenses to the right of your
callsign is the :hp2.message number.:ehp2. You can switch messages by
:hp1.typing in the corresponding number and pressing enter&colon.:ehp1.
:xmp.
Area: w4abc (#0) >
1
Message #1
Date: Wed, 21 Jan 2026 14:12:14 CST
From: w4abc@jnos2.wa4xyz.radio
To: w4abc
Subject: test email

this is a test message to demonstrate JNOS's BBS.

Area: w4abc (#1) >
2
Message #2
Date: Wed, 21 Jan 2026 14:15:14 CST
From: n4ham@jnos2.wa4xyz.radio
To: w4abc
Subject: welcome to the BBS!

Welcome to the BBS, Example Human Being!

Area: w4abc (#1) >
:exmp.
:p.At this point, you can use the :pk.kill:epk. command to remove the
old messages; otherwise, you can save the messages and log out:
:xmp.
Area: w4abc (#1) >
b
Connection closed by foreign host.
:exmp.
:p.You will return to the shell prompt.
:h5.Advanced Mode
:p.If your user account has been keyed into :pk.ftpusers:epk. and you
are marked as an :hp1.advanced user:ehp1., you will be able to see a
more complex shell prompt, but also possibly enter :hp5.sysop
mode:ehp5. to break into a JNOS shell and run any command. With
:hp5.advanced mode:ehp5. on, your shell prompt changes to this:
:i3.Advanced shell mode
:xmp.
login: n4ham
Password:
[JNOS-2.0p-B1FHIM$]

You have 0 messages.
Area: n4ham Current msg# 0.
?,A,B,C,CONV,D,E,F,H,I,IH,IP,J,K,L,M,N,NR,O,P,PI,R,S,T,U,V,W,X,Z >
:exmp.
:p.Advanced mode was intended to emulate the user interface of TheNet,
BPQ, K-node, and other such popular packet radio packages; you will
notice that this long shell prompt of letters will show up on several
other BBSes.
:p.Now that we are in advanced mode, we can enter some commands to
:hp1.discover adjacent :hp2.NET/ROM:ehp2. nodes.:ehp1. and also connect
to them.
Use the :pk.n:epk. command to list nodes, then use :pk.c:epk. to
connect to them:
:xmp.
Area: n4ham Current msg# 0.
?,A,B,C,CONV,D,E,F,H,I,IH,IP,J,K,L,M,N,NR,O,P,PI,R,S,T,U,V,W,X,Z >
n
EVIE1&colon.WA4XYZ-7
*** 1 nodes displayed
Area: n4ham Current msg# 0.
?,A,B,C,CONV,D,E,F,H,I,IH,IP,J,K,L,M,N,NR,O,P,PI,R,S,T,U,V,W,X,Z >
c evie1
Trying...  The escape character is: CTRL-T
*** connected to EVIE1&colon.WA4XYZ-7
nodes
WA4XYZ-1} Nodes:
JNOSXX&colon.WA4XYZ-8   EVIE1&colon.WA4XYZ-7
bye

*** reconnected to JNOSXX&colon.WA4XYZ-8


Area: n4ham Current msg# 0.
?,A,B,C,CONV,D,E,F,H,I,IH,IP,J,K,L,M,N,NR,O,P,PI,R,S,T,U,V,W,X,Z >
:exmp.
:p.Making NET/ROM connections is fairly easy, but making
:hp2.AX.25-NoL3:ehp2. connections will require you to be aware of the
:hp5.port.:ehp5. You can use the :pk.p:epk. command:
:xmp.
Area: n4ham Current msg# 0.
?,A,B,C,CONV,D,E,F,H,I,IH,IP,J,K,L,M,N,NR,O,P,PI,R,S,T,U,V,W,X,Z >
p
Available AX.25 Ports:
ax2
ax1
ax0
Available HFDD Ports:
Available VARA Ports:

Area: n4ham Current msg# 0.
?,A,B,C,CONV,D,E,F,H,I,IH,IP,J,K,L,M,N,NR,O,P,PI,R,S,T,U,V,W,X,Z >
:exmp.
:p.In this mode, it can be rather difficult to determine which port is
present on which frequency/interface; as such, :hp1.sysops should
assign descriptive names if they wish to remedy this!:ehp1. Alas, you
can use the :pk.c:epk. command to bring up a connection:
:xmp.
c ax1 wa4xyz-1
Trying...  The escape character is: CTRL-T
*** connected to WA4XYZ-1
nodess
WA4XYZ-1} Nodes:
JNOSXX&colon.WA4XYZ-8   EVIE1&colon.WA4XYZ-7
byee

*** reconnected to JNOSXX&colon.WA4XYZ-8
:exmp.
:p.You can also make :hp2.Telnet:ehp2. connections with the :pk.T:epk.
command:
:xmp.
Area: n4ham Current msg# 0.
?,A,B,C,CONV,D,E,F,H,I,IH,IP,J,K,L,M,N,NR,O,P,PI,R,S,T,U,V,W,X,Z >
t 192.168.48.1
Resolving 192.168.48.1... Trying...  The escape character is: CTRL-T
*** connected to 192.168.48.1&colon.telnet
login: &hat.T

Area: n4ham Current msg# 0.
?,A,B,C,CONV,D,E,F,H,I,IH,IP,J,K,L,M,N,NR,O,P,PI,R,S,T,U,V,W,X,Z >
:exmp.
:p.As shown above, pressing :hp2.control-T:ehp2. will drop you from the
connection.
:h5.Sysop Mode
:p.With all of this in mind, advanced mode may be more ideal for
registered users. However, there is one more mode that we must cover:
:hp5.sysop mode.:ehp5. Since it may sometimes be necessary to access
the JNOS shell remotely, the JNOS authors were sure to include a
mechanism to do so; enter the :pk.@:epk. command to switch:
:i3.Sysop shell mode
:xmp.
Area: n4ham Current msg# 0.
?,A,B,C,CONV,D,E,F,H,I,IH,IP,J,K,L,M,N,NR,O,P,PI,R,S,T,U,V,W,X,Z >
@ pass123

Type 'exit' to return
Jnos> ip status
( 1)ipForwarding                 1     ( 2)ipDefaultTTL               225
( 3)ipInReceives           5451444     ( 4)ipInHdrErrors                0
( 5)ipInAddrErrors               0     ( 6)ipForwDatagrams              0
( 7)ipInUnknownProtos            0     ( 8)ipInDiscards                 0
( 9)ipInDelivers           4737473     (10)ipOutRequests          4530960
(11)ipOutDiscards                0     (12)ipOutNoRoutes                4
(13)ipReasmTimeout               4     (14)ipReasmReqds           1422918
(15)ipReasmOKs              708947     (16)ipReasmFails               101
(17)ipFragOKs                    0     (18)ipFragFails                  0
(19)ipFragCreates                0
Jnos> exit
Area: n4ham Current msg# 0.
?,A,B,C,CONV,D,E,F,H,I,IH,IP,J,K,L,M,N,NR,O,P,PI,R,S,T,U,V,W,X,Z >
:exmp.
:p.Now that you are familiar with basic JNOS usage, let us also
understand some of the more advanced features this package provides.
:h3.Advanced Configuration
:p.JNOS provides more features than are readily documented in this
manual; it is highly recommended that you explore not only the old JNOS
manuals, but also press :pk.?:epk. frequently to discover new things!
:ih2.Advanced topics
:h5.IPIP Tunnels
:p.An IPIP tunnel, using :hp5.IP protocol 4:ehp5., is a useful method
of bridging two disparate networks. Note that you :hp1.cannot
port-forward:ehp1. an IPIP tunnel unless your router is using
OpenBSD :pv.pf:epv..
:fn.You can enter a rather simplistic :pk.pf.conf:epk. rule like so,
where :pk.$ext-if:epk. is the external interface, and :pk.$lan_ip:epk.
is the IP address of a host on your LAN running JNOS (possibly one
route hop away):
:i3.IPIP tunnels
:xmp.match in on $ext_if proto { 4, 94 } rdr-to $lan_ip
:exmp.

:efn.
:p.To create one of these, first define it on the target operating
system. Since this depends on the OS in question, several examples will
be provided for various OSes. In this example, :pk.198.18.0.0/24:epk.
is the subnet within the tunnel, and :pk.192.168.48.0/24:epk. is the
subnet used on the :pk.tun0:epk. device to communicate with the host.
:hp1.If the target host is :hp3.not:ehp3. the same machine running
JNOS, you will need to engage :hp3.IP forarding:ehp3. (i.e. routing) to
allow the target host and remote host to communicate.:ehp1.
:p.:hp2.Linux:ehp2., old method:
:xmp.
# iptunnel add mode ipip local 192.168.48.1 remote 192.168.48.2
# ifconfig ipip0 198.18.0.1 dstaddr 198.18.0.2 up
:exmp.
:p.:hp2.Linux:ehp2., new method:
:xmp.
# modprobe ipip
# modprobe new_tunnel
# ifconfig tunl0 198.18.0.1 pointopoint 192.168.48.2 up
:exmp.
:p.:hp2.FreeBSD:ehp2.:
:xmp.
# ifconfig gif0 create
# gifconfig gif0 inet 192.168.48.1 192.168.48.2
# ifconfig gif0 198.18.0.1 netmask 255.255.255.252 198.18.0.2
# ifconfig gif0 mtu 1500 up
:exmp.
:p.:hp2.Cisco IOS:ehp2.:
:xmp.
interface Tunnel1
 ip address 198.18.0.1 255.255.255.252
 tunnel mode ipip
 tunnel destination 192.168.48.4
 tunnel source 192.168.48.1    <--- change me!
!
:exmp.
:p.:hp2.JNOS:ehp2.:
:xmp.
route add 198.18.0.0/24 encap 192.168.48.1
:exmp.
:p.Note that there are also :hp2.NOS tunnels:ehp2. (sometimes called
:hp1.KA9Q tunnels:ehp1.) that use
:hp2.IP protocol 94:ehp2. instead. The reason for this is historical in
nature, but it will require that the setup commands are now different.
:h5.SLIP
:p.SLIP is :hp2.Serial Line IP:ehp2., and is a simplistic way of
framing IP packets on a serial cable (either synchronous or
asynchronous). If you need to get JNOS to talk to an embedded device,
SLIP might be ideal!
:i3.SLIP
:p.Setup is fairly straightforward, :hp1.but note that modern operating
systems like FreeBSD have actually removed SLIP support.:ehp1.
:p.:hp2.Linux:ehp2.:
:xmp.
# slattach -L -p slip -s 9600 /dev/ttyUSB0
# ifconfig sl0 198.18.0.2 dstaddr 198.18.0.1 up
:exmp.
:p.:hp2.JNOS:ehp2.:
:xmp.
jnos> attach asy ttyU0 - slip sl0 4096 296 9600
jnos> ifconfig sl0 ipaddress 198.18.0.1 netmask 0xffffffff up
jnos> route add 198.18.0.2/32 sl0
:exmp.
:h5.PPP
:p.The :hp2.Point-to-Point Protocol:ehp2. is a multiprotocol link-layer
protocol intended to replace SLIP on serial connections. PPP is
:hp1.intelligent:ehp1., and more than IP can be ran over it.
:i3.PPP
:fn.At the time of writing this, I have set up IPv4, IPv6, DECnet, IPX,
SNA, AppleTalk, OSI/CLNS, CDP, VINES, XNS, and Apollo/Domain over PPP.
:efn.
:p.The difficulty of this configuration lies in not JNOS, :hp1.but the
host instead;:ehp1. there is a standard PPP command (:pk.pppd:epk.) but
other OSes have different methods. Some are as follows:
:p.:hp2.Linux:ehp2.:
:xmp.
# pppd nodetach local noauth passive debug nobsdcomp \
    nodeflate noccp nocrtscts 198.18.0.1:198.18.0.2 \
    /dev/ttyUSB0 115200
:exmp.
:p.:hp2.FreeBSD:ehp2.:
:xmp.
# ppp
ppp ON bsdserver> set device /dev/ttyu2
ppp ON bsdserver> set speed 115200
ppp ON bsdserver> set ctsrts off
ppp ON bsdserver> set ifaddr 198.18.0.1 198.18.0.2
ppp ON bsdserver> set log Phase Chat Connect LCP IPCP IPV6CP CCP
ppp ON bsdserver> disable pap chap passwdauth
ppp ON bsdserver> open lcp
ppp ON bsdserver> open ipcp
:exmp.
If you get strange errors about :pk./var/lock:epk. not existing,
run :pk.mkdir /var/lock:epk. to alleviate them.
:p.:hp2.JNOS:ehp2.:
:xmp.
jnos> attach asy ttyU0 - ppp ppp0 4096 1500 115200
jnos> ppp ppp0 lcp open
jnos> ppp ppp0 ipcp open
jnos> ifconfig ppp0 netmask 0xffffff00
jnos> route add 198.18.0.1/32 ppp0
:exmp.
JNOS will request and acquire an address from the remote. If you wish
for JNOS to instead provide an address to the remote, enter these
commands:
:xmp.
jnos> ppp ppp0 ipcp local address 198.18.0.2
jnos> ppp ppp0 ipcp remote address 198.18.0.1
:exmp.
:h5.IPv6
:p.With newer versions of JNOS 2.0, the package has full IPv6 support;
this makes it the only amateur packet stack to support it. While this
guide will not configure IPv6 setup in detail (and will certainly not
explain how to set up IPv6 on your home network, good luck though!),
basic IPv6 configuration will be described.
:i3.IPv6
:p.If JNOS can communicate with the host using IPv4 with a :hp1.tun
device:ehp1., IPv6 uses a :hp3.tap device:ehp3. -- the reason for this
is because there is no assurance that the protocol number (which
conveys IPv6 presence) will make its way through the :pk.tun:epk.
device.
:fn.This is particularly a problem on Linux, where both the application
using the :pk.tun:epk. device driver and the kernel must make an
inference based on the :hp5.version number:ehp5.; BSD does not have
this issue with its superior implementation of the :pk.tun:epk. driver.
:efn.
:p.As such, you must first create a :pk.tap0:epk. device for JNOS to
use; the steps here depend on the OS running JNOS:
:p.:hp2.Linux:ehp2., old method:
:xmp.
1. Create the tap device
# tunctl -t tap0 -u root
# ifconfig tap0 up
2. Create the bridge and assign the device to the bridge
# brctl addbr br0
# brctl addif br0 tap0
# ifconfig br0 up
# ifconfig br0 inet6 fd00&colon.4&colon.&colon.1/64
:exmp.
:p.:hp2.Linux:ehp2., new method:
:xmp.
# ip tuntap add mode tap dev tap0
# ip link add dev br0 type bridge
# ip link set tap0 up
# ip link set tap0 master br0
# ip link set br0 up
# ip -6 addr add dev br0 fd00&colon.4&colon.&colon.1/64
:exmp.
:p.:hp2.FreeBSD:ehp2.:
:xmp.
1. Create the tap device
# ifconfig tap0 create
# ifconfig tap0 up
-- OR on old FreeBSD --
# kldload if_tap
# cat /dev/tap0
&hat.C
# ifconfig tap0 up
2. Create the bridge and assign the device to the bridge
# ifconfig bridge0 create
# ifconfig bridge0 addm tap0 up
# ifconfig bridge0 inet6 fd00&colon.4&colon.&colon.1 prefixlen 64
# route add -inet6 fd00&colon.4&colon.&colon./64 -iface bridge0
:exmp.
:p.:hp2.JNOS:ehp2.:
:xmp.
jnos> attach tun tap0 1500 0
jnos> ipv6 addr
(the default will be FD00:4::2/64)
jnos> ipv6 iface tap0
jnos> start telnet -6
jnos> start http -6
:exmp.
:hp1.(note that the :pk.start:epk. commands will replace the ones
described earlier on in this guide):ehp1.
:h5.RIP and Automatic Routing
:p.In addition to using static routes, you can also use :hp2.RIP:ehp2.
to dynamically exchange routes. :hp5.Note that poorly implementing this
protocol in an uncontrolled fashion leaves your network not only open
to attacks, but also massive breakage:ehp5. -- use it with caution!
:i3.RIP
:p.Starting RIP on JNOS is done the same way as any other:pk.start:epk.
command:
:xmp.
jnos> start rip
:exmp.
:p.You now need to instruct JNOS to either request a router or listen
for broadcasts; this is done explicitly:
:xmp.
jnos> rip request 192.168.50.1
:exmp.
:p.To accept announcements:
:xmp.
jnos> rip accept 192.168.50.1
:exmp.
:h3.NOSaprs
:p.APRS, while already covered, has :hp1.excellent:ehp1. support within
JNOS. Not only can JNOS be an :hp2.I-gate:ehp2., but also a full APRS
BBS and mail relay! Let us examine the configuration.
:i2.NOSaprs
:p.First, enable or disable APRS logging. This will go
at :pk./jnos/spool/log/aprs.log:epk. if you enable it:
:xmp.aprs log on
:exmp.
:p.You then need to select interfaces to run APRS on:
:xmp.aprs interface ax0
aprs interface ax1
:exmp.
:p.Set the callsign used for APRS's I-gate client:
:fn.Normally, you would need to specify a login passcode; this is
actually :hp1.not necessary:ehp1. for NOSaprs.
:efn.
:xmp.aprs logon call WA4XYZ-3
:exmp.
:p.When you log into the APRS-IS system, you need to specify a
:hp2.filter:ehp2. (or you will get :hp5.no:ehp5. APRS traffic at all):
:fn.See the section earlier on :hp2.APRS Filters:ehp2. to understand
these!
:efn.
:xmp.aprs logon filter m/50
:exmp.
:p.Inevitably, you will want to set up beacons. You can configure
unique beacons for the APRS-IS side and the RF side(s), so enter those
accordingly:
:xmp.aprs bc stat "Super Cool JNOS APRS Box"
aprs bc pos "3561.22N/08723.75WBWA4XYZ-3 JNOS Rocks!"
aprs bc timer 10
aprs bc rfstat "Super Cool JNOS APRS Box"
aprs bc rfpos "3561.22N/08723.75WBWA4XYZ-3 JNOS Rocks!"
aprs bc rftimer 10
:exmp.
:p.I will not provide an overtly-detailed explanation for this as it is
somewhat out of the scope for this document, but the :pk.B:epk.
between :pv.08723.75W:epv. and :pk.WA4XYZ-3:epk. is the :hp2.symbol
selector:ehp2. and the :pk./:epk. between :pv.3561.22N:epv.
and :pv.08723.75W:epv. is the :hp2.table selector.:ehp2.
:fn.If you are confused, see the symbol table in the first half of this
book.
:efn.
:p.The :pk.stat:epk. and :pk.pos:epk. beacons result in :hp1.two:ehp1.
effective lines of text; these show up as a purple object :hp5.status
text:ehp5. and a green object :hp5.beacon text.:ehp5.
:p.Configure the heard-station table size:
:xmp.aprs hsize 50
:exmp.
:p.Specify the contact and a locator that shows up on the TCP port
14501 HTTP status page that JNOS runs:
:xmp.aprs contact m "wa4xyz@arrl.org"
aprs locator "https://aprs.fi"
:exmp.
:p.You need to configure an :hp2.APRS server:ehp2. to make the I-Gate
function. This can be the public one, your own copy of :pk.aprsc:epk.,
XRouter's APRS server, or others. Here is one example:
:xmp.aprs server add noam.aprs2.net 14580
:exmp.
:p.You can then enable APRS-IS to RF gating:
:xmp.
aprs calls fwdtorf *
aprs calls postorf *
aprs calls stattorf *
aprs calls wxtorf *
aprs calls obj2rf *
:exmp.
:p.On the aforementioned APRS status page, you can also set the
:q.public:eq. IP address:
:xmp.aprs internal 192.168.50.2
:exmp.
:p.If you wish to allow web browser users to send and receive APRS
messages using that interface, you need to authorize their IP addresses:
:xmp.aprs calls ip45845 198.18.0.2
:exmp.
:p.For APRS email, make JNOS's SMTP server process it:
:xmp.aprs email local
:exmp.
:p.Engage APRS listening on the interfaces you specified earlier:
:xmp.aprs listen on
:exmp.
:p.You are almost done. Start the APRS listeners:
:xmp.
# If you want the NOSaprs status page to be available,
# for example, 'http&colon.//localhost:14501'.
start aprs 14501
# If you want the NOSaprs browser based message center
# for example, 'http&colon.//localhost:14845'.
start aprs 14845
:exmp.
:p.Engage the transmitting I-Gate functionality :hp1.and:ehp1.
digipeater operation with this:
:xmp.aprs flags +aprs_txenable +digi
:exmp.
:p.For any APRS packets to properly route out of the TNC interfaces,
you need to add a special route for the logical callsign :pk.APZ115:epk.:
:xmp.ax25 route add APZ115 ax0
:exmp.
:p.Congratulations, you now have working NOSaprs. Check that the NOS
node beacons out on both RF and APRS-IS (you can check that
with :pk.https&colon.//aprs.fi:epk., Xastir, UI-View32, YAAC, or any
other APRS client), and have fun!
:h1.BPQ Packet Engine
:p.John Wiseman, G8BPQ, has a long-standing history of influencing
packet radio in :hp1.several:ehp1. important ways; his most profound
contribution is the :hp2.BPQ Packet Engine:ehp2. (which has undergone
several name changes over the course of its life).
:p.There are several versions of BPQ:
:ul.
:li.:hp2.BPQCODE:ehp2., for MS-DOS
:li.:hp2.LinBPQ:ehp2., for Linux
:li.:hp2.BPQ32:ehp2., for 32-bit Windows
:eul.
:p.First, we will discuss :hp2.LinBPQ:ehp2. (since it is rather likely
that you, as a ham radio operator, have plenty of Linux machines
sitting around).
:p.BPQ does, however, have stellar implementations of:
:ul.
:li.APRS
:li.A mail system/PMS
:li.A chat server
:eul.
:p.Note conversely that BPQ does :hp5.not:ehp5. have:
:ul.
:li.TCP/IP
:li.A configuration GUI
:eul.
:h2.LinBPQ
:p.This section is for the Linux or BSD versions of BPQ.
:h3.Installation
:p.Note that the following :hp2.dependencies:ehp2. are required to
compile LinBPQ:
:ul.
:li.:pk.libconfig:epk.
:li.:pk.libpcap:epk.
:eul.
:p.LinBPQ can be compiled without too much difficulty. :hp1.Clone:ehp1.
the source code from GitHub as follows, then compile it:
:xmp.$ git clone https&colon.//github.com/g8bpq/linbpq
$ cd linbpq
$ make
:exmp.
:p.Once the compilation has completed successfully, you may start
configuring it. Inevitably, you will want to :hp2.relocate:ehp2.
the:pk.linbpq:epk. binary to some other run directory; if this is a
multiuser system and you would like to ensure its security, ensure that
the directory permissions disallow world-write (and world-read if you
like).
:fn.For the Linux-impaired, this would consist of :pk.chmod 700
bpq_directory_name:epk..
:efn.
:h3.Configuration
:p.The BPQ configuration statements are stored in a file
named:pk.bpq32.cfg:epk. :hp1.(and do note that the filename is
case-sensitive).:ehp1. Open that file with your favorite editor and
begin entering as follows!
:p.First, you will want to enable the features (i.e. services) that
you'd like. These are :pk.LINMAIL:epk. and :pk.LINCHAT:epk.:
:xmp.LINMAIL
LINCHAT
:exmp.
:p.Now, you need to set the :hp2.sysop password:ehp2.:
:xmp.PASSWORD=bpqr0ck5
:exmp.
:p.Set the node callsign, NET/ROM callsign, node alias, and gridsquare
locator:
:fn.BPQ, unlike the Linux AX.25 stack, is smart enough to distinguish
the protocol ID in the AX.25 frames when multiple connection attempts
occur. In other words, it is :hp5.not necessary to use two different
callsigns:ehp5. for NET/ROM and :q.plain:eq. AX.25-noL3 communication.
:efn.
:fn.To :hp2.stay off the BPQ map,:ehp2. simply set the locator
to :pk.NONE:epk. and also include :pk.MAPCOMMENT=NONE:epk. in the
configuration file.
:efn.
:xmp.NODECALL=WA4XYZ-8
NETROMCALL=WA4XYZ-8
NODEALIAS=MYBPQ
LOCATOR=FN03
MAPCOMMENT=Packet node in Neverland, NX
:exmp.
:p.You now need to set various :hp2.NET/ROM parameters:ehp2.:
:xmp.                ; Max number of hops a node can be announced
OBSINIT=6            ; Threshold to remove nodes from broadcasts
OBSMIN=4
NODESINTERVAL=10     ; Routing broadcast interval (minutes)
L3TIMETOLIVE=20      ; Max L3 (NET/ROM) hops
L4RETRIES=3          ; Max packet retries before a session dies
L4TIMEOUT=60         ; How many seconds before a connection is dead
L4WINDOW=4           ; Window size in packets
MAXLINKS=256         ; Max L2 links
MAXNODES=512         ; Max nodes in routing table
MAXROUTES=144        ; Max adjacent node links
MAXCIRCUITS=160      ; Max L4 session circuits
MINQUAL=1            ; Lowest node quality allowed in the routelist
PACLEN=236           ; L3 packet size (assuming 256 for L2)
T3=120               ; Link keepalive time in seconds
IDLETIME=720         ; Number of seconds before a link closes
:exmp.
:p.It should be noted that the following terms have special
significance in the world of BPQ:
:ol.
:li.:hp2.Links:ehp2. are AX.25 virtual circuits that are propped up
between nodes to carry NET/ROM traffic
:li.:hp2.Nodes:ehp2. are known NET/ROM hosts
:li.:hp2.Routes:ehp2. are known adjacent NET/ROM nodes and the path
taken to get there
:li.:hp2.Obsolecence:ehp2. prevents stale routing table entries from
locking up an entire packet network
:eol.
:p.You can emulate an :hp2.AGW Packet Engine:ehp2. virtual TNC and
allow all manner of AX.25 terminal programs to use BPQ as a :q.virtual
TNC:eq. (therefore permitting you to talk directly into the network
without having several TNCs):
:fn.:hp2.UZ7HO EasyTerm:ehp2. is a good choice if you use Windows,
otherwise use :hp2.QtTermTCP:ehp2. on other OSes (note that this
program can connect to the :pk.FBBPORT:epk. or to the :pk.AGWPORT:epk.
depending on configuration options).
:efn.
:xmp.
AGWPORT=8100
AGWMASK=0x30
AGWSESSIONS=10
AGWLOOPMON=1
AGWLOOPTX=1
:exmp.
:p.There are a few more extra config options that should be set:
:xmp.
AUTOSAVE=1           ; Save routing table in BPQNODES.dat
BBS=1                ; Set to 1 to include BBS support
NODE=1               ; Set to 1 to allow cross-port packet gating
HIDENODES=0          ; Set to 1 to hide nodes starting with '#'
ENABLE_LINKED=A      ; Only allow linking to application programs
:exmp.
:p.Now, you will want to configure :hp2.broadcasts:ehp2. and beacons:
:xmp.
BTINTERVAL=1         ; Flat beacon interval in minutes
BTEXT:
My Super Cool BPQ Node
***

IDINTERVAL=1         ; UI ID broadcast interval in minutes
IDMSG:
My Super Cool BPQ Node
***
:exmp.
:p.When users connect, you will want to include a :hp2.information
text:ehp2. for them to view:
:xmp.
INFOMSG:
This is a packet radio shell.
Please do not just copy and paste these configuration statements,
but understand what they do.

***
:exmp.
:p.You should also set a :hp2.connection text:ehp2. that users see when
they connect:
:xmp.a
FULL_CTEXT=0         ; Set to 1 to display this on all connects
CTEXT:
Welcome to Anna Airwave's super cool packet node!
***
:exmp.
:p.You can add :hp2.locked routes:ehp2. if you wish, but our example
will not have any:
:xmp.ROUTES:
***
:exmp.
:h4.Ports
:p.Now, we should configure :hp2.ports.:ehp2. There are slightly
different syntaxes for various types of interfaces, so here are some
examples:
:h5.AX/IP and AX/UDP
:p.These are managed by the same port driver:
:xmp.
PORT
 PORTNUM=20
 ID=AX/IP                       ; AX/IP/UDP Wormholes
 DRIVER=BPQAXIP                 ; Uses BPQAXIP.DLL
 QUALITY=192
 MINQUAL=191
 MAXFRAME=7                     ; Max outstanding frames (1 thru 7)
 FRACK=7000                     ; Level 2 timout in milliseconds
 RESPTIME=1000                  ; Level 2 delayed ack timer in milliseconds
 RETRIES=10                     ; Level 2 maximum retry value
 PACLEN=236
 CONFIG
  UDP 10093                     ; Listens for UDP packets on this UDP port
  MHEARD
  BROADCAST NODES
  AUTOADDMAP                    ; Automatically add lines based on UDP packets
  MAP WA4XYZ-1 198.18.12.4 B
  MAP N4HAM-3 192.168.50.2 B
  MAP AA4XY-2 44.96.23.12 UDP 10093 B
ENDPORT
:exmp.
:h5.Telnet Port
:p.This allows inbound connections via :hp2.Telnet:ehp2., permitting
easy node operation.
:xmp.
PORT
 PORTNUM=15
 ID=Telnet
 DRIVER=TELNET
 MHEARD=Y
 QUALITY=192
 CONFIG
  LOGGING=1
  TCPPORT=7300
  FBBPORT=8011
  HTTPPORT=81
  CMDPORT=23                              ; see note
  CTEXT=Connected to MYBPQ\nEnter ? for list of commands\n\n
  LOGINPROMPT=Callsign:
  PASSWORDPROMPT=Password:
  DisconnectOnClose=1
  MAXSESSIONS=10
  LOCALNET=10.0.0.0/24
  USER=n4ham,rizz123,N4HAM,,SYSOP         ; user,pass,call,command,sysop?
ENDPORT
:exmp.
:p.Of important note is the :pk.CMDPORT:epk. field -- this will be used
to create custom applications; see the :hp2.Applications:ehp2. section
below.
:h5.KISS TNCs
:p.TODO
:h5.Applications
:p.BPQ permits definition of various :hp2.applications:ehp2. that
permit access to remote systems or local services. These take the form
of custom :hp5.commands:ehp5. that users may invoke upon connecting.
Here are some samples:
:p.This is for access to the integrated :hp2.BBS:ehp2.; :pk.BBS:epk. is
the command, :pk.WA4XYZ-9:epk. is the logical callsign assigned to the
application, and :pk.MYBBS:epk. is its NET/ROM node alias (since this
is reachable outside of this node):
:xmp.APPLICATION 1,BBS,,WA4XYZ-9,MYBBS,255
:exmp.
:p.This is for access to the integrated :hp2.chat server:ehp2.; the
same parameters as above apply:
:xmp.APPLICATION 2,CHAT,,WA4XYZ-10,MYCHT,255
:exmp.
:p.The generic form of this command is:
:xmp.APPLICATION n,cmd,newcmd,call,alias,quality,l2alias
:exmp.
:ul.
:li.:pk.n:epk.: the application number, you can have up to 32
:li.:pk.cmd:epk.: the command the user types on the shell
:li.:pk.newcmd:epk.: the node command to be ran :hp1.(optional):ehp1.
:li.:pk.call:epk.: the callsign that, upon being connected to, executes
the command immediately :hp1.(optional):ehp1.
:li.:pk.alias:epk.: the NET/ROM alias that serves the same purpose as
the :pk.call:epk. field :hp1.(optional):ehp1.
:li.:pk.quality:epk.: the quality of the above :pk.call:epk.
and :pk.alias:epk. :hp5.Note: you need all three
(:pk.call,alias,quality:epk.) for this to work:ehp5. :hp1.(optional):ehp1.
:li.:pk.l2alias:epk.: functions like the :pk.call,alias,quality:epk.
triplet, but for AX.25-NoL3 connections
:eul.
:p.So, in order to create :hp1.local shell applications:ehp1., you need
to do two things:
:ol.
:li.Create or update the :pk.CMDPORT:epk. line in a Telnet port
definition
:li.Create :pk.APPLICATION:epk. lines
:eol.
:p.First, let us understand the :pk.CMDPORT:epk. field. Within your
Telnet port definition (which, in this example, holds port number 15)
you will see that field. This is a space-delimited list of sockets that
BPQ can connect to :hp1.on the host:ehp1..
:p.These TCP ports are indexed from zero, but are unrelated to the
actual ports themselves. For example, you could have these in
your :pk.CMDPORT:epk. list:
:xmp.CMDPORT 23 1023
:exmp.
:p.This would allow you to connect to the host's Telnet socket and some
other service on port 1023. :hp3.However, we can use this technique to
write custom commands!:ehp3.
:p.For example, let us create an example application that prints a
message upon connection. First, update :pk.CMDPORT:epk.:
:xmp.CMDPORT 60000 60001 60002
:exmp.
:p.:hp1.Note that there are three ports present here, we will only have
an application listen on the first one, though!:ehp1.
:p.You now need to create a program that outputs some text upon
connection. This can be done using :pk.inetd:epk., :hp1.systemd
sockets:ehp1., or a totally custom server that accepts raw TCP
connections.
:p.Create the following shell script somewhere,
like :pk./usr/local/lib/bpqdemo.sh:epk., with the following contents:
:xmp.#!/bin/bash
echo "Demonstration BPQ Application"
:exmp.
:p.Make this script executable and make sure that it runs:
:xmp.$ chmod +x bpqdemo.sh
$ ./bpqdemo.sh
Demonstration BPQ Application
:exmp.
:p.Next, if you are using :pk.systemd:epk., you need to create
:hp5.two:ehp5. files -- one will be a :hp1.socket:ehp1. and the other
will be a :hp1.service.:ehp1. First,
edit :pk./lib/systemd/system/bpqdemo.socket:epk.:
:xmp.
&lbrk.Unit&rbrk.
Description=Demo BPQ Application

&lbrk.Socket&rbrk.
ListenStream=60000
Accept=yes

&lbrk.Install&rbrk.
WantedBy=sockets.target
:exmp.
:p.Likewise, update :pk./lib/systemd/system/bpqdemo@.service:epk.:
:xmp.
&lbrk.Unit&rbrk.
Description=Demo BPQ App Server

&lbrk.Service&rbrk.
ExecStart=/usr/local/lib/bpqdemo.sh
StandardInput=socket
:exmp.
:p.You now need to tell :pk.systemd:epk. of the changes. Run these
commands :hp5.as root:ehp5.:
:xmp.
# systemctl daemon-reload
# systemctl start bpqdemo.socket
:exmp.
:p.Finally, test it:
:xmp.$ nc localhost 60000
Demonstration BPQ Application
:exmp.
:p.If you are using :pk.inetd:epk., it is much easier; add the
following line to :pk./etc/inetd.conf:epk.:
:xmp.600000  stream  tcp   nowait  root  /usr/local/lib/bpqdemo.sh bpqdemo.sh
:exmp.
:p.Restart :pk.inetd:epk. as root:
:xmp.# pkill -9 inetd
# inetd
:exmp.
:p.Now that the server process is ready, you now need to :hp2.update
the application line:ehp2. for it. Looking above, you should see
the :pk.cmd:epk. field of the :pk.APPLICATION:epk. line. In lieu of a
normal :pk.C:epk. (:pk.CONNECT:epk.) command, you will be using a
command like this:
:xmp.C 15 HOST 0
:exmp.
:p.The command arguments are as follows:
:ol.
:li.:pk.C:epk.: short for :pk.CONNECT:epk.
:li.:pk.15:epk.: port number of the Telnet link driver, 15 in this
example (but you can change the number)
:li.:pk.HOST:epk.: logical callsign on the Telnet port to make TCP
connections to :pk.localhost&colon.PORT:epk. where :pk.PORT:epk. is one
of the TCP ports listed in the :pk.CMDPORT:epk. argument on the port
definition
:li.:pk.0:epk.: use the :q.zeroth:eq. port of the :pk.CMDPORT:epk.
list, so the first one listed.
:eol.
:h3.Usage
:p.Inevitably, you will want to connect to your LinBPQ node by either
pointing another packet radio node at it, but you have two other
important options:
:ul.
:li.QtTermTCP or BPQTermTCP
:li.Telnet
:eul.
:p.You will want to try all of these, starting with :hp2.QtTermTCP.:ehp2.
:h4.QtTermTCP
:p.This program is a cross-platform successor to :hp3.BPQTermTCP:ehp3.
and is quite slick! Installation will not be described in great detail,
but John Wiseman has instructions on his site.
:p.Assuming you created a Telnet port, take note of the :pk.FBBPORT:epk.
that you entered earlier. With QtTermTCP open, go to :hp2.Setup ->
Hosts -> New Host:ehp2.. The options are as follows:
:ol.
:li.:hp2.Host Name:ehp2.: the IP address of the LinBPQ node you are
connecting to
:fn.Use :pk.127.0.0.1:epk. or :pk.localhost:epk. if you are running
QtTermTCP and LinBPQ on the same machine.
:efn.
:li.:hp2.Port:ehp2.: the :pk.FBBPORT:epk. number entered in the Telnet
port settings on the node
:li.:hp2.User:ehp2.: one of the username/password combinations in the
Telnet port settings, which would be :pk.n4ham:epk. in this example
:li.:hp2.Password:ehp2.: the password corresponding to the above
username, :pk.rizz123:epk. in this example
:li.:hp2.Session Name:ehp2.: a descriptive name of your
choosing, :pk.MYBPQ:epk. in this example
:eol.
:p.Go to :hp2.Connect -> 127.0.0.1(MYBPQ):ehp2. (or whatever you
entered), and you should see output on the bottom window:
:xmp.Connected to TelnetServer
:exmp.
:p.Enter a command, like :pk.?:epk. for some help:
:xmp.?
MYBPQ&colon.WA4XYZ-8} BBS CHAT SHELL CONNECT BYE INFO NODES PORTS ROUTE
:exmp.
:p.These various comands will do exactly what you might think:
:xmp.
nodes
MYBPQ&colon.WA4XYZ-8} Nodes
MYBBS&colon.WA4BPQ-9     MYCHT&colon.WA4XYZ-8     JNOSXX&colon.WA4XYZ-5
LNXVM&colon.WA4XYZ-7     ZLNX2&colon.WA4XYZ-2
:exmp.
:p.To make a :hp2.connection to another node:ehp2., use the :pk.C:epk.
command:
:xmp.
c lnxvm
MYBPQ&colon.WA4XYZ-8} Connected to LNXVM&colon.WA4XYZ-7
?
WA4XYZ-7} Commands:
?, Announce, Bye, Connect, Desti, DXCluster, Escape, Finger, Help,
HOst
Info, INTerfaces, Jheard, JLong, Links, MSg, NEtstat, Nodes, Ping,
Quit
Routes, Sessions, STatus, Telnet, Users, Version, Who
bye
Disconnected
:exmp.
:p.Note that when you disconnect from a remote node, :hp5.you will be
disconnected from the local node:ehp5. unless you go change that.
:p.You may also wish to :hp2.set the monitor/screen split:ehp2. for
more screen real-estate; to do that, :hp1.right-click:ehp1. and select
:q.Set Monitor/Output Split.:eq.
:p.The other BPQ commands will work, including the :hp2.BBS:ehp2.:
:xmp.
bbs
MYBPQ&colon.WA4XYZ-8} Connected to BBS
&lbrk.BPQ-6.0.23.76-IHJM$&rbrk.
Hello Evie. Latest Message is 14, Last listed is 0
Please enter your Home BBS using the Home command.
You may also enter your QTH and ZIP/Postcode using qth and zip commands.
de N4HAM>
bye
Disconnected
:exmp.
:p.:hp2.The BBS commands here are common to the XRouter and JNOS
BBS.:ehp2. As such, you should be able to learn how to use it rather
quickly by typing :pk.?:epk.!
:h4.Telnet
:p.To access the BPQ Telnet socket, simply connect to
the :pk.TCPPORT:epk. value in the Telnet port configuration section:
:xmp.
% telnet 127.0.0.1 7300
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '¬&rbrk.'.
callsign&colon.n4ham
password:

Connected to MYBPQ&colon.WA4XYZ-8
Enter ? for list of commands

?
MYBPQ&colon.WA4XYZ-8} BBS CHAT SHELL CONNECT BYE INFO NODES PORTS ROUTES USERS MHEARD
bye
*** Disconnected from Stream 2
Connection closed by foreign host.
%
:exmp.
:p.All the same commands apply as shown in the :hp2.QtTermTCP:ehp2.
section above!
:h2.BPQCODE
:p.BPQCODE, otherwise just called the :hp2.BPQ Packet Engine,:ehp2. is
the aforementioned MS-DOS BPQ AX.25 stack. This provides basic
:hp1.NET/ROM:ehp1. support, and not much else.
:p.While BPQCODE does provide KISS interface support, it also supports
the :hp3.BPQETHER:ehp3. interface -- this was described in the Linux
AX.25 section. Do, however, note that BPQETHER requires the
installation of :hp1.an additional network stack!:ehp1.
:fn.This :hp1.additional network stack:ehp1. is the :hp5.Novell VLM
Client.:ehp5. This can be found by searching online (particulary on
archive.org) for :q.Novell LAN WorkPlace 5:eq. and installing that
alongside a supported Ethernet card driver. This installation is out of
the scope of this document.
:efn.
:h3.BPQETHER Prep (Novell VLM Client)
:p.If you do wish to use BPQETHER, you need to edit
 :pk.C&colon.\NWCLIENT\NET.CFG:epk. to resemble this:
:xmp keep=5.Link Support
        Buffers 8 1500
        MemPool 6144
        Max Boards 4
        Max Stacks 8

Link Driver NCOMX
        IRQ 4
        PORT 3f8

Link Driver PCNTNW
        Frame ETHERNET_802.3
        Frame ETHERNET_II
        PROTOCOL IPX 0 ETHERNET_802.3
        PROTOCOL BPQ 8FF ETHERNET_II
        PROTOCOL TCPIP 8137 ETHERNET_II

Protocol TCPIP
        PATH TCP_CFG C&colon.\NET\TCP
        ip_address 0.0.0.0 LAN_NET
        ip_netmask 255.255.255.0 LAN_NET
        ip_router 192.168.1.1 LAN_NET
        Bind PCNTNW #1 ETHERNET_II LAN_NET
        ip_address 0.0.0.0 PPP_NET
        Bind NCOMX #1 PPP PPP_NET

NWIP
        AUTORETRIES 1
        AUTORETRY SECS 10
        NSQ_BROADCAST ON
        NWIP1_1 COMPATIBILITY OFF

NetWare DOS Requester
        First Network Drive = F
        PREFERRED SERVER = HSNW4A

BPQPARAMS
        ETH_ADDR FF&colon.FF&colon.FF&colon.FF&colon.FF&colon.FF
:exmp.
:h3.Configuration
:p.Examine the following sample :pk.BPQCFG.TXT:epk. located in the
:hp5.same directory:ehp5. as :pk.BPQCODE.EXE:epk. and
:pk.BPQCFG.EXE:epk.:
:xmp keep=5.
HOSTINTERRUPT=127 ; Sets the Interrupt used to access BPQ Host Mode. Will
                  ; normally be 127, but may be changed if this clashes w
                  ; other software. BTRIEVE seems to use 127, so if you a
                  ; using it, try INTERRUPT=126
EMS=0             ; dont use EMS RAM
DESQVIEW=0

NODECALL=WX4XYZ-1 ; NODE CALLSIGN
NODEALIAS=BPQNOD
BBSCALL=WX4XYZ-2  ; BBS CALLSIGN
BBSALIAS=BPQBBS   ; BBS ALIAS

IDMSG:
Network node (BPQ1)
***

UNPROTO=CQ                    ; DEFAULT UNPROTO ADDR

INFOMSG:
G8BPQ Packet Switch
Commands are basically the same as NET/ROM, but to connect to another
normal station (not another node), you must specify a port number before
the callsign. Use PORTS command to list available ports. The BBS command
connects you to the associated Mailbox.
***

CTEXT:
Welcome to G8BPQ's Packet Switch in Nottingham
Type ? for list of available commands.
***

FULL_CTEXT=0                    ; SEND CTEXT ONLY TO L2 CONNECTEES TO ALI

OBSINIT=5                       ; INITIAL OBSOLESCENCE VALUE
OBSMIN=4                        ; MINIMUM TO BROADCAST
NODESINTERVAL=1                 ; 'NODES' INTERVAL IN MINS
IDINTERVAL=1                    ; 'ID' BROADCAST INTERVAL
BTINTERVAL=0                    ; NO BEACONS
L3TIMETOLIVE=25                 ; MAX L3 HOPS
L4RETRIES=3                     ; LEVEL 4 RETRY COUNT
L4TIMEOUT=120                   ; LEVEL 4 TIMEOUT
L4DELAY=10                      ; LEVEL 4 DELAYED ACK TIMER
L4WINDOW=4                      ; DEFAULT LEVEL 4 WINDOW
MAXLINKS=30                     ; MAX LEVEL 2 LINKS (UP,DOWN AND INTERNOD
MAXNODES=120                    ; MAX NODES IN SYSTEM
MAXROUTES=35                    ; MAX ADJACENT NODES
MAXCIRCUITS=64                  ; NUMBER OF L4 CIRCUITS
MINQUAL=10                      ; MINIMUM QUALITY TO ADD TO NODES TABLE
BBSQUAL=30                      ; BBS Quality relative to NODE - used to
                                ; limit 'spread' of BBS through the netwo
                                ; to your required service area. I've bee
                                ; asked to set a low default to encourage
                                ; to think about a suitable value. Max is
BUFFERS=255                     ; PACKET BUFFERS - 255 MEANS ALLOCATE AS
                                ; AS POSSIBLE - NORMALLY ABOUT 130, DEPEN
                                ; ON OTHER TABLE SIZES
PACLEN=120                      ; MAX PACKET SIZE DEFAULT
TRANSDELAY=1                    ; TRANSPARENT MODE SEND DELAY - 1 SEC

T3=180                          ; LINK VALIDATION TIMER (3 MINS)
IDLETIME=900                    ; IDLE LINK SHUTDOWN TIMER (15 MINS)

BBS=1                           ; INCLUDE BBS SUPPORT
NODE=1                          ; INCLUDE SWITCH SUPPORT

HIDENODES=0                     ; IF SET TO 1, NODES STARTING WITH # WILL
                                ; ONLY BE DISPLAYED BY A NODES * COMMAND

ENABLE_LINKED=Y                 ; CONTROLS PROCESSING OF *** LINKED COMMA
                                ; Y ALLOWS UNRESTRICTED USE
                                ; A ALLOWS USE BY APPLICATION PROGRAM
                                ; N (OR ANY OTHER VALUE) DISABLE
;TNCPORT
;        COM=1
;ENDPORT
;TNCPORT
;        COM=3
;        APPLFLAGS=4
;ENDPORT

PORT
        ID=ETHERNET
        TYPE=EXTERNAL
        PROTOCOL=KISS
        INTLEVEL=125
        SPEED=9600
        CHANNEL=A
        QUALITY=10
        MAXFRAME=7
        TXDELAY=500
        SLOTTIME=100
        PERSIST=64
        FULLDUP=0
        FRACK=7000
        RESPTIME=2000
        RETRIES=10
        PACLEN=256
ENDPORT


ROUTES:
***

APPLICATIONS=BBS,,*SYS,CHAT/C NMCHAT
:exmp.
:h3.Starting BPQCODE
:p.In order to properly start BPQCODE, you must run several programs
ahead of time:
:fn.If you are using the Novell VLM Client (i.e. LAN WorkPlace) at all,
start that ahead of time before running any part of BPQ
:efn.
:xmp.
C&colon.\BPQ> bpqcfg
C&colon.\BPQ> odidrv 125     <--- only if you are using BPQETHER
C&colon.\BPQ> bpqcode
:exmp.
:p.The :pk.ODIDRV:epk. command is part of the Novell VLM client.
However, not everything is ready.
:h3.Using BPQCODE
:p.Included in the BPQ package is a program named :pk.PAC4:epk., and it
is a stand-in for BPQTerm (Windows), BPQTermTCP, or QtTermTCP on modern
LinBPQ and BPQ32. This program communicates with BPQ by using the
interrupt vector specified with the :pk.HOSTINTERRUPT:epk. option
in :pk.BPQCFG.TXT:epk.
:p.Start that program:
:xmp.C&colon.\> pac4
:exmp.
:h1.XRouter
:p.Despite being closed-source,
:fn.There are several explanations for this, with the most popular one
being that :q.XRouter is a combination of BPQ, NOS, and TheNet:eq., but
the stated reason is that the package's author does not wish to use Git
:hp1.(which is a very valid reason).:ehp1.
:efn.
XRouter is probably the best packet radio stack on the market. It
features all manner of beautiful user interfaces, advanced protocol
support, and other such things. A short list of XRouter features
includes:
:ul.
:li.Full IPv4 support :hp1.(with NAT and RIP routing):ehp1.
:li.APRS support
:fn.:hp2.Note&colon.:ehp2. at the time of writing, exiting APRS client
mode will :hp5.crash:ehp5. XRouter!
:efn.
:li.FTP, SMTP, Finger, Telnet, and other TCP services
:li.INP3 (Inter-Node Protocol 3), a NET/ROM distance vector
determination protocol
:li.An advanced PBS and chat server
:li.Support for colored user interfaces everywhere
:fn.Your TNC needs to support this; this excludes every TNC with a
firmware ROM doing AX.25-noL3 processing
:efn.
:li.Feature-rich HTTP (web) server
:eul.
:h3.Versions
:p.There are several versions of XRouter:
:table cols='*  *'.
:tcap.XRouter Versions
:thd.
:c.:hp2.OS:ehp2.
:c.:hp2.Name:ehp2.
:ethd.
:row.
:c.XRWin
:c.32-bit Windows
:row.
:c.XRWin64
:c.64-bit Windows
:row.
:c.XRLin
:c.32-bit x86 Linux
:row.
:c.XRLin64
:c.64-bit x86 Linux
:row.
:c.XRPi
:c.32-bit ARM Linux
:row.
:c.XRPi64
:c.64-bit ARM Linux
:etable.
:p.For future reference, :hp3.the config file is common to all
versions,:ehp3. with some slight variations existing between the
editions -- these will be noted.
:h2.Installation
:p.After fetching a version of XRouter (please see :hdref refid=urls.
for locations) and documentation, start by noting the following files
that will eventually be in the installation directory (the same
directory that contains your XRouter executable):
:dl tsize=15.
:dt.:pk.DOMAIN.SYS:epk.
:dd.A BIND-compatible
:fn.:hp2.BIND:ehp2. is the :hp1.Berkeley Internet Name Daemon,:ehp1. a
very popular DNS server
:efn.
DNS zone file that maps hostnames to IP addresses
:dt.:pk.DXLIST.SYS:epk.
:dd.Stores most distant heard stations
:dt.:pk.HISTORY.SYS:epk.
:dd.Stores sysop command history (commands typed into the XRouter
console)
:dt.:pk.HTTP.SYS:epk.
:dd.Configures the web server's proxying and URL rewriting rules
:dt.:pk.IGATE.CFG:epk.
:dd.Configures the APRS I-Gate (will be described in great detail in
the APRS section)
:dt.:pk.IPROUTE.SYS:epk.
:dd.Configures static IP routes, NAT entries, RIP routing learning, and
ACLs
:dt.:pk.MHEARD.SYS:epk.
:dd.Stores commands for the :q.Monitor Heard:eq. list, i.e. a list of
heard stations
:dt.:pk.PASSWORD.SYS:epk.
:dd.Stores :hp1.sysop passwords:ehp1. for remote administration (mapped
to callsigns)
:dt.:pk.USERPASS.SYS:epk.
:dd.Stores passwords for general users (who can be promoted to sysops
by having a corresponding entry in the above file)
:dt.:pk.WXSAV.DAT:epk.
:dd.Stores APRS weather information from recently-heard weather beacons
:dt.:pk.XROUTER.CFG:epk.
:dd.Main XRouter configuration file
:dt.:pk.XROUTER.SYS:epk.
:dd.Contains commands to run at startup
:fn.Analogus to :pk.autoexec.net:epk. on JNOS
:efn.
:edl.
:h3.Tailoring the Main Configuration File
:p.XRouter's configuration is stored mostly in :pk.XROUTER.CFG:epk., so
start by editing that. Let us walk through this piece by piece:
:ol.
:li.Set the :hp2.node callsigns:ehp2. and :hp2.aliases:ehp2. (for
NET/ROM):
:p.
:xmp keep=5.
NODECALL=AA4XY-1
NODEALIAS=XR1
CONSOLECALL=AA4XY

CHATCALL=AA4XY-2
CHATALIAS=XR1CHT
CHATQUAL=150

PMSCALL=AA4XY-3
PMSALIAS=XR1PMS
PMSQUAL=150

APRSCALL=AA4XY-1
QTH=Nowhere, NW
LOCATOR=FN02AA
:exmp.
:p.The entries are as follows:
:dl tsize=15.
:dt.:pk.NODECALL:epk.
:dd.The base node callsign for :hp1.both:ehp1. AX.25-NoL3 and NET/ROM
connections
:fn.Of course, if you are talking to a :hp2.Linux:ehp2. node, ensure
that node has a unique AX.25-NoL3 and NET/ROM callsign if you wish to
use AX.25-NoL3 connections
:efn.
:dt.:pk.NODEALIAS:epk.
:dd.The NET/ROM alias for the base node
:dt.:pk.CONSOLECALL:epk.
:dd.The callsign used for :hp1.outbound:ehp1. connections from the
console
:dt.:pk.CHATCALL:epk.
:dd.The callsign for the chat server, accessible by routing through the
:pk.NODECALL:epk.
:dt.:pk.CHATALIAS:epk.
:dd.The NET/ROM alias for the chat server (which will automatically be
announced on nodes broadcasts)
:dt.:pk.CHATQUAL:epk.
:dd.The NET/ROM quality of the chat server node
:dt.:pk.PMSCALL:epk.
:dd.The callsign of the PMS, also accessible through the routing
technique
:dt.:pk.PMSALIAS:epk.
:dd.The NET/ROM alias of the PMS
:dt.:pk.PMSQUAL:epk.
:dd.The NET/ROM quality of the PMS node
:dt.:pk.APRSCALL:epk.
:dd.The APRS digipeater and node callsign (also used for the weather
station), can be shared with the :pk.NODECALL:epk.
:dt.:pk.QTH:epk.
:dd.The station QTH
:dt.:pk.LOCATOR:epk.
:dd.Maidenhead gridsquare locator of the station
:edl.
:li.Set the :hp2.node broadcast text, information text, and ID
text:ehp2.:
:p.
:xmp keep=5.
CTEXT
Welcome to the AA4XY Super Cool Packet Node!
Type ? for help.
***

INFOTEXT
This is an example packet radio configuration file for
XRouter, lifted from Evie's packet radio tutorial. Hams
who copy and paste this will notice that the 0 character
does not make it over. Please change this to something
suitable for your node and/or ham club!
***

IDTEXT
!3435.10N/08620.40WnAA4XY XRouter AX.25, TCP/IP, and NET/ROM
***
:exmp.
:p.The entries are as follows:
:dl tsize=15.
:dt.:pk.CTEXT:epk.
:dd.The text sent to a user when they connect
:dt.:pk.INFOTEXT:epk.
:dd.The text printed out by the :pk.info:epk. command
:dt.:pk.IDTEXT:epk.
:dd.The ID message, see the note in the box below
:edl.
:lblbox.A Note on the IDTEXT
:p.If your node wishes to be seen, heard, and processed by nearby
:hp3.APRS stations,:ehp3. enter an APRS broadcast just like that
example.
:p.The :pk./:epk. between the coordinates is the :hp5.group:ehp5., and
can be set to :pk.\:epk. for the secondary group. The :pk.n:epk.
selects the :hp5.symbol:ehp5., which alternates between primary and
secondary in conjunction with the aforementioned group character.
:p.If you are :hp3.not running APRS,:ehp3. just set it to a plain text
beacon.
:elblbox.
:li.Set the :hp2.IP address, hostname, DNS server, and set some tuning
parameters:ehp2.:
:p.
:xmp.
IPADDRESS=203.0.113.1
HOSTNAME=coolnode.aa4xy.radio
DNS=1.1.1.1
DCACHE=20
MAXARP=100
MAXTCP=100
IPIP=1
:exmp.
:p.These terms should be pretty self-explanatory. :pk.IPIP:epk. enables
XRouter to receive IPIP tunnel (protocol 94) datagrams directly from
the Linux host; in other words, it creates a raw socket on protocol 94
and listens.
:li.Configure :hp2.TCP ports:ehp2.:
:p.
:xmp keep=5.
ECHOPORT=7 0
DISCARDPORT=9 0
FTPPORT=21 0
TELNETPORT=23 7323
FINGERPORT=79 0
HTTPPORT=80 8080
TTYLINKPORT=87 0
RLOGINPORT=513 0
SOCKSPORT=0
APRSPORT=1448 7448
TELPROXYPORT=2323 0
CHATPORT=3600 3600
AGWPORT=8000 0
:exmp.
:p.The first number is the port for the :hp2.XRouter TCP/IP stack:ehp2.
and the second number will :hp2.listen on the host.:ehp2. The services
are as follows:
:dl tsize=15.
:dt.:pk.ECHO:epk.
:dd.Simple TCP/IP echo service
:dt.:pk.DISCARD:epk.
:dd.Simple TCP/IP discard service
:dt.:pk.FTP:epk.
:dd.FTP server (file transfer)
:dt.:pk.TELNET:epk.
:dd.Telnet server (remote access)
:dt.:pk.FINGER:epk.
:dd.Finger server (lists user sessions)
:dt.:pk.HTTP:epk.
:dd.Web server
:dt.:pk.TTYLINK:epk.
:dd.Server for direct chat between two TCP/IP hosts
:dt.:pk.RLOGIN:epk.
:dd.Rlogin server (remote access)
:dt.:pk.SOCKS:epk.
:dd.SOCKS proxy service
:dt.:pk.APRS:epk.
:dd.APRS-IS server emulator (for APRS clients)
:dt.:pk.TELPROXY:epk.
:dd.Telnet proxy server
:dt.:pk.CHAT:epk.
:dd.Direct access to the chat server
:dt.:pk.AGW:epk.
:dd.Emulation of the AGW Packet Engine, which many programs can use
:edl.
:li.Set some console settings for :hp2.monitoring:ehp2.:
:p.
:xmp.
NUMCONSOLES=3
MMASK=0FFF
MPORTS=ALL
:exmp.
:p.:pk.NUMCONSOLES:epk. sets the :hp5.virtual consoles:ehp5. present on
the XRouter program; :pk.MMASK:epk. is the :hp5.monitor mask:ehp5. of
packets and protocols to monitor/trace, and :pk.MPORTS:epk. sets the
:hp5.monitor ports:ehp5. that you are allowed to trace on.
:li.If you are using the :hp3.APRS I-Gate:ehp3., enable it and set the
UI frame parameters for APRS:
:p.
:xmp.IGATE=1
UITRACE=WIDE
UIFLOOD=AL
:exmp.
:dl tsize=15.
:dt.:pk.UITRACE:epk.
:dd.Configures the destination for the :q.New-N:eq. digipeating method,
and is normally set to :pk.WIDE:epk.
:fn.This is the APRS digipeating technique wherein the :pk.WIDEn-n:epk.
(eg :pk.WIDE2-1:epk.) digipeater callsign slot fields in the AX.25
packet are consumed and replaced by the digipeating station's callsign
:efn.
:dt.:pk.UIFLOOD:epk.
:dd.An alternate APRS digipeating method, usually set to a state code;
for Alabama, set it to :pk.AL:epk.
:p.:hp1.Note: the UIFLOOD and UITRACE digipeaters are enabled by
setting DIGIFLAG correctly in the port configuration group:ehp1.
:edl.
:li.Set some :hp2.NET/ROM and AX.25:ehp2. parameters:
:p.
:xmp keep=5.
L4TIMEOUT=90
L4DELAY=10
L4WINDOW=4
L4RETRIES=3
MAXCIRCUITS=25
OBSINIT=5
OBSMIN=3
NODESINTERVAL=5
L3TTL=25
HIDENODES=0
MINQUAL=1
MAXNODES=250
SORTBYCALL=0
MAXROUTES=35
T3=180
IDLETIME=300
IDINTERVAL=10
:exmp.
:p.These are as follows:
:dl tsize=15.
:dt.:pk.L4TIMEOUT:epk.
:dd.NET/ROM layer 4 timeout before dropping a connection
:dt.:pk.L4DELAY:epk.
:dd.NET/ROM delay to prevent excessive packet sending
:fn.Set to :pk.0:epk. or some other such low value on wireline links or
AX/IP/UDP tunnels; this can be overrided in the :pk.PORT:epk. block
:efn.
:dt.:pk.L4WINDOW:epk.
:dd.NET/ROM window size
:dt.:pk.L4RETRIES:epk.
:dd.NET/ROM connection restoration attempts before giving up
:dt.:pk.MAXCIRCUITS:epk.
:dd.Maximum number of AX.25 connections that prop up NET/ROM
links
:dt.:pk.OBSINIT:epk.
:dd.NET/ROM obsolecence value, computed using a formula
:dt.:pk.OBSMIN:epk.
:dd.NET/ROM minimum obsolecence value
:dt.:pk.NODESINTERVAL:epk.
:dd.How often (in minutes) to emit a NET/ROM nodes routing table
broadcast
:dt.:pk.L3TTL:epk.
:dd.Time-to-live for L3 (NET/ROM network layer) packets
:dt.:pk.HIDENODES:epk.
:dd.Hide NET/ROM nodes starting with :pk.#:epk. in the nodes list
:dt.:pk.MINQUAL:epk.
:dd.Minimum quality number of a NET/ROM node to be included in the
routing table
:dt.:pk.MAXNODES:epk.
:dd.Maximum number of NET/ROM nodes to hold
:dt.:pk.SORTBYCALL:epk.
:dd.Sort the nodes table by the AX.25 callsign, rather than the NET/ROM
node alias name
:dt.:pk.MAXROUTES:epk.
:dd.Maximum number of AX.25 routes to hold
:dt.:pk.T3:epk.
:dd.AX.25 aliveness test timer in seconds, which :hp5.removes stale
links:ehp5.
:dt.:pk.IDLETIME:epk.
:dd.How long in seconds before an AX.25 tunnel carrying NET/ROM packets
is closed
:dt.:pk.IDINTERVAL:epk.
:dd.How often to emit the :pk.IDTEXT:epk. defined earlier
:edl.
:li.If you want to :hp3.log the console output:ehp3., enable that:
:p.
:xmp.LOG=1
:exmp.
:li.
:eol.
:h2.Port and Interface Configuration
:p.Very similar to BPQ, XRouter requires you to have at least one
:pk.PORT:epk. and :pk.INTERFACE:epk. block pair.
:h3.Interfaces
:p.The interfaces come first. These are as follows:
:ul.
:li.:pk.ASCII:epk. = serial port terminals with the XRouter command
line
:li.:pk.ETHER:epk. = Ethernet LAN interfacing with :pk.libpcap:epk.
:fn.This requires that you downloaded a version of XRouter built with
:pk.libpcap:epk. support, and you must run it either as root
:hp1.or:ehp1. give it the process capability for unfiltered network
access: :pk.setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip' xrlin:epk.
:efn.
:li.:pk.HDLC:epk. = YAM modem interface
:li.:pk.KISS:epk. = KISS TNCs or wireline links to other packet stacks
:li.:pk.MODEM:epk. = Hayes command set compatible dialup modems
:fn.As in, modems that have commands that start with :pk.AT:epk.
:efn.
:li.:pk.NETROM:epk. = NET/ROM backend interface or an old NET/ROM TNC
:li.:pk.PPP:epk. = PPP (Point-to-Point Protocol) for IP links over
serial cables
:li.:pk.SLIP:epk. = SLIP (Serial Line IP) for Berkley UNIX-compatible
serial connections (started on UNIX using the :pk.slattach:epk.
command)
:li.:pk.TNC2:epk. = TNC2 shell emulation on a serial port
:eul.
:p.Here is an example of one of each:
:h4.Internal Loopback
:p.This is the equivalent of the loopback device on a UNIX TCP/IP
stack:
:xmp.
INTERFACE=1
        TYPE=LOOPBACK
        PROTOCOL=KISS
        MTU=576
ENDINTERFACE
:exmp.
:p.The protocol used here is :hp2.KISS:ehp2., as it will need to speak
:hp1.any:ehp1. protocol.
:h4.KISS Serial Port TNC
:p.:hp1.Note: also for wireline KISS links between packet stacks:ehp1.
:p.You will need to put your TNC into KISS mode :hp1.before:ehp1.
starting XRouter.
:xmp.
INTERFACE=2
        TYPE=ASYNC
        COM=COM1
        SPEED=9600
        PROTOCOL=KISS
        KISSOPTIONS=NONE
        MTU=256
ENDINTERFACE
:exmp.
:p.For Windows systems, enter the COM port device name like
:pk.COM1:epk.; for Linux, specify the device node like
:pk./dev/ttyS2:epk..
:p.If the TNC uses the :hp2.BPQKISS:ehp2. protocol, you need to alter
that :pk.KISSOPTIONS:epk. parameter:
:xmp.
INTERFACE=2
        TYPE=ASYNC
        COM=COM1
        SPEED=9600
        PROTOCOL=KISS
        KISSOPTIONS=POLLED,CHECKSUM,ACKMODE
        MTU=256
ENDINTERFACE
:exmp.
:p.There are some other options that can be added:
:dl tsize=15.
:dt.:pk.FLOW:epk.
:dd.Serial port flow control; :pk.0:epk. = no flow control, :pk.1:epk.
= hardware (i.e. RTS/CTS pins) flow control, :pk.2:epk. = software
(i.e. XON/XOFF) flow control, :pk.3:epk. = both hardware and softwrae
flow control
:dt.:pk.KISSOPTIONS:epk.
:dd.Described in the example above. :pk.NONE:epk. is for a plain TNC,
:pk.POLLED:epk. is for a TNC that will only send data when sent a poll
command, :pk.CHECKSUM:epk. is for TNCs that support checksummed frames
:hp2.(like Dire Wolf):ehp2., :pk.ACKMODE:epk. is for TNCs that send a
:q.bounceback:eq. byte when the packet is sent, and :pk.SLAVE:epk. is
the inverse of polled mode.
:fn.This is for null-modem serial port KISS connections or KISS
connections over a leased-line modem
:efn.
:edl.
:h4.WA8DED Host-Mode Serial Port TNC
:p.This is a non-KISS TNC:
:xmp.
INTERFACE=3
        TYPE=ASYNC
        COM=COM1
        SPEED=9600
        PROTOCOL=DEDHOST
        FLOW=0
        CHANNELS=4
        MTU=256
ENDINTERFACE
:exmp.
:h4.YAM Serial Port TNC
:p.It is unlikely this will work straight away in this modern age, but
this entry is provided for completeless:
:xmp.
INTERFACE=4
        TYPE=YAM
        COM=COM1
        SPEED=9600
        PROTOCOL=HDLC
        MTU=256
ENDINTERFACE
:exmp.
:h4.NET/ROM Switch Serial Interface
:p.This permits communication with a traditional :hp1.NET/ROM
TNC:ehp1., or a null-modem serial cable to another NET/ROM switch port:
:xmp.
INTERFACE=4
        TYPE=ASYNC
        COM=COM1
        SPEED=19200
        PROTOCOL=NETROM
        MTU=256
ENDINTERFACE
:exmp.
:h4.XRouter as a TNC2 Emulation
:p.This simulates the user interface of a standard TNC2, with the
:pk.cmd&colon.:epk. prompt and all the associated commands:
:xmp.
INTERFACE=5
        TYPE=ASYNC
        COM=COM1
        SPEED=9600
        PROTOCOL=TNC2
        MTU=256
ENDINTERFACE
:exmp.
:h4.XRouter Shell on Serial Terminal
:p.This provides a timesharing-like interface such that several serial
terminals can be presented with an XRouter command line (also uses
software flow control):
:xmp.
INTERFACE=5
        TYPE=ASYNC
        COM=COM1
        SPEED=19200
        FLOW=2
        PROTOCOL=ASCII
        MTU=256
ENDINTERFACE
:exmp.
:h4.SLIP Serial Port Interface
:p.This provides a :hp5.Serial Line IP:ehp5. interface without the aid
of a dial-up modem; this is a wireline connection with a null-modem
connection.
:xmp.
INTERFACE=6
        TYPE=ASYNC
        COM=COM1
        SPEED=9600
        PROTOCOL=SLIP
        FLOW=0
        MTU=1500
ENDINTERFACE
:exmp.
:h4.PPP Serial Port Interface
:p.This configures a PPP interface that supports LCP, IPCP, and IPv4.
:xmp.
INTERFACE=6
        TYPE=ASYNC
        COM=COM1
        SPEED=9600
        PROTOCOL=PPP
        FLOW=0
        MTU=1500
ENDINTERFACE
:exmp.
:h4.Ethernet LAN Interface
:p.This allows XRouter to hook into a LAN with the :pk.libpcap:epk.
library; note that this is for :hp2.actual Ethernet card
interfaces:ehp2. and :hp1.NOT:ehp1. tun/tap devices!
:xmp.
INTERFACE=7
        TYPE=EXTERNAL
        PROTOCOL=ETHERNET
        ID=eth0
        MTU=1500
ENDINTERFACE
:exmp.
:h4.AXIP Tunnel Interface
:p.Nice and simple, because all the configuration comes later in the
:pk.PORT:epk. block:
:xmp.
INTERFACE=3
        TYPE=AXIP
        MTU=1300
ENDINTERFACE
:exmp.
:h4.AXUDP Tunnel Interface
:p.Just like the AXIP interface:
:xmp.
INTERFACE=3
        TYPE=AXUDP
        MTU=1300
ENDINTERFACE
:exmp.
:h4.AXTCP Server Interface
:p.To accept AX.25-over-TCP connections from remote systems:
:xmp.
INTERFACE=4
        TYPE=AXTCP
        MTU=1300
        INTNUM=9393
ENDINTERFACE
:exmp.
:p.:pk.INTNUM:epk. is the port to listen on.
:h4.AXTCP Client Interface
:p.For calling out to remote AXTCP sockets:
:xmp.
INTERFACE=5
        TYPE=AXTCP
        MTU=1300
        CONFIG=XR1 1.2.3.4 9393
ENDINTERFACE
:exmp.
:p.:pk.CONFIG:epk. has three fields:
:ol.
:li.The remote node name
:li.The IP address or hostname of the remote server
:li.The remote port (corresponding to :pk.INTNUM:epk.)
:eol.
:h4.AGWPE over TCP
:p.This allows XRouter to use either :hp2.AGW Packet Engine:ehp2. or
:hp2.Dire Wolf:ehp2.:
:xmp.
INTERFACE=6
        TYPE=AGW
        MTU=256
        IOADDR=127.0.0.1
        INTNUM=8000
        CONFIG=agwpasswordhere
ENDINTERFACE
:exmp.
:p.These fields are:
:dl tsize=15.
:dt.:pk.IOADDR:epk.
:dd.The IP address of the machine running AGWPE, which will be called
out to from the host's TCP/IP stack
:dt.:pk.INTNUM:epk.
:dd.The port of the AGW server, usually 8000 for AGWPE and Dire Wolf
:dt.:pk.CONFIG:epk.
:dd.The AGW password, :hp5.not necessary for Dire Wolf:ehp5.
:edl.
:h3.Ports
:p.Interfaces are associated with :hp3.ports,:ehp3. of which several
can be defined on one interface. Here are some examples:
:h1.Meshtastic
:p.Meshtastic is a :hp2.non-AX.25 packet protocol.:ehp2. Based on the
:hp5.LoRa protocol,:ehp5. Meshtastic offers a simple and non-networked
protocol that is remarkably similar to APRS is; the major difference
between the two is that AX.25 is the underlying network protocol that
carries APRS, whereas LoRa itself is the underlying protocol that
carries Meshtastic.
:fn.It should be noted that :q.LoRa:eq. is a catch-all for
:hp1.several:ehp1. protocols: the physical layer and the MAC layer (and
sometimes the application layer).
:efn.
:h2.The LoRa Protocol
:p.LoRa, short for :hp1.Long Range:ehp1., is an ISM-band based protocol
that is intended to provide excellent range (compared to other
modulation modes, like AX.25's Bell 103 modem) for the amount of
transmit power used (which, as one might imagine being on an ISM band,
is in the milliwatts).
:fn.While I said LoRa is intended to be ran on the ISM bands, some
amateur radio operators have actually ran LoRa on HF using a
:hp1.transverter:ehp1. to downconvert the 433 MHz signals to HF.
:efn.
:h3.ISM Bands
:p.ISM is short for :hp1.Industrial, Scientific, and Medical;:ehp1.
these are radio bands intended for various devices of the same name.
They are not intended for radio communication, but can be provided that
the power is under a certain threshold.
:fn.Note that this guide is very USA-centric, and this rule :hp1.may
not apply:ehp1. in some other countries!
:efn.
:p.For reference, here are most of the ISM bands in the USA:
:table cols='* * *'.
:tcap.US ISM Bands
:thd.
:c.:hp2.Start:ehp2.
:c.:hp2.End:ehp2.
:c.:hp2.Notes:ehp2.
:ethd.
:row.
:c.13.553 MHz
:c.13.567 MHz
:c.22-meter band, some run beacons here
:row.
:c.26.957 MHz
:c.27.283 MHz
:c.CB radio
:row.
:c.40.66 MHz
:c.40.7 MHz
:c.6-meter band, an amateur band in some places that aren't
the US
:row.
:c.433.05 MHz
:c.434.79 MHz
:c.Region 1 70-centimeter ISM band, shared with an amateur band
:row.
:c.902 MHz
:c.928 MHz
:c.33-centimeter band, an amateur band in the US
:row.
:c.2.4 GHz
:c.2.5 GHz
:c.13-centimeter band, commonly used for Wi-Fi and microwave
ovens
:row.
:c.5.725 GHz
:c.5.875 GHz
:c.5-centimeter band, commonly used for newer Wi-Fi systems
:etable.
:p.There are some other bands, but they have been omitted for brevity.
:h3.LoRa CSS Modulation
:p.The LoRa protocol uses the :hp2.chirp spread-spectrum:ehp2.
modulation mode, wherein a carrier shifts in frequency within a certain
bandwidth over a certain timeframe; the faster the shift, the more
bandwidth is required as per a trade-off between bandwidth and SNR.
:p.LoRa also has a :hp2.spreading factor:ehp2.
:fn.Abbreviated :hp2.SF:ehp2.
:efn.
that ranges 5 to 12 -- it controls how many bits are sent per each
symbol and the bandwidth that each transmission will take. Like many
other modems, LoRa allows the aforementioned SNR tradeoff wherein the
data rate can increase at the expense of signal integrity.
:p.LoRa also implements a :hp2.forward error correction:ehp2. scheme to
pre-emptively guard against various interference issues on the
receiving station. Since the transmit power is so low (usually limited
to +22 dBm), this error-correction scheme is paramount; with all of
this, LoRa can still manage a link distance of about 3 miles in urban
areas, and about 10 miles in rural areas (provided that there are no
obvious obstructions along those paths).
:h3.LoRa Packet Format
:p.For visual continence, the LoRa packet structure is as follows:
:fig width=column place=inline frame=none.
:artwork name=prlora align=center.
:figcap.LoRa Frame Format
:efig.
:h2.Meshtastic Protocol Introduction
:p.Meshtastic has been around since 2020, and was designed by Kevin
Hester. Like APRS, Meshtastic is a terrifically simple protocol. Rather
than provide a protocol analogous to NET/ROM, Meshtastic is a simple
per-note-repeating protocol; as such, Meshtastic would need to address
the following issues:
:ol.
:li.High node battery consumption due to constant packet reception and
processing on behalf of the nodes in the network
:li.Excessive retransmissions which would end up filling all of the
available transmission timeslots
:li.Infinite packet retransmission would cause a jamming of the entire
network
:eol.
:p.As such, the Meshtastic protocol needed to do several things to
address those issues:
:ul.
:li.Set the LoRa packet preamble to be as long as possible such that
the node can sleep while listening for packets (and wake up just in
time to decode the packet)
:li.Listen before transmitting, in the same way that most AX.25 TNCs
do, to prevent packet collisions or other such classical network design
issues
:li.Understand and rank the distance of received packets to control who
gets digipeated first
:li.If a packet has been digipeated too many times, don't digipeat it
:fn.7 is the colloquial maximum number of hops on a Meshtastic network,
and this can result in upwards of 150 km of coverage in areas with
reasonably-spaced nodes
:efn.
:li.Do not retransmit a packet that has already been digipeated unless
you were the one to originate it
:eul.
:p.Meshtastic functions at the :hp2.application layer:ehp2. of the LoRa
network stack.
:h1.Alternate Packet Modems
:h2.VARA HF/VHF/SAT
:p.While the standard Bell 102/103 and G3RUH/KN9G AX.25 physical layer
modems are rather popular, they simply do not offer very good
performance in the modern age. EA5HVK created :hp2.VARA:ehp2. as a
successor to the aforementioned modems (and, more importantly, their
shortcomings.
:p.VARA has one key feature that sets it apart from the traditional
packet TNCs and softmodems: :hp1.it can dynamically vary its speed with
band conditions.:ehp1. This is especially useful on HF, where band
conditions could result in a rapidly-fluttering signal that would be
totally unusable by traditional packet modems. VARA will detect this
and :hp5.vary its speed:ehp5. to compensate.
:p.At the time of writing, there are three versions of VARA:
:ol.
:li.:hp2.VARA HF:ehp2., for HF communications within a 3000 Hz window
:fn.This is the globally-accepted :q.standard:eq. for HF signal
bandwidth on the amateur bands
:efn.
:li.:hp2.VARA FM:ehp2., intended for use in place of traditional FM
packet TNCs, and is capable of hitting several kilobaud with a good
radio
:fn.See the coming note on :q.VARA FM Wide:eq. to understand this
:efn.
:li.:hp2.VARA SAT:ehp2., intended for use on the QO-100 geostationary
satellite
:eol.
:p.VARA is a Windows-only program, written in Visual Basic 5.
Furthermore, it features rather draconian copy protection (with an
encrypted code segment that is decrypted at runtime).
:p.TODO
:h2.ARDOP
:p.TODO
:h2.FreeDATA (Codec2)
:p.TODO
:h2.fldigi
:p.TODO
:appendix.
:h3 id=urls.Web Locations of Packet Radio Software
:p.JNOS 2.0, Mainline
:xmp.$ rsync -a www.langelaar.net&colon.&colon.official jnos
:exmp.
:p.JNOS 2.0 Help Files
:xmp.http&colon.//hamgate.ampr.org/docs/_JNOS_help_files
:exmp.
:p.JNOS 2.0, FreeBSD Port
:xmp.https&colon.//github.com/HackerSmacker/jnos-freebsd
:exmp.
:p.Linux AX.25 Programs
:xmp.Wiki: https&colon.//linux-ax25.in-berlin.de/wiki/Main_Page
ax25-apps: https&colon.//linux-ax25.in-berlin.de/cgit/ax25-apps.git
ax25-tools: https&colon.//linux-ax25.in-berlin.de/cgit/ax25-tools.git
libax25: https:/&colon.linux-ax25.in-berlin.de/cgit/libax25.git
:exmp.
:p.BPQ Packet Engine, Mainline
:xmp.https&colon.//github.com/g8bpq/linbpq
:exmp.
:p.BPQ Packet Engine, FreeBSD Port
:xmp.https&colon.//github.com/HackerSmacker/g8bpq-bsd
:exmp.
:p.:pk.aprx:epk. for Linux
:xmp.https&colon.//github.com/PhirePhly/aprx
:exmp.
:backm.
:glossary.Glossary
:gl.
:grpsep.C
:gt.Constellation Diagram
:gd.A diagram that displays amplitude and phase for various digital
modulation modes, including PSK and QAM.
:gt.CSS
:gd.Chirp Spread-Spectrum, a modulation mode often used for ISM band
devices
:grpsep.I
:gt.ISM Band
:gd.Various unlicensed radio bands that permit some amount of transmit
power, but barely any; almost all of them (except for the 40 MHz band
in most countries) overlap amateur radio bands.
:grpsep.L
:gt.LoRa
:gd.:q.Long Range:eq., a CSS modulation mode with very good SNR
:grpsep.O
:gt.OSI Model
:gd.A reference model for a network stack also called the OSI Stack,
which is often applied to other protocols. The layers are physical,
data-link, network, transport, session, presentation, application
:grpsep.P
:gt.PSK
:gd.:q.Phase-Shift Keying:eq., a data modulation mode in which the
phase of the signal is modulated
:grpsep.Q
:gt.QAM
:gd.:q.Quadrature Amplitude Modulation:eq., a data modulation mode
where the amplitude and phase of the modulated analog waveform is varied
:grpsep.S
:gt.SNR
:gd.:q.Signal-to-Noise Ratio:eq., a ratio of the signal strength to the
noise strength
:egl.
:index.
:euserdoc.
