#include "geist/boo.hpp"
#include "geist/detail/internal.hpp"
#include "geist/detail/message_prose_rows.hpp"
#include "test_failures.hpp"

#include <algorithm>
#include <filesystem>
#include <iostream>
#include <string>
#include <vector>

namespace {

void require(bool condition, const std::string &message) {
  if (!condition) {
    std::cerr << "message_prose_rows: " << message << '\n';
    geist_test::record_failure();
  }
}

void open_context(const std::filesystem::path &path,
                  geist::detail::LogicalDecodeContext &context) {
  context.bytes = geist::detail::read_file(path);
  const auto directory_page = geist::detail::read_be16(context.bytes, 0);
  const auto base =
      static_cast<std::size_t>(directory_page) * geist::boo_page_size;
  context.directory.page_number = directory_page;
  context.directory.token_threshold = context.bytes[base + 0x14];
  context.directory.token_map_offset =
      geist::detail::read_be16(context.bytes, base + 0x22);
  context.directory.dictionary_start_page =
      geist::detail::read_be16(context.bytes, base + 0x28);
  context.directory.dictionary_page_count =
      geist::detail::read_be16(context.bytes, base + 0x2e);
  context.directory.logical_record_count =
      geist::detail::read_be16(context.bytes, base + 0x36);
  context.directory.content_page_count =
      geist::detail::read_be16(context.bytes, base + 0x38);
  context.directory.content_start_page =
      geist::detail::read_be16(context.bytes, base + 0x3a);
  context.decoded_records = geist::detail::decode_experimental_logical_records(
      context.bytes, context.directory, &context.record_payload_ranges);
}

const geist::detail::MessageProseRowJoinIR *
find_join(const std::vector<geist::detail::MessageProseRowJoinIR> &joins,
          std::uint32_t logical_record, std::size_t token_begin) {
  const auto found = std::find_if(joins.begin(), joins.end(), [&](const auto &join) {
    return join.source.logical_record == logical_record &&
           join.source.token_begin == token_begin;
  });
  return found == joins.end() ? nullptr : &*found;
}

// Typed trap catalogs render through DocumentIR, which escapes Markdown
// punctuation; the rendered-text checks compare the visible text.
std::string visible_text(const std::string &markdown) {
  std::string visible;
  visible.reserve(markdown.size());
  for (std::size_t index = 0; index < markdown.size(); ++index) {
    if (markdown[index] == '\\' && index + 1 < markdown.size())
      visible.push_back(markdown[++index]);
    else
      visible.push_back(markdown[index]);
  }
  return visible;
}

bool starts_with(const std::string &text, const std::string &prefix) {
  return text.compare(0, prefix.size(), prefix) == 0;
}

bool ends_with(const std::string &text, const std::string &suffix) {
  return text.size() >= suffix.size() &&
         text.compare(text.size() - suffix.size(), suffix.size(), suffix) == 0;
}

} // namespace

int main() {
  const auto root = std::filesystem::path(GEIST_REPO_ROOT) / "BOO";
  geist::detail::LogicalDecodeContext context;
  open_context(root / "SC31-711.boo", context);

  // SC31-711 4.1.3 "LNM OS/2 Agent Traps": logical records 104-127.
  {
    const auto sources =
        geist::detail::decode_logical_record_sources(context, 104, 128);
    std::string error;
    const auto prose =
        geist::detail::build_message_prose_source_ir(sources, &error);
    require(prose.has_value(), "4.1.3 prose source rejected: " + error);
    if (!prose) return 1;
    require(prose->introduction.has_value(),
            "4.1.3 introduction rejected: " + prose->introduction_rejection);
    if (prose->introduction) {
      const auto &paragraphs = prose->introduction->paragraphs;
      require(paragraphs.size() == 4,
              "4.1.3 introduction paragraph count: " +
                  std::to_string(paragraphs.size()) + "\n" +
                  geist::detail::format_message_prose_introduction_ir(
                      *prose->introduction));
      if (paragraphs.size() == 4) {
        require(starts_with(paragraphs[0].text,
                            "Note: These traps correspond to the DFIPD "
                            "messages that are generated by the LNM OS/2 "
                            "agent program and have the same number. You can "
                            "look up a trap in the Messages chapter") &&
                    ends_with(paragraphs[0].text,
                              "error code descriptions and possible "
                              "corrective actions."),
                "4.1.3 note paragraph text: " + paragraphs[0].text);
        require(paragraphs[0].opened_by_run_start &&
                    paragraphs[0].opening_boundary.empty(),
                "4.1.3 note paragraph opens the CFONT run");
        require(starts_with(paragraphs[1].text,
                            "When the LNM for AIX Response indicates that the "
                            "status will be set to a particular setting") &&
                    paragraphs[1].text.find(
                        "For example, if the LNM for AIX Response indicates "
                        "to set the status to marginal and it is currently "
                        "in a critical state") != std::string::npos &&
                    ends_with(paragraphs[1].text,
                              "a response that indicates to set the status "
                              "to normal may be overriden by the state of "
                              "another resource."),
                "4.1.3 status paragraph text: " + paragraphs[1].text);
        // The inline paragraph gap after "actions." is proven by the
        // control-only spacing token LR104:177 inside the '?' wrapped row.
        require(paragraphs[1].opening_boundary.size() == 1 &&
                    paragraphs[1].opening_boundary[0].logical_record == 104 &&
                    paragraphs[1].opening_boundary[0].token_index == 177 &&
                    !paragraphs[1].opened_by_run_start,
                "4.1.3 status paragraph boundary provenance");
        require(paragraphs[2].text ==
                    "The traps in this section are defined under the "
                    "1.3.6.1.4.1.2.6.20 enterprise ID, which is associated "
                    "with LNM OS/2 agent.",
                "4.1.3 agent enterprise paragraph text: " +
                    paragraphs[2].text);
        // LR105 tokens 7-8 are `.` with spacing prefix 1 and the control-only
        // attach token: Format/markup.md signature B before the `as` marker
        // slot at the three-space origin.
        require(paragraphs[2].opening_boundary.size() == 1 &&
                    paragraphs[2].opening_boundary.front().logical_record ==
                        105 &&
                    paragraphs[2].opening_boundary.front().token_index == 8 &&
                    paragraphs[2].opening_boundary.front().spacing_control == 1 &&
                    paragraphs[2].opening_boundary.front().bytes.begin ==
                        0x10da7 &&
                    paragraphs[2].opening_boundary.front().bytes.end ==
                        0x10da8,
                "4.1.3 agent enterprise paragraph boundary provenance");
        require(paragraphs[3].text ==
                    "The redirected traps are defined under the "
                    "1.3.6.1.4.1.2.6.21.1.1 enterprise ID, which is "
                    "associated with LNM for AIX.",
                "4.1.3 redirected enterprise paragraph text: " +
                    paragraphs[3].text);
        require(paragraphs[3].opening_boundary.size() == 1 &&
                    paragraphs[3].opening_boundary[0].logical_record == 105 &&
                    paragraphs[3].opening_boundary[0].token_index == 62,
                "4.1.3 redirected enterprise paragraph boundary provenance");
        // The continuation prefix of LR105 belongs to the open paragraph.
        require(std::any_of(paragraphs[1].source_slices.begin(),
                            paragraphs[1].source_slices.end(),
                            [](const auto &slice) {
                              return slice.logical_record == 105 &&
                                     slice.token_begin == 0;
                            }),
                "4.1.3 LR105 continuation prefix provenance");
      }
      const auto rendered = geist::detail::render_message_prose_introduction_gml(
          sources, prose->layout, *prose->introduction);
      require(rendered.size() == 4 &&
                  starts_with(rendered[0], ":p.:hp2.Note::ehp2. These traps"),
              "4.1.3 introduction GML applies the CFONT highlight span");
    }

    // Record-continuation rows without a spacing boundary are soft wraps.
    const auto *backup_path = find_join(prose->joins, 119, 0);
    require(backup_path != nullptr &&
                backup_path->start ==
                    geist::detail::PhysicalRowStartKind::record_continuation &&
                backup_path->previous_visible_text ==
                    "The status of the segment is not changed to normal "
                    "because," &&
                backup_path->visible_text ==
                    "although the backup path has been recovered, the "
                    "segment is still wrapped.",
            "4.1.3 message 329 continuation join");
    const auto *port = find_join(prose->joins, 122, 0);
    require(port != nullptr && port->visible_text == "port" &&
                port->previous_visible_text ==
                    "Issue run commands to get status of module and",
            "4.1.3 message 444 continuation join");
    // The LR105 row after the control-only boundary tokens 7-8 must not be
    // typed as a join even though LayoutIR continues its display run.
    require(find_join(prose->joins, 105, 9) == nullptr,
            "4.1.3 paragraph boundary row was typed as a soft wrap");
    // `correlation` is a width-1 dictionary marker at a six-space origin in
    // every "Add correlation information" response row (LR106 token 162 is
    // message 101, LR110 token 101 is message 180).
    for (const auto &[record, token] :
         std::vector<std::pair<std::uint32_t, std::size_t>>{{106, 162},
                                                             {110, 101}}) {
      const auto found = std::find_if(
          prose->lexical_markers.begin(), prose->lexical_markers.end(),
          [&, record = record, token = token](const auto &marker) {
            return marker.source.logical_record == record &&
                   marker.source.token_begin == token;
          });
      require(found != prose->lexical_markers.end() &&
                  found->marker.decoded_text == "correlation" &&
                  found->marker.encoded_value == 56 &&
                  found->previous_visible_text == "Add" &&
                  found->visible_text ==
                      "information and return to AIX NetView/6000.",
              "4.1.3 lexical marker provenance for LR" +
                  std::to_string(record));
    }
  }

  // SC31-711 4.4 "FDDI SNMP Proxy Agent Traps": logical records 152-172.
  {
    const auto sources =
        geist::detail::decode_logical_record_sources(context, 152, 173);
    std::string error;
    const auto prose =
        geist::detail::build_message_prose_source_ir(sources, &error);
    require(prose.has_value(), "4.4 prose source rejected: " + error);
    if (!prose) return 1;
    const auto *resource_name = find_join(prose->joins, 152, 265);
    require(resource_name != nullptr &&
                resource_name->start ==
                    geist::detail::PhysicalRowStartKind::placeholder_wrap &&
                resource_name->marker && resource_name->marker->encoded_value == 5 &&
                resource_name->previous_visible_text ==
                    "Forward to AIX NetView/6000" &&
                resource_name->visible_text == "with resource name.",
            "4.4 message 1 placeholder-wrap join");
    const auto *loader = find_join(prose->joins, 153, 0);
    require(loader != nullptr &&
                loader->start ==
                    geist::detail::PhysicalRowStartKind::record_continuation &&
                loader->previous_visible_text ==
                    "This trap is generated when an no response has been "
                    "received" &&
                loader->visible_text ==
                    "from an Remote Program Upload (RPU) Loader",
            "4.4 message 2 record-continuation join");

    const auto was = std::find_if(
        prose->lexical_markers.begin(), prose->lexical_markers.end(),
        [](const auto &marker) {
          return marker.source.logical_record == 153 &&
                 marker.source.token_begin == 295;
        });
    require(was != prose->lexical_markers.end() &&
                was->marker.decoded_text == "was" &&
                was->marker.encoded_value == 125 &&
                was->visible_text == "incorrect or corrupted.",
            "4.4 message 4 lexical marker provenance");

    // Projection is fail-closed: an unrelated record is left untouched.
    std::vector<std::string> gml{
        ":p.rpuNoResponse set. Forward to AIX NetView/6000",
        ":p.with resource name.",
        ":anchor id='MSG 2'.",
        ":p.with resource name.",
    };
    const auto applied =
        geist::detail::project_message_prose_row_joins_gml(gml, prose->joins);
    require(applied == 1 && gml.size() == 3 &&
                gml[0] == ":p.rpuNoResponse set. Forward to AIX NetView/6000 "
                          "with resource name." &&
                gml[2] == ":p.with resource name.",
            "4.4 join projection joined exactly the evidenced record");
  }

  // SC31-711 4.1.2 "LNM OS/2 Agent Application Generated Traps".
  {
    const auto sources =
        geist::detail::decode_logical_record_sources(context, 101, 105);
    std::string error;
    const auto prose =
        geist::detail::build_message_prose_source_ir(sources, &error);
    require(prose.has_value(), "4.1.2 prose source rejected: " + error);
    if (prose) {
      require(!prose->introduction.has_value(),
              "4.1.2 symbolic catalog must not admit a numeric introduction");
      std::string listing;
      for (const auto &join : prose->joins)
        listing += geist::detail::format_message_prose_row_join_ir(join) + "\n";
      const auto *socket = find_join(prose->joins, 102, 0);
      require(socket != nullptr && socket->visible_text == "has failed" &&
                  socket->previous_visible_text ==
                      "The socket connection between LNM for AIX and the LNM "
                      "OS/2 agent",
              "4.1.2 socket error record-continuation join\n" + listing);
    }
  }

  // N2AH1MST (MVS System Messages ADY-IDC, hosted DT 19910329000100): the
  // same width-1 marker geometry carries row-boundary controls whose decoded
  // spelling is a dictionary word. The trailing line fill separates them.
  {
    geist::detail::LogicalDecodeContext mvs;
    open_context(root / "N2AH1MST.BOO", mvs);
    const auto find_marker =
        [](const std::vector<geist::detail::MessageProseLexicalMarkerIR> &markers,
           std::uint32_t logical_record, std::size_t token)
        -> const geist::detail::MessageProseLexicalMarkerIR * {
      const auto found = std::find_if(
          markers.begin(), markers.end(), [&](const auto &marker) {
            return marker.source.logical_record == logical_record &&
                   marker.source.token_begin == token;
          });
      return found == markers.end() ? nullptr : &*found;
    };

    // 18.0 "COF Messages": logical records 1555-1662.
    {
      const auto sources =
          geist::detail::decode_logical_record_sources(mvs, 1555, 1663);
      std::string error;
      const auto prose =
          geist::detail::build_message_prose_source_ir(sources, &error);
      require(prose.has_value(), "N2AH1MST 18.0 prose source rejected: " + error);
      if (prose) {
        // COF001I: `virtual` + slot `access` (LR1555 token 111, byte 0x93f2c,
        // value 28) + one 10-space origin run + `lookaside`. Hosted renders
        // `start the virtual lookaside facility (VLF)`: the slot is a row
        // boundary, not text.
        require(find_marker(prose->lexical_markers, 1555, 111) == nullptr,
                "N2AH1MST 18.0 COF001I `access` boundary slot typed as lexical");
        require(find_marker(prose->lexical_markers, 1617, 207) == nullptr,
                "N2AH1MST 18.0 COF020I `access` boundary slot typed as lexical");
        // COF001I System Action: `job step,` + slot `the` (LR1555 token 218,
        // byte 0x93fb5, value 90) + 7-space fill + 14-space origin + `system`.
        // Hosted: `in a background job step, the` / `system issues`.
        const auto *the = find_marker(prose->lexical_markers, 1555, 218);
        require(the != nullptr && the->marker.decoded_text == "the" &&
                    the->marker.encoded_value == 90 &&
                    the->line_fill.token_index == 219 &&
                    the->line_fill.width == 7 &&
                    the->line_fill.bytes.begin == 0x93fb6 &&
                    the->previous_visible_text ==
                        "If you attempted to start VLF in a background job "
                        "step," &&
                    the->visible_text ==
                        "system issues this message to the job log.",
                "N2AH1MST 18.0 COF001I hanging `the` provenance");
        const auto *system = find_marker(prose->lexical_markers, 1555, 246);
        require(system != nullptr && system->marker.decoded_text == "system" &&
                    system->line_fill.width == 14,
                "N2AH1MST 18.0 COF001I hanging `system` provenance");
      }
    }

    // 26.0 "ICU Messages": logical records 2177-2259.
    {
      const auto sources =
          geist::detail::decode_logical_record_sources(mvs, 2177, 2260);
      std::string error;
      const auto prose =
          geist::detail::build_message_prose_source_ir(sources, &error);
      require(prose.has_value(), "N2AH1MST 26.0 prose source rejected: " + error);
      if (prose) {
        // ICU056I Operator Response: `Notify the security` + slot `a`
        // (LR2251 token 60, byte 0xcffd9, value 27) + one 10-space origin run
        // + `administrator.`. Hosted: `Notify the security administrator.`
        require(find_marker(prose->lexical_markers, 2251, 60) == nullptr,
                "N2AH1MST 26.0 ICU056I `a` boundary slot typed as lexical");
      }
    }

    // 22.0 "IAR Messages": logical records 1975-1990. IAR009I lists two
    // bulleted actions; each item record opens `(` + 10-space origin +
    // bullet sentinel + 2 spaces + text, so neither is a soft wrap.
    {
      const auto sources =
          geist::detail::decode_logical_record_sources(mvs, 1975, 1991);
      std::string error;
      const auto prose =
          geist::detail::build_message_prose_source_ir(sources, &error);
      require(prose.has_value(), "N2AH1MST 22.0 prose source rejected: " + error);
      if (prose) {
        require(find_join(prose->joins, 1984, 0) == nullptr,
                "N2AH1MST 22.0 IAR009I first bullet item typed as a soft wrap");
        require(find_join(prose->joins, 1985, 0) == nullptr,
                "N2AH1MST 22.0 IAR009I second bullet item typed as a soft wrap");
        // A genuine `?`-run wrap in the same topic is still typed.
        const auto *up = find_join(prose->joins, 1985, 136);
        require(up != nullptr && up->visible_text == "up." &&
                    up->start == geist::detail::PhysicalRowStartKind::placeholder_wrap,
                "N2AH1MST 22.0 IAR009I placeholder wrap join");
      }
    }

    // 23.0 "ICH Messages": logical records 1990-2112. ICH409I `This message
    // is issued if:` is followed by the ordinal item `1.` (LR2009 tokens 2-4:
    // `1`, attached `.`, space) and ICH408I `... puts the SETROPTS` by the
    // boundary slot `access` (LR2038 token 56, byte 0xbd9cb, value 28).
    {
      const auto sources =
          geist::detail::decode_logical_record_sources(mvs, 1990, 2113);
      std::string error;
      const auto prose =
          geist::detail::build_message_prose_source_ir(sources, &error);
      require(prose.has_value(), "N2AH1MST 23.0 prose source rejected: " + error);
      if (prose) {
        require(find_join(prose->joins, 2009, 0) == nullptr,
                "N2AH1MST 23.0 ICH409I ordinal item typed as a soft wrap");
        require(find_marker(prose->lexical_markers, 2038, 56) == nullptr,
                "N2AH1MST 23.0 ICH408I `access` boundary slot typed as lexical");
        // `not specified for` + `the` (LR2038 token 46, value 90) + 10-space
        // fill + 10-space origin + `profile`: hosted keeps `for the profile`.
        const auto *the = find_marker(prose->lexical_markers, 2038, 46);
        require(the != nullptr && the->line_fill.width == 10,
                "N2AH1MST 23.0 ICH408I hanging `the` provenance");
      }
    }

    const auto mvs_document = geist::BooDocument::open(root / "N2AH1MST.BOO");
    const auto cof = visible_text(mvs_document.topic_markdown("18.0"));
    require(cof.find("virtual access lookaside") == std::string::npos &&
                cof.find("start the virtual lookaside facility (VLF)") !=
                    std::string::npos,
            "N2AH1MST 18.0 restored the `access` boundary slot");
    const auto icu = visible_text(mvs_document.topic_markdown("26.0"));
    require(icu.find("security a administrator") == std::string::npos &&
                icu.find("Notify the security administrator.") !=
                    std::string::npos,
            "N2AH1MST 26.0 restored the `a` boundary slot");
    // N2AH1MST 22.0 now renders through the trap-catalog family, whose
    // entry model is one list item per message with inline fields, so a
    // field's paragraphs run together -- the same shape SC31-711 4.1.2,
    // 4.2.2 and 4.3.4 have had since that family landed. The row-level
    // assertions above still hold: the two `°` actions are separate physical
    // rows and neither is a soft wrap. What the rendered check can still
    // require of the new route is that no word is lost.
    const auto iar = visible_text(mvs_document.topic_markdown("22.0"));
    require(iar.find("Increase the size of the central storage trace buffers, "
                     "using the BUFF option") != std::string::npos &&
                iar.find("Decrease the need for buffers by specifying fewer "
                         "RSM trace functions and events") != std::string::npos,
            "N2AH1MST 22.0 kept both IAR009I bullet items");
    const auto ich = visible_text(mvs_document.topic_markdown("23.0"));
    require(ich.find("SETROPTS access MLACTIVE") == std::string::npos &&
                ich.find("is issued if: 1. During") == std::string::npos,
            "N2AH1MST 23.0 restored `access` or joined the ordinal item");
  }

  const auto document = geist::BooDocument::open(root / "SC31-711.boo");
  const auto application_traps = visible_text(document.topic_markdown("4.1.2"));
  require(application_traps.find(
              "**Action:** The socket connection between LNM for AIX and the "
              "LNM OS/2 agent has failed. Check the nettl log") !=
              std::string::npos,
          "4.1.2 socket error action paragraph was split");
  const auto agent_traps = visible_text(document.topic_markdown("4.1.3"));
  const auto first_trap = agent_traps.find("<a id=\"MSG 001\"></a>");
  require(first_trap != std::string::npos, "4.1.3 first trap anchor");
  const auto intro = agent_traps.substr(0, first_trap);
  for (const auto *paragraph : {
           "\n**Note:** These traps correspond to the DFIPD messages that are "
           "generated by the LNM OS/2 agent program and have the same number. "
           "You can look up a trap in the Messages chapter of the LAN Network "
           "Manager for OS/2 Version 2.0 documentation to obtain more "
           "information about the event that a trap is reporting on, such as "
           "error code descriptions and possible corrective actions.\n",
           "\nWhen the LNM for AIX Response indicates that the status will be "
           "set to a particular setting, this actually indicates the best, or "
           "worst, status that can be set for the resource from processing "
           "the trap. For example, if the LNM for AIX Response indicates to "
           "set the status to marginal and it is currently in a critical "
           "state, the resource will remain in the critical state until the "
           "condition causing the critical state is resolved. Similarly, if "
           "multiple resources can affect the status of a resource, a "
           "response that indicates to set the status to normal may be "
           "overriden by the state of another resource.\n",
           "\nThe traps in this section are defined under the "
           "1.3.6.1.4.1.2.6.20 enterprise ID, which is associated with LNM "
           "OS/2 agent.\n",
           "\nThe redirected traps are defined under the 1.3.6.1.4.1.2.6.21.1.1 "
           "enterprise ID, which is associated with LNM for AIX.\n",
       }) {
    require(intro.find(paragraph) != std::string::npos,
            std::string("4.1.3 introduction paragraph: ") + paragraph);
  }
  require(intro.find("This section lists the traps that can be sent by the "
                     "LNM OS/2 agent program and the actions that LNM for AIX "
                     "takes when these traps are received.") <
              intro.find("**Note:**"),
          "4.1.3 ST introduction precedes the restored note");
  for (const auto *leaked : {"resource.as", "agent.bridge", "< enterprise",
                             "actions. When"}) {
    require(agent_traps.find(leaked) == std::string::npos,
            std::string("4.1.3 leaked marker or lost paragraph: ") + leaked);
  }
  require(agent_traps.find(
              "Set segment status marginal. Add correlation information and "
              "return to AIX NetView/6000.") != std::string::npos &&
              agent_traps.find(
                  "concentrator qualifier for this segment. Add correlation "
                  "information and return to AIX NetView/6000.") !=
                  std::string::npos &&
              agent_traps.find("Add information and return") ==
                  std::string::npos,
          "4.1.3 dropped the lexical `correlation` marker in 101/180");
  require(agent_traps.find(
              "Add correlation information and return to AIX NetView/6000. "
              "The status of the segment is not changed to normal because, "
              "although the backup path has been recovered, the segment is "
              "still wrapped.") != std::string::npos,
          "4.1.3 message 329 response paragraph was split");
  require(agent_traps.find(
              "Issue run commands to get status of module and port. Update "
              "status to reflect status in run command response.") !=
              std::string::npos,
          "4.1.3 message 444 response paragraph was split");

  const auto fddi_traps = visible_text(document.topic_markdown("4.4"));
  require(fddi_traps.find(
              "rpuNoResponse set in the 8240 concentrator. The status of the "
              "resource is set to marginal. Forward to AIX NetView/6000 with "
              "resource name.") != std::string::npos,
          "4.4 message 1 response paragraph was split");
  require(fddi_traps.find(
              "This trap is generated when an no response has been received "
              "from an Remote Program Upload (RPU) Loader. This could "
              "indicate that the specified RPU file could not be found") !=
              std::string::npos,
          "4.4 message 2 description paragraph was split");
  require(fddi_traps.find(
              "indicating that the load file received was incorrect or "
              "corrupted.") != std::string::npos,
          "4.4 message 4 dropped the lexical `was` marker");
  require(fddi_traps.find("\nwith resource name.") == std::string::npos &&
              fddi_traps.find("\nfrom an Remote Program") == std::string::npos,
          "4.4 continuation rows still start their own paragraphs");
  return 0;
}
