#!/usr/bin/env python3
# Copyright 2026 Yvan Janssens
# SPDX-License-Identifier: Apache-2.0
"""Embeds the module's static assets into a C++ header.

mod_geist ships one file. Its CSS, JavaScript and icons are compiled in
rather than installed beside it, so an operator drops a single .so into
Apache and nothing else has to be deployed, versioned or made readable.

Usage: bundle.py <output header> <asset dir>
"""
import sys, pathlib

TYPES = {
    '.css': 'text/css; charset=utf-8',
    '.js': 'application/javascript; charset=utf-8',
    '.svg': 'image/svg+xml',
    '.ico': 'image/x-icon',
    '.png': 'image/png',
    '.woff2': 'font/woff2',
}


def main(out_path: str, asset_dir: str) -> int:
    root = pathlib.Path(asset_dir)
    assets = sorted(p for p in root.rglob('*') if p.is_file())
    if not assets:
        print(f'bundle.py: no assets under {root}', file=sys.stderr)
        return 1

    lines = [
        '// Generated by apache/tools/bundle.py. Do not edit.',
        '// SPDX-License-Identifier: Apache-2.0',
        '#pragma once',
        '',
        '#include <cstddef>',
        '',
        'namespace geist_httpd {',
        '',
        'struct EmbeddedAsset {',
        '  const char* name;',
        '  const char* content_type;',
        '  const unsigned char* data;',
        '  std::size_t size;',
        '};',
        '',
    ]

    entries = []
    for index, path in enumerate(assets):
        name = path.relative_to(root).as_posix()
        blob = path.read_bytes()
        ctype = TYPES.get(path.suffix.lower(), 'application/octet-stream')
        body = ','.join(str(b) for b in blob)
        lines.append(f'// {name} ({len(blob)} bytes)')
        lines.append(f'inline constexpr unsigned char kAsset{index}[] = {{{body}}};')
        entries.append((name, ctype, f'kAsset{index}', len(blob)))
    lines.append('')

    lines.append('inline constexpr EmbeddedAsset kEmbeddedAssets[] = {')
    for name, ctype, symbol, size in entries:
        lines.append(f'    {{"{name}", "{ctype}", {symbol}, {size}}},')
    lines.append('};')
    lines.append('')
    lines.append(f'inline constexpr std::size_t kEmbeddedAssetCount = {len(entries)};')
    lines.append('')
    lines.append('} // namespace geist_httpd')
    lines.append('')

    out = pathlib.Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text('\n'.join(lines))
    total = sum(size for _, _, _, size in entries)
    print(f'bundle.py: embedded {len(entries)} assets, {total} bytes -> {out}')
    return 0


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        raise SystemExit(2)
    raise SystemExit(main(sys.argv[1], sys.argv[2]))
